import {AbiCoder,Contract,ContractFactory,Interface,getAddress,getCreateAddress,getCreate2Address,keccak256,parseUnits,formatUnits,ZeroAddress,ZeroHash,toBeHex,concat,randomBytes,hexlify} from '../vendor/ethers.min.js';
import {PROTOCOL_ARTIFACTS} from './protocols-artifacts.mjs';
import {PROTOCOL_DEPLOYMENTS} from './protocols-deployments.mjs';

const coder=AbiCoder.defaultAbiCoder(), Q96=1n<<96n, MAX128=(1n<<128n)-1n;
const ERC20=['function name() view returns(string)','function symbol() view returns(string)','function decimals() view returns(uint8)','function totalSupply() view returns(uint256)','function balanceOf(address) view returns(uint256)','function allowance(address,address) view returns(uint256)','function approve(address,uint256) returns(bool)','function transfer(address,uint256) returns(bool)'];
const addr=x=>getAddress(x), eq=(a,b)=>addr(a)===addr(b), str=x=>String(x), nz=(x,label)=>{x=addr(x);if(x===ZeroAddress)throw Error(`${label} cannot be zero.`);return x;};
const uint=(x,label,max=(1n<<256n)-1n)=>{if(!/^\d+$/.test(String(x)))throw Error(`${label} must be a whole number.`);x=BigInt(x);if(x>max)throw Error(`${label} is too large.`);return x;};
const units=(x,decimals,label)=>{let n;try{n=parseUnits(String(x),decimals);}catch{throw Error(`${label} has invalid precision.`);}if(n<0n||n>MAX128)throw Error(`${label} is outside the supported amount range.`);return n;};
const tick=(x,label)=>{const n=Number(x);if(!Number.isSafeInteger(n)||Math.abs(n)>887272)throw Error(`${label} must be a valid Uniswap tick.`);return n;};
const json=x=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v);
export const CCA_PARAMETERS='tuple(address currency,address tokensRecipient,address fundsRecipient,uint64 startBlock,uint64 endBlock,uint64 claimBlock,uint256 tickSpacing,address validationHook,uint256 floorPrice,uint128 requiredCurrencyRaised,bytes auctionStepsData)';
export const CCA_MIGRATION='tuple(address token,address currency,uint64 migrationBlock,uint128 reservedTokenAmountForLP,address recipient,address positionRecipient,tuple(uint24 fee,int24 tickSpacing,address hook) poolParameters,bytes positionDefinitions,bytes lpAllocationSchedule)';
export const DOPPLER_INITIALIZER_TYPES=['uint256','uint256','uint256','uint256','int24','int24','uint256','int24','bool','uint256','uint24','int24'];
export const PROTOCOL_VERSIONS=Object.freeze({cca:{label:'Uniswap CCA v2.1.0',commit:'a56d42231e7bf048136d9d88fa61e8518c10c5ff',url:'https://github.com/Uniswap/continuous-clearing-auction/tree/a56d42231e7bf048136d9d88fa61e8518c10c5ff'},liquidityLauncher:{commit:'3a3103543f50a13a0ae52a253bb98a925d72146f',url:'https://github.com/Uniswap/liquidity-launcher/tree/3a3103543f50a13a0ae52a253bb98a925d72146f'},doppler:{label:'Doppler dynamic v4 auction',commit:'5754c7ee01f1bdbd6f07c62be721e1223b725ecd',url:'https://github.com/whetstoneresearch/doppler/tree/5754c7ee01f1bdbd6f07c62be721e1223b725ecd'}});

/** Price means whole currency units per whole token, converted without floating-point arithmetic. */
export function ccaPrice(value,tokenDecimals,currencyDecimals){const p=parseUnits(String(value),18);if(p<=0n)throw Error('Price must be positive.');const n=p*10n**BigInt(currencyDecimals)*Q96/(10n**18n*10n**BigInt(tokenDecimals));if(n===0n)throw Error('Price is below the contract precision.');return n;}
export function ccaHumanPrice(q,tokenDecimals,currencyDecimals){return formatUnits(BigInt(q)*10n**BigInt(tokenDecimals)*10n**18n/(Q96*10n**BigInt(currencyDecimals)),18);}
/** Linear issuance uses at most two exact integer steps; all 10,000,000 mps are conserved. */
export function linearCCAsteps(duration){const n=uint(duration,'Auction blocks',(1n<<40n)-1n);if(n===0n||n>10_000_000n)throw Error('Choose 1 to 10,000,000 auction blocks.');const rate=10_000_000n/n, remainder=10_000_000n%n;const word=(r,b)=>toBeHex((r<<40n)|b,8);return remainder===0n?word(rate,n):concat([word(rate,n-1n),word(rate+remainder,1n)]);}
export async function verifyProtocol(provider,address,name,blockTag='latest'){
  const a=PROTOCOL_ARTIFACTS[name];if(!a)throw Error('Unknown pinned protocol contract.');address=addr(address);const runtime=await provider.getCode(address,blockTag);
  for(const profile of [a,...(a.variants||[])]){
    if((runtime.length-2)/2!==profile.bytes)continue;let consistent=true;
    for(const group of profile.immutableGroups||[]){if(group.length<2)continue;const first=runtime.slice(2+group[0].start*2,2+(group[0].start+group[0].length)*2);for(const m of group.slice(1))if(runtime.slice(2+m.start*2,2+(m.start+m.length)*2)!==first)consistent=false;}
    if(!consistent)continue;let normalized=runtime.slice(2);for(const m of profile.masks)normalized=normalized.slice(0,m.start*2)+'0'.repeat(m.length*2)+normalized.slice((m.start+m.length)*2);if(keccak256('0x'+normalized)===profile.normalizedHash)return new Contract(address,a.abi,provider);
  }
  throw Error(`${name} executable differs from every pinned release profile. No transaction was prepared.`);
}
export async function protocolToken(provider,address,at='latest'){
  address=addr(address);if(address===ZeroAddress)return {address,name:'Native currency',symbol:'ETH',decimals:18};
  if(await provider.getCode(address,at)==='0x')throw Error('The selected token has no contract.');const token=new Contract(address,ERC20,provider),[name,symbol,d]=await Promise.all([token.name({blockTag:at}),token.symbol({blockTag:at}),token.decimals({blockTag:at})]);const decimals=Number(d);if(!Number.isInteger(decimals)||decimals>36)throw Error('Unsupported token decimals.');return {address,name,symbol,decimals};
}
export async function protocolLogs(provider,filter,{fromBlock=0,toBlock,span=1500,maxPages=128}={}){
  const address=nz(filter.address,'History contract'),topics=filter.topics??await filter.event?.getTopicFilter();if(!Array.isArray(topics)||!topics[0])throw Error('A resolved event topic is required for protocol history.');
  const end=Number(toBlock??await provider.getBlockNumber()),start=Number(fromBlock);if(![start,end,span,maxPages].every(Number.isSafeInteger)||start<0||start>end||span<1||span>1500||maxPages<1||maxPages>128)throw Error('Invalid history block range.');if(Math.ceil((end-start+1)/span)>maxPages)throw Error('This history range exceeds 192,000 blocks. Choose the history start and end blocks.');const logs=[];
  for(let from=start;from<=end;from+=span)logs.push(...await provider.getLogs({address,topics,fromBlock:from,toBlock:Math.min(end,from+span-1)}));return logs;
}
export async function mineProtocolSalt({deployer,initCodeHash,flags,caller=null,start=0n,limit=1_000_000,onProgress,signal}){
  deployer=addr(deployer);for(let i=0;i<limit;i++){if(signal?.aborted)throw Error('Deployment search cancelled.');const salt=toBeHex(BigInt(start)+BigInt(i),32),bound=caller?keccak256(coder.encode(['address','bytes32'],[caller,salt])):salt;const address=getCreate2Address(deployer,bound,initCodeHash);if((BigInt(address)&0x3fffn)===BigInt(flags))return {salt,address,iterations:i+1};if(i%512===0){onProgress?.(i);await new Promise(r=>setTimeout(r,0));}}throw Error('No matching hook address in this search window. Continue with a new start.');
}
export function dopplerCloneAddress(factory,implementation,salt){const code=concat(['0x602c3d8160093d39f33d3d3d3d363d3d37363d73',implementation,'0x5af43d3d93803e602a57fd5bf3']);return getCreate2Address(factory,salt,keccak256(code));}
export async function verifyDopplerToken(provider,address,blockTag='latest'){const code=(await provider.getCode(address,blockTag)).toLowerCase(),prefix='0x3d3d3d3d363d3d37363d73',suffix='5af43d3d93803e602a57fd5bf3';if(code.length!==90||!code.startsWith(prefix)||!code.endsWith(suffix))throw Error('The token is not the pinned Doppler proxy format.');const implementation=addr('0x'+code.slice(prefix.length,prefix.length+40));await verifyProtocol(provider,implementation,'DopplerERC20V1',blockTag);return new Contract(address,PROTOCOL_ARTIFACTS.DopplerERC20V1.abi,provider);}

/** All writes become unsigned shared-chain plans; chain review owns signing, replacement and recovery. */
export class OfficialProtocolClient {
  constructor(chain){this.chain=chain;}
  async context(){const ch=this.chain;if(!ch?.provider||!ch.address)throw Error('Connect a wallet first.');const generation=ch.generation;await ch.assertContext(generation);const block=await ch.provider.getBlock('latest');if(!block?.hash)throw Error('Current chain block unavailable.');return {provider:ch.provider,payer:addr(ch.payer||ch.address),signer:addr(ch.address),chainId:Number(ch.chainId),generation,block,at:{blockTag:block.number}};}
  async stable(c){await this.chain.assertContext(c.generation);if(this.chain.provider!==c.provider||!eq(this.chain.payer||this.chain.address,c.payer))throw Error('Funding account changed.');if((await c.provider.getBlock(c.block.number))?.hash!==c.block.hash)throw Error('The reviewed state block changed. Refresh this operation.');}
  async plan(c,target,method,args,{kind,purpose,spend=[],value=0n,summary={},meta={},deadline=c.block.timestamp+900,nftCompatible=true}={}){await this.stable(c);return this.chain.prepareExternal({kind,purpose,chainId:c.chainId,payer:c.payer,request:{to:target.target,data:target.interface.encodeFunctionData(method,args),value},spend,deadline,summary:{purpose,protocol:kind.startsWith('official-cca')?'Uniswap CCA':'Doppler',fundingAccount:c.payer,...summary},meta:{stateBlock:c.block.number,stateBlockHash:c.block.hash,...meta}},{nftCompatible});}
  async setup(name,args,{create2,salt}={}){const c=await this.context(),a=PROTOCOL_ARTIFACTS[name],bytecode=PROTOCOL_DEPLOYMENTS[name];if(!a||!bytecode||keccak256(bytecode)!==a.creationHash)throw Error('Deployment payload integrity failed.');if(c.payer!==c.signer)throw Error('Select wallet funding for protocol infrastructure deployment.');const request=await new ContractFactory(a.abi,bytecode).getDeployTransaction(...args);let predictedAddress;
    if(create2){const helper=await verifyProtocol(c.provider,create2,'OfficialCreate2',c.block.number);salt=salt||ZeroHash;predictedAddress=getCreate2Address(helper.target,keccak256(coder.encode(['address','bytes32'],[c.payer,salt])),keccak256(request.data));request.to=helper.target;request.data=helper.interface.encodeFunctionData('deploy',[salt,request.data]);}
    else{request.nonce=await c.provider.getTransactionCount(c.signer,'pending');predictedAddress=getCreateAddress({from:c.signer,nonce:request.nonce});}
    await this.stable(c);return this.chain.prepareExternal({kind:'official-setup',purpose:`Deploy pinned ${name}`,chainId:c.chainId,request,spend:[],deadline:c.block.timestamp+900,summary:{contract:name,predictedAddress,source:PROTOCOL_VERSIONS[a.group]?.url||'ANIMA protocol periphery'},meta:{contractName:name,predictedAddress}});
  }
  async ccaCreate(input){const c=await this.context(),factory=await verifyProtocol(c.provider,input.factory,'ContinuousClearingAuctionFactory',c.block.number),token=await protocolToken(c.provider,nz(input.token,'Auction token'),c.block.number),currency=await protocolToken(c.provider,input.currency||ZeroAddress,c.block.number),total=units(input.amount,token.decimals,'Auction supply');if(total===0n)throw Error('Auction supply must be positive.');
    const controller=await factory.protocolFeeController(c.at);if(controller!==ZeroAddress)await verifyProtocol(c.provider,controller,'ProtocolFeeController',c.block.number);
    const startBlock=uint(input.startBlock,'Start block',(1n<<64n)-1n),endBlock=uint(input.endBlock,'End block',(1n<<64n)-1n),claimBlock=uint(input.claimBlock??input.endBlock,'Claim block',(1n<<64n)-1n);if(startBlock<=BigInt(c.block.number)||endBlock<=startBlock||claimBlock<endBlock)throw Error('Choose future start/end blocks and a claim block at or after the end.');
    const rawFloor=ccaPrice(input.floorPrice,token.decimals,currency.decimals),tickSpacing=ccaPrice(input.priceStep,token.decimals,currency.decimals),floorPrice=((rawFloor+tickSpacing-1n)/tickSpacing)*tickSpacing;
    const recipient=nz(input.recipient||c.payer,'Funds recipient'),salt=input.salt||hexlify(randomBytes(32));
    let target,params={currency:currency.address,tokensRecipient:recipient,fundsRecipient:recipient,startBlock,endBlock,claimBlock,tickSpacing,validationHook:addr(input.validationHook||ZeroAddress),floorPrice,requiredCurrencyRaised:units(input.minimumRaise||'0',currency.decimals,'Minimum raise'),auctionStepsData:input.auctionStepsData||linearCCAsteps(endBlock-startBlock)};
    if(params.validationHook!==ZeroAddress&&await c.provider.getCode(params.validationHook,c.block.number)==='0x')throw Error('Validation hook has no deployed code.');
    let method,args,predictedAuction,migration=null;
    if(input.strategy){target=await verifyProtocol(c.provider,input.strategy,'LBPStrategy',c.block.number);if(!eq(await target.initializerFactory(c.at),factory.target))throw Error('The strategy is bound to another CCA factory.');const manager=await target.poolManager(c.at),pm=await target.positionManager(c.at);await Promise.all([verifyProtocol(c.provider,manager,'PoolManager',c.block.number),verifyProtocol(c.provider,pm,'PositionManager',c.block.number)]);
      const reserve=units(input.reserve,token.decimals,'LP token reserve');if(reserve===0n||reserve>=total)throw Error('The LP reserve must be positive and smaller than the total distributed amount.');const fee=Number(uint(input.fee??3000,'Pool fee',1_000_000n)),spacing=Number(uint(input.tickSpacing??60,'Pool tick spacing',32767n));if(spacing===0)throw Error('Pool tick spacing must be positive.');
      const definitions=input.positions||[{offsetLower:-887272,offsetUpper:887272,weight:10_000_000,overridePositionRecipient:ZeroAddress}],brackets=input.lpBrackets||[{lowerThreshold:0,rate:Number(uint(input.lpRate??10_000_000,'LP allocation rate',10_000_000n))}];
      migration={token:token.address,currency:currency.address,migrationBlock:uint(input.migrationBlock??(endBlock+1n),'Migration block',(1n<<64n)-1n),reservedTokenAmountForLP:reserve,recipient,positionRecipient:nz(input.positionRecipient||recipient,'LP recipient'),poolParameters:{fee,tickSpacing:spacing,hook:addr(input.poolHook||ZeroAddress)},positionDefinitions:coder.encode(['tuple(int24 offsetLower,int24 offsetUpper,uint24 weight,address overridePositionRecipient)[]'],[definitions]),lpAllocationSchedule:coder.encode(['tuple(uint128 lowerThreshold,uint24 rate)[]'],[brackets])};
      if(migration.migrationBlock<=endBlock)throw Error('Migration must begin after the last auction block.');params.fundsRecipient=target.target;params.tokensRecipient=recipient;
      const encoded=coder.encode([CCA_PARAMETERS],[params]),derivedSalt=keccak256(coder.encode(['bytes32',CCA_MIGRATION],[salt,migration]));predictedAuction=await factory['getAddress(address,uint256,bytes,bytes32,address)'](token.address,total-reserve,encoded,derivedSalt,target.target,c.at);method='initializeDistribution';args=[token.address,total,coder.encode([CCA_MIGRATION,'bytes'],[migration,encoded]),salt];
    }else{target=await verifyProtocol(c.provider,input.launcher,'OfficialCCALauncher',c.block.number);if(!eq(await target.factory(c.at),factory.target))throw Error('The launcher is bound to another CCA factory.');const config=coder.encode([CCA_PARAMETERS],[params]);predictedAuction=await target.predict(token.address,total,config,salt,c.payer,c.at);method='create';args=[token.address,total,config,salt];}
    if(await c.provider.getCode(predictedAuction,c.block.number)!=='0x')throw Error('This deterministic auction already exists. Open it or select a new salt.');
    return this.plan(c,target,method,args,{kind:'official-cca-create',purpose:migration?'Create, fund and commit the CCA liquidity migration':'Create and fund the official CCA auction',spend:[{tokenAddress:token.address,amount:total}],summary:{token:token.symbol,amount:formatUnits(total,token.decimals),currency:currency.symbol,floorPrice:ccaHumanPrice(floorPrice,token.decimals,currency.decimals),priceRounding:'Floor rounds up to the next contract tick; bidder maximums round down.',startBlock:str(startBlock),endBlock:str(endBlock),claimBlock:str(claimBlock),recipient,auction:predictedAuction,protocolFeeController:controller,feePolicy:controller===ZeroAddress?'No protocol controller':'Controller fees can change before sweep',migration:migration?{reserve:input.reserve,positionRecipient:migration.positionRecipient,block:str(migration.migrationBlock),lpRate:input.lpRate??10_000_000}:'Standalone; no pool is promised'},meta:{protocol:'official-cca',auction:predictedAuction,token:token.address,factory:factory.target,strategy:migration?target.target:null,termsHash:keccak256(coder.encode([CCA_PARAMETERS],[params]))}});
  }
  async readCCA({provider=this.chain?.provider,auction,owner=this.chain?.payer||this.chain?.address,fromBlock,toBlock,bidOffset=0,bidLimit=24}){if(!provider)throw Error('Choose a read provider.');bidOffset=Number(bidOffset);bidLimit=Number(bidLimit);if(!Number.isSafeInteger(bidOffset)||bidOffset<0||!Number.isSafeInteger(bidLimit)||bidLimit<1||bidLimit>100)throw Error('Choose a nonnegative bid offset and 1 to 100 bids per page.');const block=await provider.getBlock('latest'),a=await verifyProtocol(provider,auction,'ContinuousClearingAuction',block.number),at={blockTag:block.number};const fields=['token','currency','totalSupply','startBlock','endBlock','claimBlock','floorPrice','tickSpacing','clearingPrice','currencyRaised','totalCleared','isGraduated','tokensRecipient','fundsRecipient','nextBidId','sweepCurrencyBlock','sweepUnsoldTokensBlock'];const values=await Promise.all(fields.map(k=>a[k](at))),s=Object.fromEntries(fields.map((k,i)=>[k,typeof values[i]==='bigint'?str(values[i]):values[i]]));
    const [token,currency]=await Promise.all([protocolToken(provider,s.token,block.number),protocolToken(provider,s.currency,block.number)]);const start=Number(s.startBlock);let bids=[];
    const history={fromBlock:Number(fromBlock??Math.max(Math.min(start,block.number),block.number-191999)),toBlock:Number(toBlock??block.number),bidOffset,bidLimit,totalBids:0,hasNext:false};if(history.toBlock>block.number)throw Error('History end exceeds the current block.');
    if(owner){const logs=await protocolLogs(provider,{address:a.target,event:a.filters.BidSubmitted(null,owner)},history),allIds=[...new Set(logs.map(l=>a.interface.parseLog(l)).filter(e=>e?.name==='BidSubmitted').map(e=>e.args.id.toString()))],ids=allIds.slice(bidOffset,bidOffset+bidLimit);history.totalBids=allIds.length;history.hasNext=bidOffset+bidLimit<allIds.length;bids=await Promise.all(ids.map(async id=>{const b=await a.bids(id,at);return {id,startBlock:Number(b.startBlock),exitedBlock:Number(b.exitedBlock),maxPrice:str(b.maxPrice),owner:b.owner,amount:str(b.amountQ96/Q96),tokensFilled:str(b.tokensFilled)};}));}
    return {...s,chainId:Number((await provider.getNetwork()).chainId),auction:a.target,blockNumber:block.number,blockHash:block.hash,tokenInfo:token,currencyInfo:currency,bids,history,phase:block.number<start?'scheduled':block.number<Number(s.endBlock)?'bidding':s.isGraduated?'graduated':'ended',checkpointWarning:'Clearing totals reflect the latest onchain checkpoint; refresh/finalize before settlement.',formatted:{raised:formatUnits(s.currencyRaised,currency.decimals),floor:ccaHumanPrice(s.floorPrice,token.decimals,currency.decimals),clearing:ccaHumanPrice(s.clearingPrice,token.decimals,currency.decimals)}};
  }
  async ccaBid(input){const c=await this.context(),a=await verifyProtocol(c.provider,input.auction,'ContinuousClearingAuction',c.block.number),at=c.at;const [token,currency,start,end,step]=await Promise.all([a.token(at),a.currency(at),a.startBlock(at),a.endBlock(at),a.tickSpacing(at)]);if(BigInt(c.block.number)<start||BigInt(c.block.number)>=end)throw Error('This CCA is not accepting bids at the current block.');const [t,q]=await Promise.all([protocolToken(c.provider,token,c.block.number),protocolToken(c.provider,currency,c.block.number)]),amount=units(input.amount,q.decimals,'Bid amount'),requestedPrice=ccaPrice(input.maxPrice,t.decimals,q.decimals),price=requestedPrice/step*step;if(!amount||price===0n)throw Error('Use a positive bid and a maximum price above one price step.');const args=[price,amount,nz(input.recipient||c.payer,'Bid recipient'),input.hookData||'0x'];
    return this.plan(c,a,'submitBid(uint256,uint128,address,bytes)',args,{kind:'official-cca-bid',purpose:'Submit a price-limited official CCA bid',spend:currency===ZeroAddress?[]:[{tokenAddress:currency,amount}],value:currency===ZeroAddress?amount:0n,summary:{amount:input.amount,currency:q.symbol,maximumPrice:ccaHumanPrice(price,t.decimals,q.decimals),recipient:args[2],refunds:'Unused bidding currency returns to the bid owner on exit'},meta:{protocol:'official-cca',auction:a.target}});
  }
  async ccaAction({auction,action,bidId,fromBlock,strategy,lastFullyFilledCheckpointBlock,outbidBlock}){const c=await this.context(),a=await verifyProtocol(c.provider,auction,'ContinuousClearingAuction',c.block.number);let target=a,method,args=[],purpose,meta={protocol:'official-cca',auction:a.target};
    if(action==='checkpoint'){method='checkpoint';purpose='Checkpoint the official auction clearing state';}
    else if(action==='claim'){method='claimTokens';args=[uint(bidId,'Bid ID')];const bid=await a.bids(args[0],c.at);if(!bid.exitedBlock||!bid.tokensFilled)throw Error('Exit a filled bid before claiming; this bid has no unclaimed filled tokens.');purpose='Claim filled tokens to the recorded bid owner';}
    else if(action==='sweepTokens'){if(!eq(await a.tokensRecipient(c.at),c.payer))throw Error('Only the committed unsold-token recipient can sweep these tokens.');method='sweepUnsoldTokens';purpose='Return unsold auction tokens to the committed recipient';}
    else if(action==='sweepCurrency'){if(!eq(await a.fundsRecipient(c.at),c.payer))throw Error('Only the committed funds recipient can sweep proceeds. Auctions committed to a migration strategy use Migrate to perform that sweep.');method='sweepCurrency';purpose='Send final proceeds to the committed recipient';}
    else if(action==='migrate'){target=await verifyProtocol(c.provider,strategy,'LBPStrategy',c.block.number);const params=await target.initializers(a.target,c.at);if(!eq(params.token,await a.token(c.at))||!eq(await a.fundsRecipient(c.at),target.target))throw Error('This auction is not registered with that strategy.');method='migrate';args=[a.target];purpose='Migrate the CCA into v4 liquidity or execute its committed reserve recovery';meta.strategy=target.target;}
    else if(action==='exit'){const id=uint(bidId,'Bid ID'),b=await a.bids(id,c.at);if(b.exitedBlock!==0n)throw Error('This bid is already exited.');const end=await a.endBlock(c.at),finished=BigInt(c.block.number)>=end;if(finished&&await a.lastCheckpointedBlock(c.at)!==end)throw Error('Finalize the auction checkpoint before choosing this bid’s settlement path.');if(finished&&(!await a.isGraduated(c.at)||b.maxPrice>await a.clearingPrice(c.at))){method='exitBid';args=[id];}
      else{let last=b.startBlock,outbid=0n;if(lastFullyFilledCheckpointBlock!==undefined||outbidBlock!==undefined){last=uint(lastFullyFilledCheckpointBlock,'Last fully filled checkpoint',(1n<<64n)-1n);outbid=uint(outbidBlock??0,'Outbid checkpoint',(1n<<64n)-1n);}else{let number=b.startBlock,steps=0;const sentinel=(1n<<64n)-1n;while(number!==sentinel){if(++steps>2048)throw Error('This bid spans over 2,048 checkpoints. Enter its exact last-filled/outbid checkpoint hints in advanced recovery.');const cp=await a.checkpoints(number,c.at);if(cp.clearingPrice<b.maxPrice)last=number;else if(cp.clearingPrice>b.maxPrice){outbid=number;break;}if(cp.next===sentinel)break;if(cp.next<=number)throw Error('The auction returned an invalid checkpoint link.');number=cp.next;}}method='exitPartiallyFilledBid';args=[id,last,outbid];await a.exitPartiallyFilledBid.staticCall(...args,c.at);}purpose='Exit this bid and refund its unspent currency to the bid owner';}
    else throw Error('Unsupported CCA operation.');return this.plan(c,target,method,args,{kind:'official-cca-'+action,purpose,summary:{auction:a.target,bidId:bidId??null,settlement:action==='migrate'?'A successful transaction can report MigrationFailed and recover reserves instead. Read its events before claiming a pool exists.':undefined},meta});
  }
  async dopplerScope(input,c){
    const airlock=await verifyProtocol(c.provider,input.airlock,'Airlock',c.block.number),names={tokenFactory:'DopplerERC20V1Factory',poolInitializer:'UniswapV4Initializer',governanceFactory:'LaunchpadGovernanceFactory',liquidityMigrator:'UniswapV2MigratorSplit'},modules={};
    for(const [key,name] of Object.entries(names)){modules[key]=await verifyProtocol(c.provider,input[key],name,c.block.number);const expected={tokenFactory:1,governanceFactory:2,poolInitializer:3,liquidityMigrator:4}[key];if(Number(await airlock.getModuleState(modules[key].target,c.at))!==expected)throw Error(`${name} is not approved in this Airlock.`);if(key!=='governanceFactory'&&!eq(await modules[key].airlock(c.at),airlock.target))throw Error(`${name} belongs to another Airlock.`);}
    const initializer=modules.poolInitializer,manager=await initializer.poolManager(c.at),deployerAddress=await initializer.deployer(c.at),deployer=await verifyProtocol(c.provider,deployerAddress,'DopplerDeployer',c.block.number);if(!eq(await deployer.poolManager(c.at),manager))throw Error('Doppler deployer and initializer use different PoolManagers.');await verifyProtocol(c.provider,manager,'PoolManager',c.block.number);
    const implementation=await modules.tokenFactory.IMPLEMENTATION(c.at);await verifyProtocol(c.provider,implementation,'DopplerERC20V1',c.block.number);const topUp=await verifyProtocol(c.provider,await modules.liquidityMigrator.TOP_UP_DISTRIBUTOR(c.at),'TopUpDistributor',c.block.number);if(!eq(await topUp.AIRLOCK(c.at),airlock.target))throw Error('The top-up distributor belongs to another Airlock.');return {...c,airlock,...modules,manager,deployer,implementation,topUp};
  }
  async dopplerCreate(input,{signal,onProgress}={}){
    const c=await this.dopplerScope(input,await this.context()),q=await protocolToken(c.provider,input.numeraire||ZeroAddress,c.block.number),supply=units(input.supply,18,'Token supply'),sale=units(input.amount,18,'Sale allocation'),recipient=nz(input.recipient||c.payer,'Retained token and LP recipient');if(!supply||!sale||sale>supply)throw Error('Choose a positive sale allocation no larger than total supply.');
    const name=String(input.name||'').trim(),symbol=String(input.symbol||'').trim();if(!name||!symbol||new TextEncoder().encode(name).length>64||new TextEncoder().encode(symbol).length>16)throw Error('Provide a token name up to 64 bytes and symbol up to 16 bytes.');
    const minimum=units(input.minimumRaise||'0',q.decimals,'Minimum proceeds'),maximum=units(input.maximumRaise,q.decimals,'Maximum proceeds');if(maximum<minimum||maximum===0n)throw Error('Maximum proceeds must be positive and at least the minimum.');
    const starts=uint(input.starts,'Start timestamp'),ends=uint(input.ends,'End timestamp'),epoch=uint(input.epochLength,'Epoch seconds');if(starts<=BigInt(c.block.timestamp)||ends<=starts||epoch===0n||(ends-starts)%epoch)throw Error('Use a future start and an auction duration exactly divisible by the epoch length.');
    const startingTick=tick(input.startingTick,'Starting tick'),endingTick=tick(input.endingTick,'Ending tick'),gamma=tick(input.gamma,'Gamma'),spacing=Number(uint(input.tickSpacing??8,'Tick spacing',32767n)),slugs=uint(input.slugs??10,'Price discovery positions',15n),fee=uint(input.fee??3000,'LP fee',999999n);if(!spacing||gamma<=0||BigInt(gamma)*epoch/(ends-starts)<BigInt(spacing)||!slugs)throw Error('Gamma and epoch length must permit at least one tick spacing of movement.');
    const isToken0=input.isToken0===true;if((isToken0&&startingTick<endingTick)||(!isToken0&&startingTick>endingTick))throw Error('Tick direction must match the token ordering.');
    const initArgs=[c.manager,sale,minimum,maximum,starts,ends,startingTick,endingTick,epoch,gamma,isToken0,slugs,c.poolInitializer.target,fee],initCode=(await new ContractFactory(PROTOCOL_ARTIFACTS.Doppler.abi,PROTOCOL_DEPLOYMENTS.Doppler).getDeployTransaction(...initArgs)).data;
    const initHash=keccak256(initCode);let found,start=BigInt(input.searchStart||0);for(let batch=0;batch<16;batch++){found=await mineProtocolSalt({deployer:c.deployer.target,initCodeHash:initHash,flags:0x38e0,start,limit:200000,signal,onProgress});const asset=dopplerCloneAddress(c.tokenFactory.target,c.implementation,found.salt);if((BigInt(asset)<BigInt(q.address))===isToken0&&await c.provider.getCode(asset,c.block.number)==='0x'&&await c.provider.getCode(found.address,c.block.number)==='0x'){found.asset=asset;break;}start=BigInt(found.salt)+1n;found=null;}if(!found)throw Error('No compatible unused token/hook pair in this search. Continue with another search start.');
    const schedules=input.vestingSchedules||[],allocations=input.vestingAllocations||[],vested=allocations.reduce((n,a)=>n+units(a.amount,18,'Vested allocation'),0n);if(vested+sale>supply)throw Error('Vested and sale allocations exceed the issued supply.');
    const tokenFactoryData=coder.encode(['string','string','tuple(uint64 cliff,uint64 duration)[]','address[]','uint256[]','uint256[]','string','uint256','uint48','address','address[]'],[name,symbol,schedules,allocations.map(a=>nz(a.beneficiary,'Vesting beneficiary')),allocations.map(a=>uint(a.scheduleId,'Vesting schedule')),allocations.map(a=>units(a.amount,18,'Vested allocation')),input.tokenURI||'',0,0,ZeroAddress,[]]);
    const share=units(input.proceedsShare||'0',18,'Proceeds share');if(share>5n*10n**17n)throw Error('The selected official migrator caps the proceeds split at 50%.');if(share>0n&&!await c.topUp.canPullUp(c.liquidityMigrator.target,c.at))throw Error('The selected migrator is not enabled for proceeds top-up distribution.');const splitRecipient=share>0n?nz(input.proceedsRecipient||recipient,'Proceeds recipient'):ZeroAddress;
    const params={initialSupply:supply,numTokensToSell:sale,numeraire:q.address,tokenFactory:c.tokenFactory.target,tokenFactoryData,governanceFactory:c.governanceFactory.target,governanceFactoryData:coder.encode(['address'],[recipient]),poolInitializer:c.poolInitializer.target,poolInitializerData:coder.encode(DOPPLER_INITIALIZER_TYPES,[minimum,maximum,starts,ends,startingTick,endingTick,epoch,gamma,isToken0,slugs,fee,spacing]),liquidityMigrator:c.liquidityMigrator.target,liquidityMigratorData:coder.encode(['address','uint256'],[splitRecipient,share]),integrator:addr(input.integrator||ZeroAddress),salt:found.salt};
    return this.plan(c,c.airlock,'create',[params],{kind:'official-doppler-create',purpose:'Create the official Doppler token, dynamic auction and committed migration',summary:{name,symbol,supply:input.supply,auctionAllocation:input.amount,minimumRaise:input.minimumRaise||'0',maximumRaise:input.maximumRaise,currency:q.symbol,starts:str(starts),ends:str(ends),recipient,asset:found.asset,hook:found.address,proceedsShare:input.proceedsShare||'0',protocolPolicy:'The official v2 migrator locks 5% of LP for one year. Locked-slice fees go to the Airlock owner; principal goes to the selected recipient. Airlock also takes its protocol/integrator migration fees.',failure:'If the minimum is missed, holders sell tokens into the protocol refund curve; this is not a guaranteed refund of each historical purchase price.'},meta:{protocol:'official-doppler',airlock:c.airlock.target,token:found.asset,hook:found.address,termsHash:keccak256(c.airlock.interface.encodeFunctionData('create',[params]))}});
  }
  async readDoppler({provider=this.chain?.provider,airlock,asset}){
    if(!provider)throw Error('Choose a read provider.');const block=await provider.getBlock('latest'),at={blockTag:block.number},a=await verifyProtocol(provider,airlock,'Airlock',block.number),data=await a.getAssetData(asset,at);if(data.pool===ZeroAddress)throw Error('This Airlock has no record for that token.');const hook=await verifyProtocol(provider,data.pool,'Doppler',block.number),initializer=await verifyProtocol(provider,data.poolInitializer,'UniswapV4Initializer',block.number),migrator=await verifyProtocol(provider,data.liquidityMigrator,'UniswapV2MigratorSplit',block.number);if(!eq(await hook.initializer(at),initializer.target)||!eq(await initializer.airlock(at),a.target)||!eq(await migrator.airlock(at),a.target))throw Error('The official protocol contracts have inconsistent parent bindings.');
    const token=await verifyDopplerToken(provider,asset,block.number),key=await hook.poolKey(at),[t,q,state,starts,ends,min,max,failed,early,locked,lockerAddress]=await Promise.all([protocolToken(provider,asset,block.number),protocolToken(provider,data.numeraire,block.number),hook.state(at),hook.startingTime(at),hook.endingTime(at),hook.minimumProceeds(at),hook.maximumProceeds(at),hook.insufficientProceeds(at),hook.earlyExit(at),token.isPoolLocked(at),migrator.locker(at)]),locker=await verifyProtocol(provider,lockerAddress,'UniswapV2Locker',block.number),lock=await locker.getState(data.migrationPool,at);
    if(!eq(await hook.poolManager(at),await initializer.poolManager(at))||!eq(await locker.migrator(at),migrator.target))throw Error('The Doppler hook or LP locker has inconsistent protocol bindings.');
    return {protocol:'official-doppler',chainId:Number((await provider.getNetwork()).chainId),blockNumber:block.number,blockHash:block.hash,timestamp:block.timestamp,airlock:a.target,asset:addr(asset),hook:hook.target,poolInitializer:initializer.target,liquidityMigrator:migrator.target,manager:await initializer.poolManager(at),migrationPool:data.migrationPool,recipient:data.timelock,governance:data.governance,integrator:data.integrator,tokenInfo:t,currencyInfo:q,poolId:keccak256(coder.encode(['tuple(address currency0,address currency1,uint24 fee,int24 tickSpacing,address hooks)'],[key])),poolKey:{currency0:key.currency0,currency1:key.currency1,fee:Number(key.fee),tickSpacing:Number(key.tickSpacing),hooks:key.hooks},starts:Number(starts),ends:Number(ends),minimum:str(min),maximum:str(max),proceeds:str(state.totalProceeds),tokensSold:str(state.totalTokensSold),insufficientProceeds:failed,earlyExit:early,migrated:!locked,phase:!locked?'migrated':block.timestamp<Number(starts)?'scheduled':failed||(block.timestamp>=Number(ends)&&state.totalProceeds<min)?'refund-curve':early||block.timestamp>=Number(ends)?'ready-to-migrate':'trading',locker:locker.target,lpLock:{recipient:lock.recipient,minUnlockDate:Number(lock.minUnlockDate)},formatted:{proceeds:formatUnits(state.totalProceeds,q.decimals),minimum:formatUnits(min,q.decimals),maximum:formatUnits(max,q.decimals),sold:formatUnits(state.totalTokensSold,t.decimals)}};
  }
  async dopplerQuote(input){const provider=input.provider||this.chain?.provider;if(!provider)throw Error('Choose a read provider.');const s=await this.readDoppler({...input,provider}),lens=await verifyProtocol(provider,input.quoter,'OfficialV4QuoteLens',s.blockNumber);if(!eq(await lens.manager({blockTag:s.blockNumber}),s.manager))throw Error('Quote lens uses another PoolManager.');if(s.migrated)throw Error('This auction migrated.');const sell=input.side==='sell',tokenIn=sell?s.tokenInfo:s.currencyInfo,tokenOut=sell?s.currencyInfo:s.tokenInfo,amount=units(input.amount,tokenIn.decimals,'Quote input'),direction=eq(tokenIn.address,s.poolKey.currency0),limit=direction?4295128740n:1461446703485210103287273052203988822378723970341n;const [spent,received]=await lens.quote.staticCall(s.poolKey,direction,amount,limit,{blockTag:s.blockNumber});return {protocol:'official-doppler',source:'Actual PoolManager and Doppler hook execution rolled back by the quote lens',blockNumber:s.blockNumber,blockHash:s.blockHash,input:tokenIn.address,output:tokenOut.address,amount:str(amount),spent:str(spent),received:str(received),unusedInput:str(amount-spent),formatted:{spent:formatUnits(spent,tokenIn.decimals),received:formatUnits(received,tokenOut.decimals)},fees:'Net amounts include every fee effect of the actual swap. Airlock migration fees are assessed separately at migration, not added to this swap quote.'};}
  async ccaCheckpointPreview({provider=this.chain?.provider,auction}){const block=await provider.getBlock('latest'),a=await verifyProtocol(provider,auction,'ContinuousClearingAuction',block.number),checkpoint=await a.checkpoint.staticCall({blockTag:block.number});return {protocol:'official-cca',blockNumber:block.number,blockHash:block.hash,checkpoint:JSON.parse(json(checkpoint.toObject())),scope:'Exact current checkpoint execution. Future bids and eventual auction allocations are not predicted.'};}
  async dopplerSwap(input){const c=await this.context(),s=await this.readDoppler({...input,provider:c.provider}),router=await verifyProtocol(c.provider,input.router,'OfficialV4SwapRouter',c.block.number);if(!eq(await router.manager(c.at),s.manager))throw Error('Swap router uses another PoolManager.');if(s.migrated)throw Error('This auction migrated. Use the new pool to trade.');const sell=input.side==='sell',inputToken=sell?s.tokenInfo:s.currencyInfo,outputToken=sell?s.currencyInfo:s.tokenInfo,amount=units(input.amount,inputToken.decimals,'Trade input');if(amount===0n)throw Error('Trade amount must be positive.');if(s.phase==='refund-curve'&&!sell)throw Error('The failed auction accepts token redemptions through its refund curve.');
    const zeroForOne=eq(inputToken.address,s.poolKey.currency0),params={key:s.poolKey,zeroForOne,amountIn:amount,minimumOut:units(input.minimumOut||'0',outputToken.decimals,'Minimum output'),sqrtPriceLimitX96:input.sqrtPriceLimitX96?uint(input.sqrtPriceLimitX96,'Price limit'):zeroForOne?4295128740n:1461446703485210103287273052203988822378723970341n,recipient:nz(input.recipient||c.payer,'Trade recipient'),deadline:BigInt(c.block.timestamp+900)};
    let quote;if(input.quoter){quote=await this.dopplerQuote({...input,provider:c.provider});if(quote.blockHash!==s.blockHash)throw Error('The quote block changed. Prepare a fresh quote.');const slippage=uint(input.slippageBps??50,'Slippage basis points',5000n);if(!params.minimumOut)params.minimumOut=BigInt(quote.received)*(10000n-slippage)/10000n;}
    if(params.minimumOut===0n)throw Error('Configure the quote lens or set a positive minimum output before preparing a funded swap.');return this.plan(c,router,'swap',[params],{kind:'official-doppler-'+(s.phase==='refund-curve'?'refund':sell?'sell':'buy'),purpose:s.phase==='refund-curve'?'Redeem tokens against the official Doppler refund curve':sell?'Sell tokens into the Doppler auction':'Buy tokens from the Doppler auction',spend:inputToken.address===ZeroAddress?[]:[{tokenAddress:inputToken.address,amount}],value:inputToken.address===ZeroAddress?amount:0n,summary:{amount:input.amount,input:inputToken.symbol,minimumOut:formatUnits(params.minimumOut,outputToken.decimals),quotedOutput:quote?.formatted.received,quoteIncludes:'Actual pool and hook swap fees; migration fees apply separately',output:outputToken.symbol,recipient:params.recipient,execution:'Exact input cap; partial fills refund unused native input or leave unused ERC20 in your account'},meta:{protocol:'official-doppler',airlock:s.airlock,token:s.asset,hook:s.hook,quote}});
  }
  async dopplerAction(input){const c=await this.context(),s=await this.readDoppler({...input,provider:c.provider});let target,method,args,purpose;
    if(input.action==='migrate'){if(s.phase!=='ready-to-migrate')throw Error('The auction is not ready to migrate.');target=await verifyProtocol(c.provider,s.airlock,'Airlock',c.block.number);method='migrate';args=[s.asset];purpose='Migrate the completed Doppler auction into its committed Uniswap v2 pool';}
    else if(input.action==='exitLockedLP'){if(!s.lpLock.minUnlockDate||c.block.timestamp<s.lpLock.minUnlockDate)throw Error('The protocol LP lock has not matured.');const pair=new Contract(s.migrationPool,['function balanceOf(address) view returns(uint256)'],c.provider);if(!await pair.balanceOf(s.locker,c.at))throw Error('The protocol LP position has already been released.');target=await verifyProtocol(c.provider,s.locker,'UniswapV2Locker',c.block.number);method='claimFeesAndExit';args=[s.migrationPool];purpose='Release matured locked LP principal and settle protocol fees';}
    else if(['collectProtocolFees','collectIntegratorFees'].includes(input.action)){target=await verifyProtocol(c.provider,s.airlock,'Airlock',c.block.number);method=input.action;const feeToken=addr(input.feeToken||ZeroAddress),recipient=nz(input.recipient||c.payer,'Fee recipient');let available;if(method==='collectProtocolFees'){if(!eq(await target.owner(c.at),c.payer))throw Error('Only the Airlock owner can collect protocol fees.');available=await target.getProtocolFees(feeToken,c.at);}else available=await target.getIntegratorFees(c.payer,feeToken,c.at);if(!available)throw Error('No fees are accrued for this account and token.');args=[recipient,feeToken,available];purpose='Collect accrued '+(method==='collectProtocolFees'?'protocol':'integrator')+' fees to the selected recipient';}
    else if(input.action==='releaseVesting'){target=new Contract(s.asset,PROTOCOL_ARTIFACTS.DopplerERC20V1.abi,c.provider);const beneficiary=nz(input.beneficiary||c.payer,'Vesting beneficiary'),id=uint(input.scheduleId,'Schedule ID'),available=await target['computeAvailableVestedAmount(address,uint256)'](beneficiary,id,c.at);if(!available)throw Error('No allocation has vested for this recipient and schedule.');method='releaseFor(address,uint256,uint256)';args=[beneficiary,id,available];purpose='Release vested Doppler tokens to their committed beneficiary';}
    else throw Error('Unsupported Doppler lifecycle action.');return this.plan(c,target,method,args,{kind:'official-doppler-'+input.action,purpose,summary:{token:s.tokenInfo.symbol,auction:s.hook,recipient:s.recipient,migrationPool:s.migrationPool},meta:{protocol:'official-doppler',airlock:s.airlock,token:s.asset}});
  }
  async approveModules({airlock,modules}){const c=await this.context(),a=await verifyProtocol(c.provider,airlock,'Airlock',c.block.number);if(!eq(await a.owner(c.at),c.payer))throw Error('Only the selected Airlock owner can enable modules.');const names={1:'DopplerERC20V1Factory',2:'LaunchpadGovernanceFactory',3:'UniswapV4Initializer',4:'UniswapV2MigratorSplit'};for(const m of modules)await verifyProtocol(c.provider,m.address,names[m.state],c.block.number);return this.plan(c,a,'setModuleState',[modules.map(x=>addr(x.address)),modules.map(x=>Number(x.state))],{kind:'official-doppler-setup',purpose:'Enable verified protocol modules in this Airlock',summary:{modules}});}
  async enableProceedsSplit({airlock,migrator}){const c=await this.context(),a=await verifyProtocol(c.provider,airlock,'Airlock',c.block.number),m=await verifyProtocol(c.provider,migrator,'UniswapV2MigratorSplit',c.block.number),top=await verifyProtocol(c.provider,await m.TOP_UP_DISTRIBUTOR(c.at),'TopUpDistributor',c.block.number);if(!eq(await a.owner(c.at),c.payer)||!eq(await m.airlock(c.at),a.target)||!eq(await top.AIRLOCK(c.at),a.target))throw Error('Only the matching Airlock owner can enable this proceeds distributor.');return this.plan(c,top,'setPullUp',[m.target,true],{kind:'official-doppler-topup',purpose:'Enable the official proceeds splitter for this verified migrator',summary:{airlock:a.target,migrator:m.target},meta:{airlock:a.target,migrator:m.target}});}
}

/** Reconcile a mined operation against exact protocol events and deployed bytecode before confirmation. */
export async function verifyProtocolReceipt(provider,record,receipt){
  if(!record?.kind?.startsWith('official-')||!record.final)return null;
  if(Number(receipt.status)!==1)throw Error('The official protocol transaction reverted.');
  const block=await provider.getBlock(receipt.blockNumber);if(block?.hash!==receipt.blockHash)throw Error('The official protocol receipt is not in the canonical block.');
  const at={blockTag:receipt.blockNumber},r=record.innerRequest||record.request,meta=record.meta||{},effects=[];
  const logs=(name,address)=>{const i=new Interface(PROTOCOL_ARTIFACTS[name].abi);return receipt.logs.filter(l=>eq(l.address,address)).map(l=>{try{return i.parseLog(l);}catch{return null;}}).filter(Boolean);};
  const requireEvent=(events,name,predicate=()=>true)=>{const e=events.find(e=>e.name===name&&predicate(e.args));if(!e)throw Error(`The receipt has no matching ${name} event.`);return e;};
  if(record.kind==='official-setup'){
    const name=meta.contractName,address=meta.predictedAddress,c=await verifyProtocol(provider,address,name,receipt.blockNumber);let initData;
    if(r.to){const helper=await verifyProtocol(provider,r.to,'OfficialCreate2',receipt.blockNumber),decoded=helper.interface.decodeFunctionData('deploy',r.data);initData=decoded[1];const predicted=getCreate2Address(helper.target,keccak256(coder.encode(['address','bytes32'],[record.account,decoded[0]])),keccak256(initData));if(!eq(predicted,address))throw Error('The CREATE2 deployment address differs from the signed payload.');requireEvent(logs('OfficialCreate2',helper.target),'Deployed',e=>eq(e.caller,record.account)&&eq(e.deployed,address)&&e.salt===decoded[0]);}
    else{if(!receipt.contractAddress||!eq(receipt.contractAddress,address))throw Error('Created contract differs from the reviewed address.');initData=r.data;}
    const creation=PROTOCOL_DEPLOYMENTS[name];if(!initData.toLowerCase().startsWith(creation.toLowerCase()))throw Error('Deployment initialization differs from the pinned contract.');
    const constructor=new Interface(PROTOCOL_ARTIFACTS[name].abi).deploy,types=constructor.inputs,args=coder.decode(types,'0x'+initData.slice(creation.length));
    const bindings={OfficialCCALauncher:[['factory',0]],ContinuousClearingAuctionFactory:[['protocolFeeController',0]],LBPStrategy:[['positionManager',0],['poolManager',1],['initializerFactory',2]],OfficialV4SwapRouter:[['manager',0]],OfficialV4QuoteLens:[['manager',0]],DopplerDeployer:[['poolManager',0]],UniswapV4Initializer:[['airlock',0],['poolManager',1],['deployer',2]],DopplerERC20V1Factory:[['airlock',0]],UniswapV2MigratorSplit:[['airlock',0],['factory',1],['TOP_UP_DISTRIBUTOR',2],['weth',3]],TopUpDistributor:[['AIRLOCK',0]],PositionManager:[['poolManager',0],['permit2',1]]};
    for(const [getter,index]of bindings[name]||[])if(!eq(await c[getter](at),args[index]))throw Error(`${name} constructor binding ${getter} differs from the reviewed value.`);
    return {verified:true,protocol:'official-setup',contractName:name,address,effects:[{event:'Deployment',contract:name,address}]};
  }
  if(record.kind==='official-cca-create'){
    const a=await verifyProtocol(provider,meta.auction,'ContinuousClearingAuction',receipt.blockNumber),f=await verifyProtocol(provider,meta.factory,'ContinuousClearingAuctionFactory',receipt.blockNumber),e=requireEvent(logs('ContinuousClearingAuctionFactory',f.target),'AuctionCreated',e=>eq(e.auction,meta.auction)&&eq(e.token,meta.token));
    if(!eq(await a.token(at),meta.token)||BigInt(e.args.amount)!==await a.totalSupply(at))throw Error('The created CCA supply or token differs from the factory event.');
    const receivedSupply=await a.totalSupply(at);requireEvent(logs('ContinuousClearingAuction',a.target),'TokensReceived',e=>e.totalSupply===receivedSupply&&receivedSupply>0n);
    const params=coder.decode([CCA_PARAMETERS],e.args.configData)[0];if(keccak256(coder.encode([CCA_PARAMETERS],[params]))!==meta.termsHash)throw Error('Mined CCA parameters differ from the reviewed terms.');
    if(meta.strategy){const s=await verifyProtocol(provider,meta.strategy,'LBPStrategy',receipt.blockNumber);requireEvent(logs('LBPStrategy',s.target),'InitializerCreated',e=>eq(e.initializer,a.target));if(!eq(await s.initializerFactory(at),f.target))throw Error('The migration strategy is bound to another factory.');}
    effects.push({event:'AuctionCreated',auction:a.target,asset:meta.token,amount:str(await a.totalSupply(at))});return {verified:true,protocol:'official-cca',auction:a.target,effects};
  }
  if(record.kind.startsWith('official-cca-')){
    const a=await verifyProtocol(provider,meta.auction,'ContinuousClearingAuction',receipt.blockNumber),events=logs('ContinuousClearingAuction',a.target),i=a.interface;
    if(record.kind==='official-cca-migrate'){const s=await verifyProtocol(provider,meta.strategy,'LBPStrategy',receipt.blockNumber),events=logs('LBPStrategy',s.target),success=events.find(e=>e.name==='Migrated'&&eq(e.args.initializer,a.target)),failed=events.find(e=>e.name==='MigrationFailed'&&eq(e.args.initializer,a.target));if(!success&&!failed)throw Error('The receipt has no matching migration outcome.');if(failed){const recovery=requireEvent(events,'FundsRecovered',e=>eq(e.initializer,a.target));effects.push({event:'MigrationRecovered',auction:a.target,recipient:recovery.args.recipient,amount:str(recovery.args.amount),reason:failed.args.reason});}else{const manager=await verifyProtocol(provider,await s.poolManager(at),'PoolManager',receipt.blockNumber),poolId=success.args.key.hash,managerEvents=logs('PoolManager',manager.target),initialized=requireEvent(managerEvents,'Initialize',e=>e.id===poolId&&e.sqrtPriceX96===success.args.initialSqrtPriceX96);requireEvent(managerEvents,'ModifyLiquidity',e=>e.id===poolId&&e.liquidityDelta>0n);const k=initialized.args;effects.push({event:'Migrated',auction:a.target,manager:manager.target,poolKey:{currency0:k.currency0,currency1:k.currency1,fee:str(k.fee),tickSpacing:str(k.tickSpacing),hooks:k.hooks},poolId,sqrtPriceX96:str(success.args.initialSqrtPriceX96)});}return {verified:true,protocol:'official-cca',outcome:failed?'recovered':'migrated',effects};}
    const tx=i.parseTransaction({data:r.data,value:r.value||0}),map={bid:'BidSubmitted',exit:'BidExited',claim:'TokensClaimed',checkpoint:'CheckpointUpdated',sweepTokens:'TokensSwept',sweepCurrency:'CurrencySwept'},action=record.kind.slice('official-cca-'.length),eventName=map[action];if(!eventName)throw Error('Unsupported official CCA receipt kind.');
    if(action==='bid'){const e=requireEvent(events,eventName,e=>e.priceQ96===tx.args[0]&&e.amount===tx.args[1]&&eq(e.owner,tx.args[2]));effects.push({event:eventName,id:str(e.args.id),owner:e.args.owner,amount:str(e.args.amount),maxPriceQ96:str(e.args.priceQ96)});}
    else if(action==='exit'||action==='claim'){const e=requireEvent(events,eventName,e=>e.bidId===tx.args[0]);effects.push({event:eventName,id:str(e.args.bidId),owner:e.args.owner,tokens:str(e.args.tokensFilled),refunded:str(e.args.currencyRefunded||0)});}
    else{const e=requireEvent(events,eventName);effects.push({event:eventName,values:json(e.args.toObject?.()||Array.from(e.args))});}return {verified:true,protocol:'official-cca',auction:a.target,effects};
  }
  if(record.kind==='official-doppler-setup'){const a=await verifyProtocol(provider,r.to,'Airlock',receipt.blockNumber),tx=a.interface.parseTransaction({data:r.data}),events=logs('Airlock',a.target);for(let k=0;k<tx.args[0].length;k++)requireEvent(events,'SetModuleState',e=>eq(e.module,tx.args[0][k])&&BigInt(e.state)===BigInt(tx.args[1][k]));return {verified:true,protocol:'official-doppler',effects:[{event:'ModulesEnabled'}]};}
  if(record.kind==='official-doppler-topup'){const top=await verifyProtocol(provider,r.to,'TopUpDistributor',receipt.blockNumber),tx=top.interface.decodeFunctionData('setPullUp',r.data);if(!eq(await top.AIRLOCK(at),meta.airlock)||!eq(tx[0],meta.migrator)||await top.canPullUp(tx[0],at)!==tx[1])throw Error('The proceeds distributor did not enable the selected migrator.');return {verified:true,protocol:'official-doppler',effects:[{event:'ProceedsSplitEnabled',migrator:tx[0],enabled:tx[1]}]};}
  const a=await verifyProtocol(provider,meta.airlock,'Airlock',receipt.blockNumber),data=await a.getAssetData(meta.token,at);
  if(record.kind==='official-doppler-create'){
    const tx=a.interface.parseTransaction({data:r.data}),params=tx.args[0];if(keccak256(r.data)!==meta.termsHash)throw Error('Doppler creation payload differs from the reviewed terms.');
    requireEvent(logs('Airlock',a.target),'Create',e=>eq(e.asset,meta.token)&&eq(e.poolOrHook,meta.hook)&&eq(e.initializer,params.poolInitializer)&&eq(e.numeraire,params.numeraire));
    const factory=await verifyProtocol(provider,params.tokenFactory,'DopplerERC20V1Factory',receipt.blockNumber),implementation=await factory.IMPLEMENTATION(at);await verifyProtocol(provider,implementation,'DopplerERC20V1',receipt.blockNumber);
    const predicted=dopplerCloneAddress(factory.target,implementation,params.salt),expectedRuntime=concat(['0x3d3d3d3d363d3d37363d73',implementation,'0x5af43d3d93803e602a57fd5bf3']);if(!eq(predicted,meta.token)||(await provider.getCode(meta.token,receipt.blockNumber)).toLowerCase()!==expectedRuntime.toLowerCase())throw Error('The Doppler token is not the predicted pinned implementation clone.');
    const hook=await verifyProtocol(provider,meta.hook,'Doppler',receipt.blockNumber);if(!eq(await hook.initializer(at),params.poolInitializer)||data.numTokensToSell!==params.numTokensToSell||data.totalSupply!==params.initialSupply)throw Error('Doppler creation outputs differ from the signed allocation.');effects.push({event:'Created',asset:meta.token,hook:meta.hook,totalSupply:str(params.initialSupply),offered:str(params.numTokensToSell)});
  }else if(['official-doppler-buy','official-doppler-sell','official-doppler-refund'].includes(record.kind)){
    const router=await verifyProtocol(provider,r.to,'OfficialV4SwapRouter',receipt.blockNumber),tx=router.interface.decodeFunctionData('swap',r.data)[0],e=requireEvent(logs('OfficialV4SwapRouter',router.target),'Swapped',e=>eq(e.payer,record.payer||record.account)&&eq(e.recipient,tx.recipient)&&e.spent<=tx.amountIn&&e.received>=tx.minimumOut);effects.push({event:'Swapped',payer:e.args.payer,recipient:e.args.recipient,input:e.args.input,output:e.args.output,spent:str(e.args.spent),received:str(e.args.received)});
  }else if(record.kind==='official-doppler-migrate'){requireEvent(logs('Airlock',a.target),'Migrate',e=>eq(e.asset,meta.token)&&eq(e.pool,data.migrationPool));const token=new Contract(meta.token,PROTOCOL_ARTIFACTS.DopplerERC20V1.abi,provider);if(await token.isPoolLocked(at)||!eq(await token.owner(at),data.timelock))throw Error('Doppler migration did not release the committed owner rights.');effects.push({event:'Migrated',asset:meta.token,pool:data.migrationPool,recipient:data.timelock});}
  else if(record.kind==='official-doppler-releaseVesting'){const token=new Contract(meta.token,PROTOCOL_ARTIFACTS.DopplerERC20V1.abi,provider),tx=token.interface.parseTransaction({data:r.data});const transfer=new Interface(ERC20.concat(['event Transfer(address indexed from,address indexed to,uint256 amount)']));if(!receipt.logs.some(l=>{try{const e=transfer.parseLog(l);return eq(l.address,meta.token)&&e.name==='Transfer'&&eq(e.args.to,tx.args[0])&&e.args.amount===tx.args[2];}catch{return false;}}))throw Error('The vesting release transfer is missing.');effects.push({event:'VestingReleased',asset:meta.token,recipient:tx.args[0],amount:str(tx.args[2])});}
  else if(record.kind==='official-doppler-exitLockedLP'){const locker=await verifyProtocol(provider,r.to,'UniswapV2Locker',receipt.blockNumber),tx=locker.interface.decodeFunctionData('claimFeesAndExit',r.data),m=await verifyProtocol(provider,data.liquidityMigrator,'UniswapV2MigratorSplit',receipt.blockNumber);if(!eq(tx[0],data.migrationPool)||!eq(await m.locker(at),locker.target))throw Error('The LP exit belongs to a different pool or locker.');const pair=new Contract(data.migrationPool,['function balanceOf(address) view returns(uint256)','event Burn(address indexed sender,uint256 amount0,uint256 amount1,address indexed to)','event Transfer(address indexed from,address indexed to,uint256 value)'],provider),events=receipt.logs.filter(l=>eq(l.address,pair.target)).map(l=>{try{return pair.interface.parseLog(l);}catch{return null;}}).filter(Boolean);const burn=requireEvent(events,'Burn',e=>eq(e.sender,locker.target)&&eq(e.to,locker.target)&&e.amount0>0n&&e.amount1>0n);requireEvent(events,'Transfer',e=>eq(e.from,locker.target)&&eq(e.to,pair.target)&&e.value>0n);if(await pair.balanceOf(locker.target,at)!==0n)throw Error('The locker still holds LP after its exit.');effects.push({event:'LockedLPExited',asset:meta.token,pool:data.migrationPool,recipient:data.timelock,amount0:str(burn.args.amount0),amount1:str(burn.args.amount1)});}
  else if(['official-doppler-collectProtocolFees','official-doppler-collectIntegratorFees'].includes(record.kind)){const tx=a.interface.parseTransaction({data:r.data}),e=requireEvent(logs('Airlock',a.target),'Collect',e=>eq(e.to,tx.args[0])&&eq(e.token,tx.args[1])&&e.amount===tx.args[2]);effects.push({event:'FeesCollected',recipient:e.args.to,asset:e.args.token,amount:str(e.args.amount)});}
  else throw Error('Unsupported official protocol receipt.');return {verified:true,protocol:'official-doppler',asset:meta.token,effects};
}
