import {Contract,getAddress,parseUnits,formatUnits,ZeroAddress} from '../vendor/ethers.min.js';
import {CommunitySaleClient,verifySaleContract} from './sale-client.mjs';

const TOKEN_ABI=['function decimals() view returns(uint8)','function symbol() view returns(string)','function balanceOf(address) view returns(uint256)'];
const MAX112=(1n<<112n)-1n,DAY=86400;
const payer=chain=>getAddress(chain.payer||chain.address);
const same=(a,b)=>getAddress(a)===getAddress(b);
const integer=(v,label,min=0,max=Number.MAX_SAFE_INTEGER)=>{if(!/^\d+$/.test(String(v)))throw Error(`${label} must be a whole number.`);const n=Number(v);if(!Number.isSafeInteger(n)||n<min||n>max)throw Error(`${label} must be ${min}–${max}.`);return n;};
const lockId=v=>{if(!/^\d+$/.test(String(v))||BigInt(v)<=0n||BigInt(v)>=(1n<<256n))throw Error('Choose a valid lock ID.');return BigInt(v);};

/** Optional fixed-beneficiary custody, through the same wallet/NFT review path. */
export class VaultStrategyClient{
 constructor(chain){this.chain=chain;}
 async context(){const chain=this.chain,generation=chain.generation;await chain.assertContext(generation);const provider=chain.provider,account=payer(chain),block=await provider.getBlock('latest');if(!block?.hash)throw Error('Current chain state is unavailable.');return {provider,account,generation,block,at:{blockTag:block.number},chainId:Number(chain.chainId)};}
 async assert(c){await this.chain.assertContext(c.generation);if(this.chain.provider!==c.provider||!same(payer(this.chain),c.account))throw Error('Funding account changed during vault preparation.');if((await c.provider.getBlock(c.block.number))?.hash!==c.block.hash)throw Error('The reviewed vault block changed. Refresh.');}
 async scope(address,c){const vault=await verifySaleContract(c.provider,address,'TimeVault',c.block.number),ledger=await verifySaleContract(c.provider,await vault.ledger(c.at),'WorldLedger',c.block.number),[sealed,installed,collection]=await Promise.all([ledger.isSealed(c.at),ledger.vault(c.at),ledger.collection(c.at)]);if(!sealed||!same(installed,vault.target))throw Error('Choose the vault installed in a sealed Genesis ledger.');if(await c.provider.getCode(collection,c.block.number)==='0x')throw Error('The ledger collection is not deployed.');return {...c,vault,ledger,collection};}
 async asset(c,address){address=getAddress(address);if(address===ZeroAddress)return {address,decimals:18,symbol:'ETH',balance:await c.provider.getBalance(c.account,c.block.number)};if(await c.provider.getCode(address,c.block.number)==='0x')throw Error('Choose a deployed token or liquidity-share contract.');const token=new Contract(address,TOKEN_ABI,c.provider),[decimals,symbol,balance]=await Promise.all([token.decimals(c.at),token.symbol(c.at),token.balanceOf(c.account,c.at)]);if(Number(decimals)>36)throw Error('Unsupported token decimals.');return {address,decimals:Number(decimals),symbol,balance};}
 async verify(vault){const c=await this.scope(vault,await this.context());await this.assert(c);return {vault:c.vault.target,ledger:c.ledger.target,collection:c.collection,chainId:c.chainId,blockNumber:c.block.number,blockHash:c.block.hash};}
 async setup({ledger}){return new CommunitySaleClient(this.chain).setup({kind:'vault',ledger});}
 async prepare(c,kind,purpose,data,{spend=[],value=0n,summary={},deadline}={}){await this.assert(c);return this.chain.prepareExternal({kind,purpose,payer:c.account,chainId:c.chainId,deadline:deadline??Math.floor(Date.now()/1000)+900,request:{to:c.vault.target,data,value},spend,summary:{purpose,...summary},meta:{vault:c.vault.target,ledger:c.ledger.target,collection:c.collection,stateBlock:c.block.number,stateBlockHash:c.block.hash}},{nftCompatible:true});}
 async deposit({vault,asset=ZeroAddress,amount,beneficiary,linear=false,days='180',cliffDays='30',start}){
  const c=await this.scope(vault,await this.context()),token=await this.asset(c,asset),raw=parseUnits(String(amount),token.decimals),recipient=getAddress(beneficiary||c.account);if(raw<=0n||raw>MAX112)throw Error('Lock amount must be positive and fit uint112.');if(raw>token.balance)throw Error('The funding account does not hold the selected lock amount.');if(recipient===ZeroAddress||same(recipient,c.vault.target))throw Error('Choose a nonzero beneficiary other than this vault.');if(typeof linear!=='boolean')throw Error('Choose cliff lock or linear vesting.');
  const duration=integer(days,'Duration days',1,3649)*DAY,offset=linear?integer(cliffDays,'Cliff days',0,3649)*DAY:duration;
  if(offset>duration)throw Error('The cliff cannot follow the vesting end.');
  // A future start preserves the reviewed end even if wallet confirmation takes minutes.
  const begins=start===undefined?c.block.timestamp+300:integer(start,'Start time',c.block.timestamp+60),cliff=begins+offset,end=begins+duration;
  if(end>c.block.timestamp+3650*DAY)throw Error('The schedule extends beyond the vault’s ten-year limit.');
  const data=c.vault.interface.encodeFunctionData('deposit',[token.address,raw,recipient,begins,cliff,end,linear,0]);
  return this.prepare(c,'vault-deposit',linear?'Vest the selected assets to a fixed beneficiary':'Lock the selected assets until the chosen date',data,{spend:token.address===ZeroAddress?[]:[{tokenAddress:token.address,amount:raw}],value:token.address===ZeroAddress?raw:0n,deadline:begins,summary:{asset:token.address,symbol:token.symbol,decimals:token.decimals,amount:formatUnits(raw,token.decimals),beneficiary:recipient,start:begins,cliff,end,linear,depositor:c.account,rights:'No administrator or early withdrawal. Anyone may release only to the fixed beneficiary. If this asset is an LP share, both redemption principal and its proportional LP fees stay in custody until shares are released.',identity:'0: no additional collection identity claim'}});
 }
 async lock(c,id){id=lockId(id);const [l,releasable]=await Promise.all([c.vault.lockInfo(id,c.at),c.vault.releasable(id,c.at)]);if(l[3]===0n)throw Error('This lock does not exist.');const token=await this.asset(c,l[2]);return {id:String(id),vault:c.vault.target,chainId:c.chainId,depositor:l[0],beneficiary:l[1],asset:l[2],amount:String(l[3]),released:String(l[4]),start:Number(l[5]),cliff:Number(l[6]),end:Number(l[7]),linear:l[8],identity:String(l[9]),releasable:String(releasable),remaining:String(l[3]-l[4]),symbol:token.symbol,decimals:token.decimals,formatted:{amount:formatUnits(l[3],token.decimals),released:formatUnits(l[4],token.decimals),releasable:formatUnits(releasable,token.decimals),remaining:formatUnits(l[3]-l[4],token.decimals)},blockNumber:c.block.number};}
 async read({vault,id}){const c=await this.scope(vault,await this.context()),result=await this.lock(c,id);await this.assert(c);return result;}
 async list({vault,beneficiary,offset=0,limit=20}){const c=await this.scope(vault,await this.context()),recipient=getAddress(beneficiary||c.account),count=await c.vault.lockCountOf(recipient,c.at),start=integer(offset,'Offset'),take=integer(limit,'Page size',1,50),end=Math.min(Number(count),start+take),locks=[];for(let i=start;i<end;i++)locks.push(await this.lock(c,await c.vault.lockIdOf(recipient,i,c.at)));await this.assert(c);return {vault:c.vault.target,beneficiary:recipient,total:String(count),locks,next:end<Number(count)?end:null};}
 async release({vault,id}){const c=await this.scope(vault,await this.context()),lock=await this.lock(c,id);if(BigInt(lock.releasable)<=0n)throw Error('No assets are releasable at this block.');return this.prepare(c,'vault-release','Release vested assets to their fixed beneficiary',c.vault.interface.encodeFunctionData('release',[lockId(id)]),{summary:{lockId:lock.id,asset:lock.asset,symbol:lock.symbol,amount:lock.formatted.releasable,recipient:lock.beneficiary,rights:'The caller cannot redirect this payment.'}});}
 async extend({vault,id,additionalDays}){const c=await this.scope(vault,await this.context()),lock=await this.lock(c,id);if(!same(lock.beneficiary,c.account)||lock.linear||c.block.timestamp>=lock.end)throw Error('Only the current fixed beneficiary can extend an unexpired cliff lock.');const end=lock.end+integer(additionalDays,'Additional days',1,3649)*DAY;if(end>c.block.timestamp+3650*DAY)throw Error('The extended schedule exceeds the vault’s ten-year limit.');return this.prepare(c,'vault-extend','Extend this cliff lock',c.vault.interface.encodeFunctionData('extend',[lockId(id),end]),{deadline:lock.end,summary:{lockId:lock.id,previousEnd:lock.end,newEnd:end,beneficiary:lock.beneficiary,rights:'Extension is irreversible and never changes the beneficiary.'}});}
}
