import assert from 'node:assert/strict';
import test from 'node:test';
import {EventEmitter} from 'node:events';
import {keccak256,bytesOf,hexOf,address,quantity,abiEncode,callData,words,TestnetClient,TEST_CHAINS,INTENT_TYPES,encodeVerified} from '../web/evm.mjs';
const owner='0x'+'11'.repeat(20),collection='0x'+'22'.repeat(20),account='0x'+'33'.repeat(20),hash='0x'+'44'.repeat(32),root='0x'+'55'.repeat(32);
class Wallet extends EventEmitter{
 constructor(){super();this.chain='0xaa36a7';this.accounts=[owner];this.calls=[];this.status='0x1';this.receiptHash=hash;this.blockHash=hash;this.failCall=false;this.duringCall=null;this.nonce=2;this.sovereign=false;}
 async request(r){this.calls.push(r);switch(r.method){case 'eth_chainId':return this.chain;case 'eth_accounts':case 'eth_requestAccounts':return this.accounts;case 'eth_getCode':return '0x6000';case 'eth_blockNumber':return '0x10';case 'eth_getBlockByNumber':return {hash:this.blockHash,number:'0x10',timestamp:'0x6a995000'};case 'eth_gasPrice':return '0x3b9aca00';case 'eth_estimateGas':return '0x186a0';case 'eth_sendTransaction':if(this.sendReject)throw Error('User rejected request');return hash;case 'eth_getTransactionReceipt':return this.noReceipt?null:{transactionHash:hash,blockHash:this.receiptHash,blockNumber:'0x10',status:this.status,logs:[]};case 'eth_call':{
 if(this.duringCall){const f=this.duringCall;this.duringCall=null;f();}
 if(this.failCall)throw Error('execution reverted');const d=r.params[0].data;
 if(d.startsWith(keccak256('renderSnapshot(uint256)').slice(0,10)))return abiEncode(['uint256',...Array(7).fill('bytes32'),'uint64','uint64','uint32','uint32','uint256','uint256','bool','address','address'],[1,...Array(7).fill(root),1700000000,1700000001,0,2,0,this.nonce,this.sovereign,account,owner]);
 if(d.startsWith(keccak256('deriveEvolutionStateRoot(uint256,bytes32,bytes32,bytes32)').slice(0,10)))return root;
 if(d.startsWith(keccak256('intentStatement((address,uint256,bytes32,uint256,uint48,uint48,bytes32,bytes32,bytes32,bytes32,bytes32,uint32))').slice(0,10)))return hash;
 return '0x';}default:throw Error('Unexpected method '+r.method);}}
}
async function connected(w=new Wallet()){const c=new TestnetClient(w);await c.connect(collection);await c.snapshot(1);return [c,w];}
test('Ethereum Keccak matches known empty, abc, and function selector vectors',()=>{assert.equal(keccak256(''),'0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470');assert.equal(keccak256('abc'),'0x4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45');assert.equal(keccak256('transfer(address,uint256)').slice(0,10),'0xa9059cbb');assert.equal(keccak256('balanceOf(address)').slice(0,10),'0x70a08231');assert.equal(keccak256('approve(address,uint256)').slice(0,10),'0x095ea7b3');});
test('hex, address and integer codecs reject malformed or truncated values',()=>{for(const x of ['0x0','hello','0xzz'])assert.throws(()=>bytesOf(x));assert.equal(hexOf(bytesOf('0x0123fe')),'0x0123fe');assert.throws(()=>address('0x'+'00'.repeat(20)));assert.throws(()=>quantity(-1));assert.throws(()=>abiEncode(['uint8'],[256]));assert.throws(()=>abiEncode(['bytes32'],['0x01']));assert.throws(()=>words('0x00',1));});
test('ABI known transfer encoding matches independent expected words',()=>{const data=callData('transfer(address,uint256)',['address','uint256'],[owner,1]);assert.equal(data,'0xa9059cbb'+'0'.repeat(24)+'11'.repeat(20)+'0'.repeat(63)+'1');});
test('dynamic ABI offsets account for multi-word static tuples',()=>{const v=abiEncode([['uint256','uint256'],'bytes','string'],[[3,4],'0x112233','hello']);const h=v.slice(2);assert.equal(BigInt('0x'+h.slice(128,192)),128n);assert.equal(BigInt('0x'+h.slice(192,256)),192n);assert.equal(BigInt('0x'+h.slice(256,320)),3n);assert(h.slice(320,384).startsWith('112233'));assert.equal(BigInt('0x'+h.slice(384,448)),5n);assert(h.slice(448).startsWith('68656c6c6f'));});
test('UTF-8 ABI string length counts bytes rather than UTF-16 units',()=>{const b=abiEncode(['string'],['🜁']);assert.equal(BigInt('0x'+b.slice(66,130)),4n);});
test('wallet construction has no side effects or account requests',()=>{const w=new Wallet(),c=new TestnetClient(w);assert.equal(w.calls.length,0);c.close();assert.equal(w.listenerCount('chainChanged'),0);});
test('mainnet is rejected before accounts exposure',async()=>{const w=new Wallet();w.chain='0x1';await assert.rejects(()=>new TestnetClient(w).connect(collection),/blocked/);assert(!w.calls.some(c=>c.method==='eth_requestAccounts'));assert.deepEqual([...TEST_CHAINS.keys()],[31337,11155111,84532]);});
test('snapshot reads one block and decodes exactly the requested token',async()=>{const [c,w]=await connected();assert.equal(c.state.nonce,2);assert.equal(c.state.account,account);assert.equal(c.state.blockNumber,'16');assert.equal(c.state.blockHash,hash);const read=w.calls.find(r=>r.method==='eth_call');assert.equal(read.params[1],'0x10');await assert.rejects(()=>c.snapshot(2),/mismatch/);});
test('preparing an action simulates and estimates but never sends',async()=>{const [c,w]=await connected();const p=await c.evolution(root);assert.equal(p.label,'EVOLVE');assert.equal(p.tx.to,account);assert.equal(p.tx.value,'0x0');assert.equal(p.tx.chainId,'0xaa36a7');assert.equal(p.estimatedGas,'100000');assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));assert.equal(p.tx.data.slice(0,10),keccak256('evolveBound(uint256,bytes32,bytes32,bytes32)').slice(0,10));});
test('RPC simulation failure prevents signing',async()=>{const [c,w]=await connected();w.failCall=true;await assert.rejects(()=>c.prepare('TEST',account,'0x12345678'),/reverted/);assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));});
test('successful included receipt is checked against its canonical block',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');const events=[];const r=await c.send(p,(...x)=>events.push(x));assert.equal(r.status,'0x1');assert.deepEqual(events.map(e=>e[0]),['SUBMITTED','INCLUDED']);assert.equal(c.pending,false);assert.equal(w.calls.filter(r=>r.method==='eth_sendTransaction').length,1);});
test('reverted receipt never produces an INCLUDED success event',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.status='0x0';const events=[];await assert.rejects(()=>c.send(p,s=>events.push(s)),/reverted/);assert.deepEqual(events,['SUBMITTED']);assert.equal(c.pending,false);});
test('reorganized receipt block is rejected',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.receiptHash=root;await assert.rejects(()=>c.send(p),/block changed/);});
test('wallet rejection releases the pending guard without claiming execution',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.sendReject=true;await assert.rejects(()=>c.send(p),/rejected/);assert.equal(c.pending,false);});
test('a stale network or account review cannot be signed',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.chain='0x1';w.emit('chainChanged','0x1');await assert.rejects(()=>c.send(p),/Reconnect/);assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));});
test('account switch during re-simulation is rejected before send',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.duringCall=()=>{w.accounts=[collection];w.emit('accountsChanged',[collection]);};await assert.rejects(()=>c.send(p),/Reconnect|changed/);assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));});
test('unannounced chain change is also rejected',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.chain='0x1';await assert.rejects(()=>c.send(p),/changed/);assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));});
test('pending timeout reports the hash, not a fabricated success',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.noReceipt=true;await assert.rejects(()=>c.send(p,()=>{},0),/Still pending.*0x/);assert.equal(c.pending,false);});
test('sovereign evolution builds an exact request without generating a proof',async()=>{const [c,w]=await connected();w.sovereign=true;const request=await c.evolution(root);assert.equal(request.proofRequired,true);assert.equal(request.statement,hash);assert.equal(request.intent.policyHash,root);assert.equal(request.intent.value,'0');assert.equal(request.intent.nonce,'2');assert.equal(request.intent.validUntil-request.intent.validAfter,1800);assert(!('proof' in request));assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));await assert.rejects(()=>c.verifiedEvolution(request,'0x'),/nonempty/);});
test('proof execution binds calldata and deployment rather than importing arbitrary transactions',async()=>{const [c,w]=await connected();w.sovereign=true;const req=await c.evolution(root);const tx=await c.verifiedEvolution(req,'0x0102');assert.equal(tx.tx.to,account);assert.throws(()=>encodeVerified(req.intent,'0xbeef','0x01'),/calldata/);await assert.rejects(()=>c.verifiedEvolution({...req,chainId:1},'0x01'),/different/);});
test('sovereign spawn and metadata paths refuse owner bypass',async()=>{const [c,w]=await connected();w.sovereign=true;await assert.rejects(()=>c.spawn(root),/proof/);await assert.rejects(()=>c.seal(root),/proof/);assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));});

test('provider disconnect invalidates prepared transactions and cleanup removes listeners',async()=>{const [c,w]=await connected();const p=await c.prepare('TEST',account,'0x12345678');w.emit('disconnect',{code:4900});await assert.rejects(()=>c.send(p),/Reconnect/);assert(!w.calls.some(r=>r.method==='eth_sendTransaction'));c.close();assert.equal(w.listenerCount('disconnect'),0);});
