[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 800
via_ir = false
fuzz = { runs = 512 }
invariant = { runs = 64, depth = 32, fail_on_revert = false }

[rpc_endpoints]
robinhood = "https://rpc.mainnet.chain.robinhood.com"
robinhood_testnet = "https://rpc.testnet.chain.robinhood.com"
