import test from 'node:test';
import assert from 'node:assert/strict';
import {AbiCoder, Contract, ZeroHash, keccak256, sha256, toUtf8Bytes} from 'ethers';
import {artifacts, fixture, hash, emptyArchive, send, rejected, event} from './contracts.fixture.mjs';

test('release publication pins immutable archives and exact versions, without publisher privilege over other namespaces',async t=>{
  const f=await fixture(t),{factory,releases,archive,publish,publisher,other,provider,deploy}=f;
  const first=await archive('<!doctype html><p>Version one</p>');
  const release=await publish(first.descriptor),record=await releases.release(release.id);
  assert.equal(record.publisher,publisher.address);
  assert.equal(record.moduleKey,release.key);
  assert.equal(await releases.manifest(release.id),'0x'+Buffer.from(release.manifest).toString('hex'));
  assert.equal(record.input.payload.archive,first.descriptor.archive);
  assert.equal(record.manifestHash,sha256(release.manifest));
  await rejected(()=>send(releases.connect(publisher),'publish',[release.input,release.manifest]));
  await rejected(()=>publish({...first.descriptor,codeHash:ZeroHash},{version:2n}));
  await rejected(()=>publish({...first.descriptor,storedBytes:first.bytes.length+1},{version:2n}));
  await rejected(()=>publish(first.descriptor,{version:2n,dependencies:[hash('missing release')]}));
  await rejected(()=>publish(first.descriptor,{version:2n,dependencies:[release.id,release.id]}));
  await rejected(()=>publish(first.descriptor,{version:2n,capabilities:[ZeroHash]}));
  await rejected(()=>send(factory,'createArchive',[first.chunks,hash('incorrect bytes')]));
  const unregistered=await deploy('OnchainApp',[first.chunks,first.descriptor.storedHash]);
  const unregisteredCodeHash=keccak256(await provider.getCode(unregistered.target));
  await rejected(()=>publish({...first.descriptor,archive:unregistered.target,codeHash:unregisteredCodeHash},{version:2n}));
  const otherNamespace=await publish(first.descriptor,{signer:other});
  assert.notEqual(otherNamespace.key,release.key,'publisher address is part of module identity');
  const next=await publish(first.descriptor,{version:2n,dependencies:[otherNamespace.id]});
  assert.equal((await releases.release(next.id)).input.payload.archive,first.descriptor.archive,'unchanged payload archive reused');
  assert.deepEqual(Array.from((await releases.releasesOf(release.key,0,1))[0]),[release.id]);
  assert.deepEqual(Array.from((await releases.releasesOf(release.key,1,1))[0]),[next.id]);
  assert.equal((await releases.releasesOf(release.key,2,1))[0].length,0);
  await rejected(()=>releases.releasesOf(release.key,0,65));
  await rejected(()=>releases.catalog(100,1));

  const second=await archive('<script>document.body.dataset.version="2"</script>');
  const all=new Uint8Array([...first.bytes,...second.bytes]);
  const directoryReceipt=await send(factory,'createDirectory',[[first.descriptor.archive,second.descriptor.archive],sha256(all)]);
  const location=event(directoryReceipt,factory,'ArchiveCreated').archive;
  const descriptor={archive:location,schema:2,storedHash:sha256(all),storedBytes:all.length,expandedHash:sha256(all),expandedBytes:all.length,codeHash:keccak256(await provider.getCode(location))};
  await factory.validateArchive(descriptor);
  const directory=new Contract(location,artifacts().OnchainAppDirectory.abi,provider);
  const recovered=[];for(let i=0;i<Number(await directory.chunkCount());i++)recovered.push(Buffer.from((await directory.readChunk(i)).slice(2),'hex'));
  assert.equal(sha256(Buffer.concat(recovered)),descriptor.storedHash);
  await publish(descriptor,{version:3n});
  await rejected(()=>send(factory,'createDirectory',[[unregistered.target],first.descriptor.storedHash]));
  assert.equal(await provider.getCode(first.chunks[0]),'0x00'+Buffer.from(first.bytes).toString('hex'),'stored chunk bytes remain unchanged');
});

test('native NFT owns module selection, atomic state migration, stale reviews and transfer revocation',async t=>{
  const f=await fixture(t,{mint:true}),{collection,account,account2,modules,state,archive,publish,call,context,owner,buyer,publisher,provider}=f;
  const snapshot=await collection.renderSnapshot(1),accountCode=await provider.getCode(account.target),collectionCode=await provider.getCode(collection.target);
  const balance=await provider.getBalance(account.target),grants=await account.instrumentGrantCount();
  const payload=await archive('<p>Counter</p>'),a=await publish(payload.descriptor),b=await publish(payload.descriptor,{moduleId:hash('another-counter')});
  const stateSchema2=hash('calculator/state/2'),a2=await publish(payload.descriptor,{version:2n,stateSchema:stateSchema2});
  const initial=await context();
  const uninstalledKey=hash('not-yet-published-state-namespace');
  await rejected(()=>call('stageState',[1,uninstalledKey,initial.root,initial.epoch,ZeroHash,toUtf8Bytes('invalid schema'),emptyArchive]));
  assert.equal(await modules.stateModuleCount(1),0n,'failed staging does not index a namespace');
  // Discard the transaction receipt: NFT context alone must rediscover never-activated state.
  await call('stageState',[1,uninstalledKey,initial.root,initial.epoch,hash('draft-state/1'),toUtf8Bytes('recover without receipt'),emptyArchive]);
  await call('stageState',[1,uninstalledKey,initial.root,initial.epoch,hash('draft-state/1'),toUtf8Bytes('second draft'),emptyArchive]);
  assert.equal(await modules.moduleCount(1),0n,'staging is not installation');
  assert.equal(await modules.historyCount(1),0n,'staging is not an active catalog mutation');
  assert.equal(await modules.rootOf(1),initial.root);
  assert.equal(await modules.stateModuleCount(1),1n,'duplicate drafts index their namespace once');
  assert.equal(await modules.stateModuleCount(2),0n,'state index is NFT scoped');
  const [draftKeys,draftNext]=await modules.stateModulesOf(1,0,1);
  assert.deepEqual(Array.from(draftKeys),[uninstalledKey]);assert.equal(draftNext,1n);
  const [draftIds]=await state.historyOf(1,draftKeys[0],0,64);
  assert.equal(draftIds.length,2);
  assert.equal(await state.dataOf(draftIds[0]),'0x'+Buffer.from('recover without receipt').toString('hex'));
  assert.equal((await modules.stateModulesOf(1,1,1))[0].length,0);
  await rejected(()=>modules.stateModulesOf(1,0,0));
  await rejected(()=>modules.stateModulesOf(1,0,65));
  await rejected(()=>modules.stateModulesOf(1,2,1));
  await rejected(()=>modules.activate(1,a.id,initial.root,initial.epoch,ZeroHash,ZeroHash));
  await rejected(()=>modules.connect(publisher).activate(1,a.id,initial.root,initial.epoch,ZeroHash,ZeroHash));
  await rejected(()=>call('activate',[1,a.id,initial.root,initial.epoch,ZeroHash,ZeroHash],owner,account2));
  await call('activate',[1,a.id,initial.root,initial.epoch,ZeroHash,ZeroHash]);
  assert.equal((await modules.installation(1,a.key)).enabled,true);
  await rejected(()=>call('activate',[1,b.id,initial.root,initial.epoch,ZeroHash,ZeroHash]));
  assert.equal(await modules.moduleCount(1),1n);

  let c=await context();
  const saved=await call('writeState',[1,a.key,c.root,c.epoch,toUtf8Bytes('{"count":1}'),emptyArchive]);
  const oldHead=event(saved,state,'StateStaged').stateId;
  assert.equal(await modules.stateModuleCount(1),2n,'active writes also index state namespaces');
  assert.deepEqual(Array.from((await modules.stateModulesOf(1,0,64))[0]),[uninstalledKey,a.key]);
  assert.equal((await modules.installation(1,a.key)).stateHead,oldHead);
  assert.equal(await state.dataOf(oldHead),'0x'+Buffer.from('{"count":1}').toString('hex'));
  c=await context();
  const priorRoot=c.root;
  const stagedReceipt=await call('stageState',[1,a.key,c.root,c.epoch,stateSchema2,toUtf8Bytes('{"count":1,"step":2}'),emptyArchive]);
  const staged=event(stagedReceipt,state,'StateStaged').stateId;
  assert.equal(await modules.rootOf(1),priorRoot,'staging does not change active code/state');
  assert.equal((await modules.installation(1,a.key)).releaseId,a.id);
  await rejected(()=>call('activate',[1,a2.id,c.root,c.epoch,oldHead,oldHead]));
  assert.equal(await modules.rootOf(1),priorRoot,'failed migration keeps old root');
  assert.equal((await modules.installation(1,a.key)).stateHead,oldHead);
  await call('activate',[1,a2.id,c.root,c.epoch,oldHead,staged]);
  const active=await modules.installation(1,a.key);
  assert.equal(active.releaseId,a2.id);assert.equal(active.stateHead,staged);
  assert.equal((await state.record(staged)).parent,oldHead);
  assert.equal(await state.dataOf(oldHead),'0x'+Buffer.from('{"count":1}').toString('hex'),'old bytes retained after migration');

  c=await context();
  await call('activate',[1,b.id,c.root,c.epoch,ZeroHash,ZeroHash]);
  c=await context();
  await rejected(()=>call('activate',[1,b.id,c.root,c.epoch,ZeroHash,staged]));
  await rejected(()=>state.append(1,a.key,stateSchema2,staged,c.epoch,toUtf8Bytes('publisher overwrite'),emptyArchive));
  await rejected(()=>modules.connect(publisher).writeState(1,a.key,c.root,c.epoch,toUtf8Bytes('publisher overwrite'),emptyArchive));
  await rejected(()=>call('writeState',[1,a.key,c.root,c.epoch,new Uint8Array(32769),emptyArchive]));
  await rejected(()=>call('writeState',[1,a.key,c.root,c.epoch,toUtf8Bytes('ambiguous'),payload.descriptor]));

  const pendingReceipt=await call('stageState',[1,a.key,c.root,c.epoch,stateSchema2,toUtf8Bytes('stale staged value'),emptyArchive]);
  const pending=event(pendingReceipt,state,'StateStaged').stateId;
  const saveReceipt=await call('writeState',[1,a.key,c.root,c.epoch,toUtf8Bytes('new current value'),emptyArchive]);
  const currentHead=event(saveReceipt,state,'StateStaged').stateId;
  c=await context();
  await rejected(()=>call('activate',[1,a2.id,c.root,c.epoch,currentHead,pending]));
  await rejected(()=>call('activate',[1,a2.id,c.root,c.epoch,currentHead,oldHead]));
  await rejected(()=>call('activate',[1,a2.id,c.root,c.epoch,currentHead,ZeroHash]));
  await call('disable',[1,a.key,c.root,c.epoch]);
  c=await context();
  await rejected(()=>call('writeState',[1,a.key,c.root,c.epoch,toUtf8Bytes('disabled write'),emptyArchive]));
  assert.equal((await modules.installation(1,a.key)).stateHead,currentHead,'disable preserves state');
  await call('activate',[1,a2.id,c.root,c.epoch,currentHead,currentHead]);

  c=await context();
  const beforeTransferRoot=c.root,oldEpoch=c.epoch;
  const awaiting=event(await call('stageState',[1,a.key,c.root,c.epoch,stateSchema2,toUtf8Bytes('old-owner pending'),emptyArchive]),state,'StateStaged').stateId;
  await send(collection,'transferFrom',[owner.address,buyer.address,1]);
  assert.equal(await modules.rootOf(1),beforeTransferRoot,'public installation history survives transfer');
  await rejected(()=>call('disable',[1,a.key,beforeTransferRoot,oldEpoch]));
  await rejected(()=>call('disable',[1,a.key,beforeTransferRoot,oldEpoch],buyer));
  c=await context();assert.equal(c.epoch,oldEpoch+1n);
  await rejected(()=>call('activate',[1,a2.id,c.root,c.epoch,currentHead,awaiting],buyer));
  await call('writeState',[1,a.key,c.root,c.epoch,toUtf8Bytes('new owner save'),emptyArchive],buyer);
  await send(collection.connect(buyer),'transferFrom',[buyer.address,owner.address,1]);
  c=await context();assert.equal(c.epoch,oldEpoch+2n);
  await rejected(()=>call('disable',[1,a.key,c.root,oldEpoch]));

  const large=await archive('archive-backed current state');
  const archivedReceipt=await call('writeState',[1,a.key,c.root,c.epoch,'0x',large.descriptor]);
  const archived=event(archivedReceipt,state,'StateStaged').stateId,archivedRecord=await state.record(archived);
  assert.equal(archivedRecord.archive.archive,large.descriptor.archive);
  assert.equal(archivedRecord.dataHash,large.descriptor.expandedHash);
  assert.equal(await state.dataOf(archived),'0x');
  const recordCount=await state.countOf(1,a.key);
  assert.equal(await modules.stateModuleCount(1),2n,'write, migration, disable and transfer do not duplicate state keys');
  assert.ok(recordCount>=7n);
  const page=await state.historyOf(1,a.key,0,2);assert.equal(page[0].length,2);assert.equal(page[1],2n);
  await rejected(()=>state.historyOf(1,a.key,0,65));
  await rejected(()=>modules.modulesOf(1,0,65));
  const keys=(await modules.modulesOf(1,0,64))[0];assert.deepEqual(Array.from(keys),[a.key,b.key]);
  const history=(await modules.historyOf(1,0,64))[0];
  assert.equal(history.at(-1).root,await modules.rootOf(1));
  for(let i=1;i<history.length;i++)assert.equal(history[i].previousRoot,history[i-1].root);
  assert.equal(await account.instrumentGrantCount(),grants,'installation and saves grant no spending permission');
  assert.equal(await provider.getBalance(account.target),balance,'module operations spend no account funds');
  assert.equal(await provider.getCode(account.target),accountCode);
  assert.equal(await provider.getCode(collection.target),collectionCode);
  const after=await collection.renderSnapshot(1);
  for(const key of ['seed','genome','stateRoot','memoryRoot','lineageRoot','constitutionHash','generation','evolutions','account'])assert.equal(after[key],snapshot[key],`original ${key} preserved`);
  assert.ok(after.actionNonce>snapshot.actionNonce,'normal existing-account audit records these calls');
});

test('release identity has an independently encoded ABI commitment',async t=>{
  const f=await fixture(t),payload=await f.archive('<p>ABI proof</p>'),a=await f.publish(payload.descriptor);
  const archiveType='tuple(address archive,uint8 schema,bytes32 storedHash,uint32 storedBytes,bytes32 expandedHash,uint32 expandedBytes,bytes32 codeHash)';
  const inputType=`tuple(bytes32 moduleId,uint64 version,${archiveType} payload,bytes32 runtime,bytes32 hostAPI,bytes32 stateSchema,bytes32[] capabilities,bytes32[] dependencies)`;
  const independentlyEncoded=AbiCoder.defaultAbiCoder().encode(['bytes32','address',inputType,'bytes32'],[hash('anima.extension-release/1'),f.publisher.address,a.input,sha256(a.manifest)]);
  assert.equal(a.id,keccak256(independentlyEncoded));
});
