import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const source=fs.readFileSync(new URL('../../web/memory/app.js',import.meta.url),'utf8');
// Actual controller functions in a VM with narrow UI/async stubs. These are NOT browser crypto tests.
function harness(){const state={actor:'you',selected:1,now:100};const n={header:{id:1,author:'you',identity:1,time:100},payload:{mode:'encrypted'},digest:'note'};const c=vm.createContext({structuredClone,Date,Map,MEM_ZERO:'0x0000',document:{hidden:false},ixReview:null,ixView:'journal',W:()=>({s:state}),ixEngine:{entry:()=>n,memoryHeader:()=>n.header},ix$:()=>({value:'memory passphrase',checked:true}),draw:()=>{},notice:()=>{},decryptMemory:async()=>({thesis:'hidden'}),memoryBody:x=>x,memorySeal:(h,p)=>({header:h,payload:p})});vm.runInContext(source,c);return {c,state,n,run:s=>vm.runInContext(s,c)};}
test('Locking private bodies clears volatile text, query, passphrase and private review',()=>{const{c,run}=harness();c.ixReview={memoryPrivate:true,html:'private thesis',note:{payload:{mode:'encrypted'}}};run("memSession('secret passphrase');memDraft={thesis:'private'};memQuery='sensitive search';memUnlocked.set('x',{thesis:'private'});memLock()");assert.equal(c.ixReview,null);assert.equal(run('memSessionPass'),'');assert.equal(run('memDraft'),null);assert.equal(run('memQuery'),'');assert.equal(run('memUnlocked.size'),0);});
test('Locking memory does not cancel an unrelated ordinary trade review',()=>{const{c,run}=harness();const review={title:'Ordinary trade'};c.ixReview=review;run('memLock()');assert.equal(c.ixReview,review);});
test('A decryption finishing after lock cannot reopen the private session',async()=>{const{c,run}=harness();let done;c.decryptMemory=()=>new Promise(r=>done=r);run('memOpen=1');const pending=run("memSubmit('mem-unlock-form')");run('memLock()');done({thesis:'hidden'});await assert.rejects(pending,/session changed/);assert.equal(run('memUnlocked.size'),0);assert.equal(run('memSessionPass'),'');});
test('A decryption finishing after persona change cannot expose its result',async()=>{const{c,state,run}=harness();let done;c.decryptMemory=()=>new Promise(r=>done=r);run('memOpen=1');const pending=run("memSubmit('mem-unlock-form')");state.actor='guest';done({thesis:'hidden'});await assert.rejects(pending,/session changed/);assert.equal(run('memUnlocked.size'),0);});
test('A private draft finishing after lock cannot restore its passphrase',async()=>{const{c,run}=harness();let done;c.encryptMemory=()=>new Promise(r=>done=r);run("memGetBody=()=>({thesis:'private'});memVal=id=>id==='privacy'?'encrypted':'a long secret passphrase'");const pending=run("memSealDraft('memory')");run('memLock()');done({mode:'encrypted'});await assert.rejects(pending,/context changed/);assert.equal(run('memSessionPass'),'');});
