import test from 'node:test';import assert from 'node:assert/strict';
import {PrivateVault,sealPrivateData,openPrivateData} from '../../web/privacy/vault.mjs';
const data={mnemonic:'test test test test test test test test test test test junk',settings:{rpc:'https://example.invalid/secret-token'},drafts:[{name:'Unannounced launch'}],note:'Private thought'};
const password='correct horse battery staple';
const storage=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),map};};
test('private backups authenticate contents, randomize ciphertext and conceal recovery, RPC credentials and drafts',async()=>{const a=await sealPrivateData(data,password),b=await sealPrivateData(data,password);assert.notEqual(a.envelope.iv,b.envelope.iv);assert.notEqual(a.envelope.ciphertext,b.envelope.ciphertext);const serialized=JSON.stringify(a.envelope);for(const secret of ['junk','secret-token','Unannounced','Private thought'])assert.ok(!serialized.includes(secret));assert.deepEqual((await openPrivateData(a.envelope,password)).data,data);await assert.rejects(openPrivateData(a.envelope,password+'x'),/incorrect/);const bad=structuredClone(a.envelope);bad.ciphertext=(bad.ciphertext[0]==='A'?'B':'A')+bad.ciphertext.slice(1);await assert.rejects(openPrivateData(bad,password),/incorrect|changed/);});
test('encrypted vault restores exact data, saves updated drafts and does not overwrite an existing wallet',async()=>{const s=storage(),v=new PrivateVault(s);await v.create(data,password);assert.ok(v.exists);v.data.note='Updated private thought';await v.save();const backup=v.exportBackup();v.lock();assert.equal(v.data,null);assert.equal(v.key,null);await v.unlock(password);assert.equal(v.data.note,'Updated private thought');await assert.rejects(v.importBackup(backup,password),/empty/);const restored=new PrivateVault(storage());await restored.importBackup(backup,password);assert.deepEqual(restored.data,v.data);});
test('locking during decryption cannot reopen the vault',async()=>{const v=new PrivateVault(storage());await v.create(data,password);v.lock();const pending=v.unlock(password);v.lock();await assert.rejects(pending,/locked/);assert.equal(v.data,null);assert.equal(v.key,null);});
test('hostile KDF work factors and malformed backups reject before expensive decryption',async()=>{await assert.rejects(openPrivateData({schema:'anima.encrypted-private-wallet/1',kdf:'PBKDF2-SHA256',iterations:2**32,cipher:'AES-256-GCM'},password),/Unsupported/);await assert.rejects(sealPrivateData(data,'short'),/16/);});
