/** Local EVM regression tests, executed during Confluence integration.
 * Uses a real local EVM when dependencies are installed. This is NOT a v4 PoolManager test.
 * Compile with npm run compile:local before this suite: Ganache uses Shanghai.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,Contract,ZeroAddress} from 'ethers';
const root=path.resolve(import.meta.dirname,'../..');
const art=n=>JSON.parse(fs.readFileSync(path.join(root,'contracts/artifacts',n+'.json'),'utf8'));
async function deploy(n,s,args=[]){const a=art(n),c=await new ContractFactory(a.abi,a.bytecode,s).deploy(...args);await c.waitForDeployment();return c;}
async function fixture(t){const rpc=ganache.provider({chain:{chainId:31337,hardfork:'shanghai'},logging:{quiet:true},wallet:{totalAccounts:3}});t.after(()=>rpc.disconnect());const p=new BrowserProvider(rpc,undefined,{cacheTimeout:-1});p.pollingInterval=10;const a=await p.getSigner(0),b=await p.getSigner(1);const gate=await deploy('ExperimentGate',a,[await a.getAddress()]);const x=await deploy('OperatingTokenMock',a,[18]),y=await deploy('OperatingTokenMock',a,[6]);for(const s of[a,b])for(const z of[x,y])await(await z.mint(await s.getAddress(),10n**25n)).wait();return{rpc,p,a,b,gate,x,y};}
async function rejected(fn){await assert.rejects(async()=>{const tx=await fn();if(tx.wait)await tx.wait();});}
async function latest(p){return Number((await p.getBlock('latest')).timestamp);}

test('new EVM suite: deposit ceiling cannot underfund split basket claims',async t=>{const{p,a,gate,x,y}=await fixture(t);const ordered=[x,y].sort((a,b)=>a.target.toLowerCase().localeCompare(b.target.toLowerCase()));const basket=await deploy('FixedBasket',a,[gate.target,ordered[0].target,ordered[1].target,1,1,await a.getAddress(),'Test basket','TST']);await(await gate.set(basket.target,true)).wait();for(const z of ordered)await(await z.approve(basket.target,100)).wait();const due=await latest(p)+1000;await(await basket.mint(1900000000000000000n,2,2,due)).wait();await(await basket.mint(1900000000000000000n,2,2,due)).wait();assert.equal(await basket.reserve0(),4n);assert.equal(await basket.reserve1(),4n);await(await gate.set(basket.target,false)).wait();await rejected(()=>basket.mint(1,1,1,due));await(await basket.redeem(3800000000000000000n,3,3,due)).wait();assert.equal(await basket.totalSupply(),0n);assert.equal(await basket.dust(ordered[0].target),1n);});

test('new EVM suite: matched early exits divide an impairment rather than pay nominal principal first',async t=>{const{p,a,b,gate,x}=await fixture(t);const m=await deploy('MatchedRightsVault',a,[gate.target,x.target,await latest(p)+1000]);await(await gate.set(m.target,true)).wait();for(const s of[a,b]){await(await x.connect(s).approve(m.target,50)).wait();await(await m.connect(s).pair(50,50)).wait();}await(await x.burn(m.target,50)).wait();const aa=await x.balanceOf(await a.getAddress()),bb=await x.balanceOf(await b.getAddress());await(await gate.set(m.target,false)).wait();await(await m.recombine(50,25)).wait();await(await m.connect(b).recombine(50,25)).wait();assert.equal(await x.balanceOf(await a.getAddress())-aa,25n);assert.equal(await x.balanceOf(await b.getAddress())-bb,25n);});

test('new EVM suite: a disabled entry gate cannot seize active loan collateral or block repayment',async t=>{const{a,b,gate,x,y}=await fixture(t);const m=await deploy('FixedTermCredit',a,[gate.target,x.target,y.target]);await(await gate.set(m.target,true)).wait();await(await x.approve(m.target,100)).wait();await(await m.request(100,20,22,1000)).wait();await(await y.connect(b).approve(m.target,20)).wait();await(await m.connect(b).fund(1)).wait();await(await gate.set(m.target,false)).wait();await(await y.approve(m.target,22)).wait();await(await m.repay(1)).wait();assert.equal(await m.claimable(await a.getAddress(),x.target),100n);assert.equal(await m.claimable(await b.getAddress(),y.target),22n);await(await m.connect(b).withdrawFor(await a.getAddress(),x.target)).wait();assert.equal(await m.claimable(await a.getAddress(),x.target),0n);});

test('new EVM suite: accepted covered-call exercise remains available after new-risk gate closes',async t=>{const{p,a,b,gate,x,y}=await fixture(t);const m=await deploy('CoveredCallBook',a,[gate.target,x.target,y.target]);await(await gate.set(m.target,true)).wait();await(await x.approve(m.target,100)).wait();await(await m.write(100,20,2,await latest(p)+1000)).wait();await(await y.connect(b).approve(m.target,22)).wait();await(await m.connect(b).take(1)).wait();await(await gate.set(m.target,false)).wait();await rejected(()=>m.close(1));await(await m.connect(b).exercise(1)).wait();assert.equal(await m.claimable(await b.getAddress(),x.target),100n);assert.equal(await m.claimable(await a.getAddress(),y.target),22n);});

test('new EVM suite: custody retires cell adapter grants; reauthorization is explicit and allowances reset',async t=>{const{p,a,b,gate,x,y}=await fixture(t);const account=await deploy('OperatingAccountMock',a,[await a.getAddress()]),factory=await deploy('ExperimentCellFactory',a);await(await account.run(factory.target,factory.interface.encodeFunctionData('create',[]))).wait();const cell=new Contract(await factory.cellOf(account.target),art('ExperimentCell').abi,a);const m=await deploy('FixedTermCredit',a,[gate.target,x.target,y.target]);await(await gate.set(m.target,true)).wait();await(await x.approve(cell.target,100)).wait();await(await cell.fund(x.target,100)).wait();await(await cell.adopt(m.target,[y.target])).wait();const data=m.interface.encodeFunctionData('request',[100,20,22,1000]);await(await account.transferControl(await b.getAddress())).wait();await rejected(async()=>cell.connect(b).execute(m.target,data,[[x.target,100]],[],await latest(p)+1000,0));await(await cell.connect(b).adopt(m.target,[y.target])).wait();await(await cell.connect(b).execute(m.target,data,[[x.target,100]],[],await latest(p)+1000,0)).wait();assert.equal(await x.allowance(cell.target,m.target),0n);assert.equal((await m.loan(1)).borrower,cell.target);assert.equal(await x.balanceOf(account.target),0n);});
