import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ganache from 'ganache';
import {BrowserProvider,Contract,ContractFactory,Wallet,keccak256,toUtf8Bytes,sha256,getBytes,AbiCoder,ZeroAddress} from 'ethers';
import {deployStack,deployContract} from '../../scripts/lib/deploy-stack.mjs';
const art=n=>JSON.parse(fs.readFileSync(new URL('../../contracts/artifacts/'+n+'.json',import.meta.url),'utf8'));
test('master NFT owns configurable routing and cartridge rights; custody changes preserve claims',async t=>{
 const rpc=ganache.provider({chain:{chainId:31337,hardfork:'shanghai'},wallet:{totalAccounts:5},logging:{quiet:true}});t.after(()=>rpc.disconnect());const provider=new BrowserProvider(rpc,undefined,{cacheTimeout:-1});provider.pollingInterval=10;
 const owner=await provider.getSigner(0),next=await provider.getSigner(1),recipient=await provider.getSigner(2);const addr=await owner.getAddress(),na=await next.getAddress(),ra=await recipient.getAddress();
 const stack=await deployStack({signer:owner,attesterAddress:ra,royaltyReceiver:addr,royaltyBps:0});const c=stack.collection;
 async function mint(tag){const secret=keccak256(toUtf8Bytes(tag)),commit=await c.commitmentFor(addr,secret,addr);await(await c.commitAwakening(commit)).wait();await rpc.request({method:'evm_mine',params:[]});await rpc.request({method:'evm_mine',params:[]});await(await c.revealAwakening(secret,addr)).wait();}
 await mint('confluence-1');await mint('confluence-2');const aa=await c.accountOf(1),ab=await c.accountOf(2),account=new Contract(aa,art('SovereignAccount').abi,owner);
 assert.equal(await c.artifactIdOfAccount(aa),1n);assert.notEqual((await c.organismOf(1)).seed,(await c.organismOf(2)).seed);
 await assert.rejects(c.transferFrom(addr,ab,1));
 const router=await deployContract('OwnerFeeRouter',owner,[aa,[addr,ra],[7,3]]);await(await router.depositNative({value:101})).wait();assert.equal(await router.claimable(ZeroAddress,addr),70n);assert.equal(await router.claimable(ZeroAddress,ra),31n);
 const change=router.interface.encodeFunctionData('configureSplit',[[na],[1]]);await assert.rejects(router.configureSplit([na],[1]));await(await account.execute(router.target,0,change)).wait();await(await router.depositNative({value:99})).wait();assert.equal(await router.claimable(ZeroAddress,addr),70n);assert.equal(await router.claimable(ZeroAddress,na),99n);
 const binding=await deployContract('ArtifactBinding',owner,[c.target]),cartridges=await deployContract('CartridgeRegistry',owner,[binding.target]);const html=toUtf8Bytes('<!doctype html><title>Test world</title>');const hash=sha256(html);await(await cartridges.mint(aa,JSON.stringify({spec:'awe.cartridge/1',name:'Test world',entry:'onchain',contentHash:hash}),hash)).wait();let info=await cartridges.launchManifest(1,addr);assert.equal(info.authorized,true);assert.equal(info.parentArtifactId,1n);
 await(await account.execute(cartridges.target,0,cartridges.interface.encodeFunctionData('publishContent',[1,html]))).wait();assert.equal(await cartridges.contentOf(1),'0x'+Buffer.from(html).toString('hex'));
 await(await c.transferFrom(addr,na,1)).wait();info=await cartridges.launchManifest(1,addr);assert.equal(info.authorized,false);assert.equal((await cartridges.launchManifest(1,na)).authorized,true);await assert.rejects(account.execute(router.target,0,change));await(await account.connect(next).execute(router.target,0,change)).wait();
 assert.equal(await router.totalClaimable(ZeroAddress),200n);await(await router.claimFor(ZeroAddress,addr)).wait();assert.equal(await router.claimable(ZeroAddress,addr),0n);assert.equal(await router.totalClaimable(ZeroAddress),130n);
});
test('threshold-two verifier boots safely and requires two distinct signatures',async t=>{
 const rpc=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai'},wallet:{totalAccounts:4}});t.after(()=>rpc.disconnect());const p=new BrowserProvider(rpc,undefined,{cacheTimeout:-1});p.pollingInterval=10;const owner=await p.getSigner();const accounts=Object.values(rpc.getInitialAccounts());const s1=new Wallet(accounts[1].secretKey),s2=new Wallet(accounts[2].secretKey);const v=await deployContract('ThresholdAttestationVerifier',owner,[await owner.getAddress(),2]);await(await v.setSigner(s1.address,true)).wait();await assert.rejects(v.freeze());await(await v.setSigner(s2.address,true)).wait();await(await v.freeze()).wait();const statement=keccak256(toUtf8Bytes('confluence-verifier-regression')),digest=getBytes(await v.attestationDigest(statement));const signers=[s1,s2].sort((a,b)=>a.address.toLowerCase().localeCompare(b.address.toLowerCase()));const sigs=await Promise.all(signers.map(s=>s.signMessage(digest))),coder=AbiCoder.defaultAbiCoder();assert.equal(await v.verify(statement,coder.encode(['bytes[]'],[sigs])),true);assert.equal(await v.verify(statement,coder.encode(['bytes[]'],[[sigs[0]]])),false);assert.equal(await v.verify(statement,coder.encode(['bytes[]'],[[sigs[0],sigs[0]]])),false);
});
test('onchain Base64 preserves every byte including short and partial groups',async t=>{const rpc=ganache.provider({logging:{quiet:true},chain:{hardfork:'shanghai'}});t.after(()=>rpc.disconnect());const p=new BrowserProvider(rpc,undefined,{cacheTimeout:-1});p.pollingInterval=10;const c=await deployContract('EncodingHarness',await p.getSigner());for(const size of [0,1,2,3,4,31,32,33,64,511]){const input=Uint8Array.from({length:size},(_,i)=>(i*47+1)%256);assert.equal(await c.encode(input),Buffer.from(input).toString('base64'));}});
