import {formatUnits} from '../vendor/ethers.min.js';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const td=x=>'<td>'+esc(x)+'</td>';
export function renderRehearsal(r){
  const rows=r.balances.filter(x=>x.delta!=='0').map(x=>'<tr>'+[x.address,x.asset,formatUnits(x.before,x.decimals),formatUnits(x.after,x.decimals),formatUnits(x.delta,x.decimals)].map(td).join('')+'</tr>').join('');
  const allowances=r.allowances.map(x=>'<tr>'+[x.asset,x.holder,x.spender,x.before,x.after].map(td).join('')+'</tr>').join('');
  const locks=r.locks.map(l=>{const a=l.after;return `<li>Lock ${esc(l.id)} · beneficiary ${esc(a[1])} · amount ${esc(a[3])} · released ${esc(a[4])} · ${a[8]?'linear':'cliff'} · cliff ${esc(new Date(Number(a[6])*1000).toISOString())} · end ${esc(new Date(Number(a[7])*1000).toISOString())}</li>`;}).join('');
  return `<section class="anima-rehearsal" data-private-surface><h3>Rehearsal · ${esc(r.status)}</h3><p>Possible next state at block ${esc(r.sourceBlock.number)}. This execution took place on a disposable fork. Your real balances have not changed.</p><code>${esc(r.sourceBlock.hash)}</code><div class="anima-table-scroll"><table><caption>Measured asset changes · native gas is included for the signing wallet</caption><thead><tr><th>Holder</th><th>Asset</th><th>Before</th><th>After</th><th>Change</th></tr></thead><tbody>${rows}</tbody></table></div><details><summary>Remaining token allowances</summary><div class="anima-table-scroll"><table><thead><tr><th>Asset</th><th>Holder</th><th>Spender</th><th>Before · raw</th><th>After · raw</th></tr></thead><tbody>${allowances}</tbody></table></div></details><p>Gas used: ${esc(r.gas.used)} · simulated cost: ${esc(formatUnits(r.gas.cost,18))} native.</p>${r.fees?`<p>Market fee: ${esc(r.fees.basisPointsPerHop)} basis points per hop, ${esc(r.fees.hops)} hop(s). Fees remain in pool reserves.</p>`:''}<p>Owner: ${esc(r.authority.before.owner)} → ${esc(r.authority.after.owner)}<br>Custody epoch: ${esc(r.authority.before.epoch)} → ${esc(r.authority.after.epoch)}<br>Action nonce: ${esc(r.authority.before.nonce)} → ${esc(r.authority.after.nonce)}</p>${locks?'<ul>'+locks+'</ul>':''}<p>These are observations from your chosen rehearsal service, not a cryptographic execution proof. Actual prices, gas, ordering and chain state can change. Minimum outputs and deadlines remain enforced by the transaction.</p></section>`;
}
