/** Isolated exact-contract economics. Never connects a public RPC or accepts keys/calldata. */
import fs from 'node:fs';
import path from 'node:path';
import net from 'node:net';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),base=path.join(root,'integrations/official-launch');
const require=createRequire(path.join(root,'package.json')),{ethers:E}=require('ethers');
const {OfficialProtocolClient,verifyProtocolReceipt,mineProtocolSalt}=await import(path.join(root,'web/launchpad/protocols-client.mjs'));
const artifact=n=>JSON.parse(fs.readFileSync(path.join(base,'artifacts',n+'.json'),'utf8'));
const plain=x=>JSON.parse(JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v));
export const SCENARIO_LIMITS=Object.freeze({maxSteps:128,actors:[0,1],mechanisms:['cca','doppler'],outcomes:['success','failed-minimum','migration-failure'],options:{protocolFeePips:{min:0,max:1000000,integer:true},proceedsShare:{min:'0',max:'0.5',decimal:true},tradingFee:{min:100,max:10000,integer:true}},actions:['advance','bid','trade','quote','checkpoint','exit','claim','migrate','sweepCurrency','sweepTokens','exitLockedLP','collectProtocolFees','collectIntegratorFees']});
const amount=(x,max,label='Amount')=>{if(!/^(?:0|[1-9]\d{0,6})(?:\.\d{1,18})?$/.test(String(x)))throw Error(`${label} must be a decimal amount with at most 18 places.`);const n=E.parseEther(String(x));if(n<=0n||n>E.parseEther(String(max)))throw Error(`${label} must be positive and at most ${max}.`);return String(x);};
const integer=(x,min,max,label)=>{const n=Number(x);if(!Number.isSafeInteger(n)||n<min||n>max)throw Error(`Invalid ${label}.`);return n;};
async function freePort(){const s=net.createServer();await new Promise((r,j)=>{s.once('error',j);s.listen(0,'127.0.0.1',r);});const p=s.address().port;await new Promise(r=>s.close(r));return p;}

export async function createOfficialScenario({mechanism='cca',outcome='success',options={}}={}, {signal}={}){
  signal?.throwIfAborted();
  if(!SCENARIO_LIMITS.mechanisms.includes(mechanism)||!SCENARIO_LIMITS.outcomes.includes(outcome)||mechanism==='doppler'&&outcome==='migration-failure')throw Error('Unsupported official protocol scenario.');
  for(const k of Object.keys(options))if(!SCENARIO_LIMITS.options[k])throw Error('Unknown scenario option.');
  const protocolFeePips=integer(options.protocolFeePips??10000,0,1000000,'CCA protocol fee'),tradingFee=integer(options.tradingFee??200,100,10000,'trading fee'),proceedsShare=String(options.proceedsShare??'0');if(!/^(?:0(?:\.\d{1,18})?)$/.test(proceedsShare)||E.parseEther(proceedsShare)>E.parseEther('0.5'))throw Error('Proceeds share must be between zero and 0.5.');
  const port=await freePort(),rpc=`http://127.0.0.1:${port}`,anvil=spawn(process.execPath,[path.join(root,'integrations/console/protocol/v4-hook/node_modules/@foundry-rs/anvil/bin.mjs'),'--host','127.0.0.1','--port',String(port),'--chain-id','31337','--hardfork','cancun','--timestamp','1800000000','--silent'],{stdio:['ignore','ignore','pipe']});
  let errors='',provider,closed=false,busy=false,initialized=false,gasBurn=0n,gasPaid=0n,gasByPayer=new Map(),baselineNative=0n,history=[],stepCount=0,last=null;anvil.stderr.on('data',d=>{errors=(errors+d).slice(-2000);});
  const close=async()=>{if(closed)return;closed=true;provider?.destroy();anvil.kill('SIGTERM');signal?.removeEventListener('abort',onAbort);};
  const onAbort=()=>{void close();};signal?.addEventListener('abort',onAbort,{once:true});
  try{
    let ready=false;for(let i=0;i<100;i++){signal?.throwIfAborted();if(anvil.exitCode!==null)throw Error(errors||'Local Anvil exited.');try{const r=await fetch(rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_chainId',params:[]})});ready=(await r.json()).result==='0x7a69';if(ready)break;}catch{}await new Promise(r=>setTimeout(r,100));}if(!ready)throw Error('Local scenario chain did not start.');
    provider=new E.JsonRpcProvider(rpc,31337,{staticNetwork:true,cacheTimeout:-1});provider.pollingInterval=10;
    const signers=await Promise.all([0,1,2,3,4,5,6,7,8,9].map(i=>provider.getSigner(i))),addresses=await Promise.all(signers.map(s=>s.getAddress())),creator=signers[0],owner=addresses[0],actors=[signers[1],signers[2]],protocolOwner=signers[3],protocolAddress=addresses[3],integrator=signers[4],integratorAddress=addresses[4];
    const tracked=new Map(addresses.map((a,i)=>[a, i===0?'Creator':i<3?`Participant ${i}`:i===3?'Protocol fee recipient':i===4?'Integrator fee recipient':`Unused local wallet ${i}`]));tracked.set(E.ZeroAddress,'Miner / minimum LP');
    const contracts={},receipts=[];
    const remember=(c,label)=>{tracked.set(E.getAddress(c.target||c),label);return c;};
    async function receipt(tx){let r,failure;try{r=await(await tx).wait();}catch(e){if(!e.receipt)throw e;r=e.receipt;failure=e;}if(initialized){const block=await provider.getBlock(r.blockNumber);gasPaid+=r.gasUsed*r.gasPrice;gasByPayer.set(r.from,(gasByPayer.get(r.from)||0n)+r.gasUsed*r.gasPrice);gasBurn+=r.gasUsed*(block.baseFeePerGas||0n);receipts.push({hash:r.hash,blockNumber:r.blockNumber,gasUsed:r.gasUsed,gasPrice:r.gasPrice,gasCost:r.gasUsed*r.gasPrice});}if(failure)throw failure;return r;}
    async function deploy(name,args=[],signer=creator){signal?.throwIfAborted();const a=artifact(name),c=await new E.ContractFactory(a.abi,a.bytecode,signer).deploy(...args);await c.waitForDeployment();contracts[name]=remember(c,name);return c;}
    function clientFor(signer){const address=signer.address,chain={provider,address,payer:address,chainId:31337,generation:0,async assertContext(){if(closed)throw Error('Scenario closed.');},async prepareExternal(p){return p;}};return new OfficialProtocolClient(chain);}
    const client=clientFor(creator);
    async function run(plan,signer=creator){signal?.throwIfAborted();for(const s of plan.spend||[]){const t=new E.Contract(s.tokenAddress,['function approve(address,uint256) returns(bool)'],signer);await receipt(t.approve(plan.request.to,s.amount));}const r=await receipt(signer.sendTransaction(plan.request));const verification=await verifyProtocolReceipt(provider,{...plan,account:signer.address,payer:signer.address,final:true},r);return {receipt:r,verification};}
    const manager=await deploy('PoolManager',[owner]);let token,auction,strategy,airlock,router,quoteLens,terms,state,feeController;
    if(mechanism==='cca'){
      feeController=await deploy('ProtocolFeeController',[protocolAddress],protocolOwner);await receipt(feeController.setProtocolFeeRecipient(protocolAddress));await receipt(feeController.setGlobalProtocolFeePips(outcome==='migration-failure'?1000000:protocolFeePips));
      const factory=await deploy('ContinuousClearingAuctionFactory',[feeController.target]),launcher=await deploy('OfficialCCALauncher',[factory.target]);token=await deploy('OfficialLaunchToken',['Scenario CCA','SCCA',E.parseEther('1000000'),owner]);
      const permit=await deploy('Permit2'),weth=await deploy('WETH'),pm=await deploy('PositionManager',[manager.target,permit.target,100000,E.ZeroAddress,weth.target]),create2=await deploy('OfficialCreate2');
      const a=artifact('LBPStrategy'),args=[pm.target,manager.target,factory.target],init=(await new E.ContractFactory(a.abi,a.bytecode).getDeployTransaction(...args)).data,mined=await mineProtocolSalt({deployer:create2.target,caller:owner,initCodeHash:E.keccak256(init),flags:0x2000,signal});await receipt(create2.deploy(mined.salt,init));strategy=remember(new E.Contract(mined.address,a.abi,creator),'CCA migration strategy');
      const b=await provider.getBlockNumber();terms={mechanism,version:'Uniswap CCA v2.1.0',outcome,totalSupply:'1000000',distributed:'2000',auctionAllocation:'1000',liquidityReserve:'1000',floorPrice:'0.00001',priceStep:'0.000001',startBlock:b+12,endBlock:b+92,claimBlock:b+94,minimumRaise:outcome==='failed-minimum'?'10':'0',protocolFeePips:outcome==='migration-failure'?1000000:protocolFeePips,feePolicy:'Mutable controller fee is assessed on proceeds sweep.',migration:'Official CCA to Uniswap v4 position NFT'};
      const p=await client.ccaCreate({factory:factory.target,launcher:launcher.target,strategy:strategy.target,token:token.target,currency:E.ZeroAddress,amount:terms.distributed,reserve:terms.liquidityReserve,floorPrice:terms.floorPrice,priceStep:terms.priceStep,startBlock:terms.startBlock,endBlock:terms.endBlock,claimBlock:terms.claimBlock,minimumRaise:terms.minimumRaise,recipient:owner,positionRecipient:owner,salt:E.ZeroHash});await run(p);auction=remember(new E.Contract(p.meta.auction,artifact('ContinuousClearingAuction').abi,creator),'CCA auction');terms.auction=auction.target;
    }else{
      airlock=await deploy('Airlock',[protocolAddress],protocolOwner);const factory=await deploy('DopplerERC20V1Factory',[airlock.target]),governance=await deploy('LaunchpadGovernanceFactory'),deployer=await deploy('DopplerDeployer',[manager.target]),initializer=await deploy('UniswapV4Initializer',[airlock.target,manager.target,deployer.target]),topUp=await deploy('TopUpDistributor',[airlock.target]),weth=await deploy('WETH');
      const v2code='0x'+fs.readFileSync(path.join(base,'vendor/doppler/script/utils/uniswapV2Factory.bytecode'),'utf8').trim().replace(/^0x/,'');const v2factory=await new E.ContractFactory(['constructor(address)'],v2code,creator).deploy(owner);await v2factory.waitForDeployment();remember(v2factory,'Uniswap v2 factory');
      const migrator=await deploy('UniswapV2MigratorSplit',[airlock.target,v2factory.target,topUp.target,weth.target]);router=await deploy('OfficialV4SwapRouter',[manager.target]);quoteLens=await deploy('OfficialV4QuoteLens',[manager.target]);
      await run(await clientFor(protocolOwner).approveModules({airlock:airlock.target,modules:[{address:factory.target,state:1},{address:governance.target,state:2},{address:initializer.target,state:3},{address:migrator.target,state:4}]}),protocolOwner);
      if(E.parseEther(proceedsShare)>0n)await run(await clientFor(protocolOwner).enableProceedsSplit({airlock:airlock.target,migrator:migrator.target}),protocolOwner);
      const t=(await provider.getBlock('latest')).timestamp;terms={mechanism,version:'Doppler 5754c7ee',outcome,totalSupply:'100000',auctionAllocation:'100000',minimumRaise:outcome==='failed-minimum'?'10':'0.01',maximumRaise:'100',starts:t+40,ends:t+440,tradingFee,proceedsShare,feePolicy:'Actual Airlock migration protocol/integrator fees and official one-year 5% LP lock.',migration:'Dynamic v4 Doppler to official Uniswap v2 migrator'};
      const p=await client.dopplerCreate({airlock:airlock.target,tokenFactory:factory.target,governanceFactory:governance.target,poolInitializer:initializer.target,liquidityMigrator:migrator.target,name:'Scenario Doppler',symbol:'SDOP',supply:terms.totalSupply,amount:terms.auctionAllocation,numeraire:E.ZeroAddress,minimumRaise:terms.minimumRaise,maximumRaise:terms.maximumRaise,starts:terms.starts,ends:terms.ends,epochLength:40,gamma:800,startingTick:6000,endingTick:60000,tickSpacing:2,slugs:10,fee:tradingFee,recipient:owner,integrator:integratorAddress,proceedsShare,proceedsRecipient:owner},{signal});await run(p);token=remember(new E.Contract(p.meta.token,artifact('DopplerERC20V1').abi,creator),'Doppler token');remember(p.meta.hook,'Doppler auction hook');state=await client.readDoppler({airlock:airlock.target,asset:token.target});remember(state.migrationPool,'Migrated Uniswap v2 pool');remember(state.locker,'Protocol LP locker');terms.airlock=airlock.target;terms.hook=p.meta.hook;
    }
    terms.token=token.target;terms.currency=E.ZeroAddress;
    async function balances(){const block=await provider.getBlock('latest'),rows=await Promise.all([...tracked].map(async([address,label])=>({address,label,native:await provider.getBalance(address,block.number),token:await token.balanceOf(address,{blockTag:block.number})})));return {block,rows,native:rows.reduce((a,b)=>a+b.native,0n),token:rows.reduce((a,b)=>a+b.token,0n)};}
    const initial=await balances();baselineNative=initial.native;initialized=true;
    async function snapshot(){if(closed)throw Error('Scenario closed.');const b=await balances();let protocolFees={},custody={},bids=[];
      if(mechanism==='cca'){state=await client.readCCA({auction:auction.target,owner:null});const n=Number(state.nextBidId);if(n>128)throw Error('Scenario bid limit exceeded.');for(let i=0;i<n;i++){const v=await auction.bids(i);bids.push({id:i,owner:v.owner,amount:v.amountQ96/(1n<<96n),maxPrice:v.maxPrice,exitedBlock:v.exitedBlock,tokensFilled:v.tokensFilled});}protocolFees={ratePips:terms.protocolFeePips,recipient:protocolAddress,receivedNative:await provider.getBalance(protocolAddress)-initial.rows.find(x=>x.address===protocolAddress).native+(gasByPayer.get(protocolAddress)||0n)};custody={liquidityNFTs:await contracts.PositionManager.balanceOf(owner),reserveTokens:await token.balanceOf(strategy.target),migrationOutcome:history.filter(h=>h.verification?.outcome).at(-1)?.verification.outcome||'pending'};
      }else{state=await client.readDoppler({airlock:airlock.target,asset:token.target});protocolFees={native:await airlock.getProtocolFees(E.ZeroAddress),token:await airlock.getProtocolFees(token.target),integratorNative:await airlock.getIntegratorFees(integratorAddress,E.ZeroAddress),integratorToken:await airlock.getIntegratorFees(integratorAddress,token.target)};const pair=new E.Contract(state.migrationPool,['function totalSupply() view returns(uint256)','function balanceOf(address) view returns(uint256)'],provider);const lpSupply=await pair.totalSupply(),lpRows=await Promise.all([...tracked].map(async([address,label])=>({address,label,balance:await pair.balanceOf(address)})));custody={...state.lpLock,pool:state.migrationPool,lpSupply,lpBalances:lpRows.filter(x=>x.balance>0n),lpResidual:lpSupply-lpRows.reduce((s,x)=>s+x.balance,0n),migrated:state.migrated};}
      const totalSupply=await token.totalSupply();return plain({mode:'isolated-contract-scenario',chainId:31337,mechanism,outcome,terms,blockNumber:b.block.number,timestamp:b.block.timestamp,phase:state.phase,actors:actors.map((s,i)=>({id:i,address:s.address,label:`Participant ${i+1}`})),balances:b.rows.filter(x=>!x.label.startsWith('Unused local wallet')).map(x=>({...x,nativeFormatted:E.formatEther(x.native),tokenFormatted:E.formatEther(x.token),nativeDelta:x.native-(initial.rows.find(y=>y.address===x.address)?.native||0n),tokenDelta:x.token-(initial.rows.find(y=>y.address===x.address)?.token||0n),gasPaid:gasByPayer.get(x.address)||0n,economicNativeDelta:x.native-(initial.rows.find(y=>y.address===x.address)?.native||0n)+(gasByPayer.get(x.address)||0n)})),protocolFees,custody,bids,conservation:{totalSupply,trackedTokens:b.token,tokenResidual:totalSupply-b.token,initialNative:baselineNative,trackedNative:b.native,nativeGasPaid:gasPaid,nativeBurned:gasBurn,nativeResidual:baselineNative-b.native-gasBurn,note:'Native conservation includes all ten local wallets, contracts and miner; gas paid is separate from sale economics. Burned base fees are accounted. Token and LP residuals must be zero.'},state,history,last,remainingSteps:128-stepCount});}
    async function step(command){if(closed||busy)throw Error(closed?'Scenario closed.':'A scenario step is already running.');if(++stepCount>128)throw Error('Scenario step limit reached.');busy=true;const allowed=new Set(['action','actor','phase','amount','maxPrice','side','minimumOut','bidId']);let row={sequence:stepCount,command:plain(command),status:'rejected',receipts:[]};receipts.length=0;
      try{if(!command||Object.keys(command).some(k=>!allowed.has(k))||!SCENARIO_LIMITS.actions.includes(command.action))throw Error('Unsupported scenario command.');const actor=integer(command.actor??0,0,1,'participant'),signer=actors[actor],c=clientFor(signer),action=command.action;let result;
        if(action==='advance'){if(!['start','end','claim','unlock'].includes(command.phase))throw Error('Unknown lifecycle boundary.');const current=await provider.getBlock('latest');if(mechanism==='cca'){if(command.phase==='unlock')throw Error('CCA position NFTs have no imposed LP lock.');const target=command.phase==='start'?terms.startBlock:command.phase==='end'?terms.endBlock+1:terms.claimBlock+1;if(target<=current.number)throw Error('That boundary has already passed.');await provider.send('anvil_mine',[E.toQuantity(target-current.number)]);}else{const s=await client.readDoppler({airlock:airlock.target,asset:token.target}),target=command.phase==='start'?terms.starts:command.phase==='end'||command.phase==='claim'?terms.ends+1:s.lpLock.minUnlockDate+1;if(target<=current.timestamp)throw Error('That boundary has already passed or its lock is not active.');await provider.send('evm_setNextBlockTimestamp',[target]);await provider.send('evm_mine',[]);}row.status='advanced';}
        else if(mechanism==='cca'){if(action==='bid')result=await run(await c.ccaBid({auction:auction.target,amount:amount(command.amount,1000),maxPrice:amount(command.maxPrice,1000,'Maximum price'),recipient:signer.address}),signer);else if(['checkpoint','exit','claim','migrate','sweepCurrency','sweepTokens'].includes(action))result=await run(await (action==='sweepTokens'?client:c).ccaAction({auction:auction.target,strategy:strategy.target,action,bidId:['exit','claim'].includes(action)?integer(command.bidId,0,10000,'bid ID'):undefined}),action==='sweepTokens'?creator:signer);else throw Error('This command belongs to another launch mechanism.');}
        else if(['trade','quote'].includes(action)){if(!['buy','sell'].includes(command.side))throw Error('Choose buy or sell.');const input={airlock:airlock.target,asset:token.target,router:router.target,quoter:quoteLens.target,side:command.side,amount:amount(command.amount,command.side==='buy'?1000:1000000),minimumOut:command.minimumOut===undefined||Number(command.minimumOut)===0?undefined:amount(command.minimumOut,1000000,'Minimum output'),recipient:signer.address};if(action==='quote'){row.quote=await c.dopplerQuote(input);row.status='quoted';}else result=await run(await c.dopplerSwap(input),signer);}
        else if(['migrate','exitLockedLP'].includes(action))result=await run(await c.dopplerAction({airlock:airlock.target,asset:token.target,action}),signer);
        else if(['collectProtocolFees','collectIntegratorFees'].includes(action)){const isProtocol=action==='collectProtocolFees',who=isProtocol?protocolOwner:integrator;let collected=[];for(const asset of [E.ZeroAddress,token.target]){const n=isProtocol?await airlock.getProtocolFees(asset):await airlock.getIntegratorFees(who.address,asset);if(n){await run(await clientFor(who).dopplerAction({airlock:airlock.target,asset:token.target,action,feeToken:asset,recipient:who.address}),who);collected.push({asset,amount:n,recipient:who.address});}}if(!collected.length)throw Error('There are no accrued fees to collect.');row.collected=collected;row.status='confirmed';}
        else throw Error('This command belongs to another launch mechanism.');
        if(result){row.status='confirmed';row.verification=result.verification;}
      }catch(error){row.error=String(error.shortMessage||error.message).slice(0,800);}finally{row.receipts=plain(receipts);history.push(plain(row));last=plain(row);busy=false;}return snapshot();
    }
    return {step,snapshot,close};
  }catch(error){await close();throw error;}
}
