import {InstrumentEngine,DAY} from '../instruments/engine.mjs';
import {wei,E18,MAX112,fingerprint,KingdomModel} from '../kingdom/model.mjs';
/** Finite local execution model. Never evaluates user code or requests a wallet.
 * Published content is durable; grants are epoch-bound; obligations have their own lifecycle.
 * Laboratory capital is explicitly segregated, not a second allowance on the root account. */
export const LAB_MODULES=['granary','issue','strips','counter','scrivener'];
export function ceilRatio(a,b,d){a=BigInt(a);b=BigInt(b);d=BigInt(d);if(a<0n||b<0n||d<=0n)throw Error('Invalid ratio.');return (a*b+d-1n)/d;}
export function matchedExit(assets,pairs,burn){assets=BigInt(assets);pairs=BigInt(pairs);burn=BigInt(burn);if(assets<0n||pairs<=0n||burn<=0n||burn>pairs)throw Error('Invalid matched exit.');return assets*burn/pairs;}
const opQ=v=>{if(!/^[0-9]{1,34}$/.test(String(v)))throw Error('Expected integer base units.');const n=BigInt(v);if(n<=0n||n>MAX112)throw Error('Amount out of range.');return n;};
const opN=v=>{if(!/^[0-9]{1,34}$/.test(String(v))||BigInt(v)>MAX112)throw Error('Invalid stored quantity.');return BigInt(v);};
const opText=(v,max=256)=>{if(typeof v!=='string'||!v.trim()||new TextEncoder().encode(v).length>max)throw Error('Text is empty or too long.');return v.trim();};
const opDays=(v,max=3650)=>{if(!Number.isInteger(v)||v<1||v>max)throw Error('Invalid duration.');return v;};
export const opGet=(xs,id)=>{const v=xs.find(x=>x.id===Number(id));if(!v)throw Error('Unknown operating record.');return v;};
const opAdd=(b,k,n)=>{const v=BigInt(b[k]||0)+BigInt(n);if(v<0n||v>MAX112)throw Error('Balance out of range.');b[k]=String(v);};
const opTake=(b,k,n)=>{n=opQ(n);if(BigInt(b[k]||0)<n)throw Error('Insufficient '+k+' in this compartment.');opAdd(b,k,-n);};
function opFresh(){return {schema:'idfbi/operating-state/1.6',editions:[],installations:[],grants:[],commissions:[],collectibles:[],venues:[],cells:[],loans:[],options:[],covenants:{},applications:[],lossSink:{}};}
export class OperatingEngine extends InstrumentEngine {
 constructor(now){super(now);this.op=opFresh();this._attach();
  if(!this.world.s.identities.some(a=>a.id===2)){this.world.s.identities.push({id:2,name:"Guest instrument account",owner:"guest",epoch:1,nonce:0,seed:29,color:0,balances:{ETH:String(wei("3")),AUR:String(wei("5000"))},lease:null});this.record("REHEARSAL_ACCOUNT",2,{note:"Fictional Guest allocation; not a mint or deposit."});}
  for(const l of this.world.s.listings.filter(l=>l.status==='listed'))this._bindListing(l);
 }
 _attach(){const self=this,w=this.world;
  w._owner=function(id){const a=this.identity(id);const d=self._delegation;if(a.owner===this.s.actor)return a;if(d&&d.identity===a.id&&d.epoch===a.epoch&&a.owner!=='escrow')return a;throw Error('Only the current owner may create new risk.');};
  const check=KingdomModel.prototype.checkListing;
  w.checkListing=function(id){const l=check.call(this,id),c=self.op.covenants[l.id];if(!c||c.moduleRoot!==fingerprint(self.moduleSnapshot(l.identity)))throw Error('Operating covenant changed or missing. Seller must refresh the listing.');return l;};
  w.listEstate=function(id,n,days=7){return self.atomic(()=>{const l=KingdomModel.prototype.listEstate.call(this,id,n,days);self._bindListing(l);return l;});};
 }
 atomic(fn){const saved=this.op?structuredClone(this.op):null;try{return super.atomic(fn);}catch(e){if(saved)this.op=saved;throw e;}}
 context(anchor){return fingerprint({base:super.context(anchor),operating:this.moduleSnapshot(this.world.s.selected)});}
 record(kind,id,data){const causes=new Set(data.causes||[]);if(data.cause)causes.add(data.cause);for(const key of ['commission','loan','option','venue','grant','edition'])if(data[key]){const prior=this.world.s.events.findLast(e=>e.data[key]===data[key]);if(prior)causes.add(prior.seq);}return this.world._event(kind,id,{...data,causes:[...causes].filter(n=>Number.isInteger(n)&&n>0&&n<=this.world.s.seq)});}
 edition(id){return opGet(this.op.editions,id);}
 publish(title,raw,parent=0){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected);if(this.op.editions.length>=256)throw Error('Edition capacity reached.');const recipe=this.normalize(raw);if(parent)this.edition(parent);const e={id:this.op.editions.length+1,title:opText(title,96),author:this.world.s.actor,identity:a.id,epoch:a.epoch,time:this.world.s.now,parent:Number(parent),recipe};e.contentHash=fingerprint({schema:'idfbi/typed-edition/1.6',recipe});e.editionHash=fingerprint(e);e.receipt=this.record('EDITION_PUBLISHED',a.id,{edition:e.id,contentHash:e.contentHash,parent:e.parent}).seq;this.op.editions.push(e);return e;});}
 install(id){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected),e=this.edition(id);if(this.op.installations.some(x=>x.identity===a.id&&x.edition===e.id))throw Error('Edition already in this library.');const i={id:this.op.installations.length+1,identity:a.id,edition:e.id,contentHash:e.contentHash,readyAt:this.world.s.now+7*DAY};this.op.installations.push(i);this.record('EDITION_ADOPTED',a.id,{edition:e.id,readyAt:i.readyAt,cause:e.receipt});return i;});}
 grant(edition,{caller,perCall,total,calls=1,days=7}){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected),e=this.edition(edition),i=this.op.installations.find(x=>x.identity===a.id&&x.edition===e.id);if(!i||this.world.s.now<i.readyAt)throw Error('Installation is still in its seven-day review period.');if(!['you','guest'].includes(caller)||!Number.isInteger(calls)||calls<1||calls>100)throw Error('Invalid caller or call limit.');const p=opQ(perCall),t=opQ(total);if(p>t||BigInt(e.recipe.amount)>p)throw Error('Recipe exceeds the authorized budget.');opDays(days,30);const g={id:this.op.grants.length+1,identity:a.id,edition:e.id,editionHash:e.editionHash,epoch:a.epoch,caller,perCall:String(p),total:String(t),spent:'0',calls,used:0,expires:this.world.s.now+days*DAY,revoked:false};this.op.grants.push(g);this.record('GRANT_CREATED',a.id,{grant:g.id,edition:e.id,epoch:a.epoch,caller,budget:g.total,cause:e.receipt});return g;});}
 grantStatus(g){const a=this.world.identity(g.identity);return g.revoked?'revoked':a.owner==='escrow'?'escrowed':a.epoch!==g.epoch?'custody changed':this.world.s.now>=g.expires?'expired':g.used>=g.calls?'exhausted':'active';}
 revoke(id){const g=opGet(this.op.grants,id);this.world._owner(g.identity);g.revoked=true;this.record('GRANT_REVOKED',g.identity,{grant:g.id});}
 run(id){return this.atomic(()=>{const g=opGet(this.op.grants,id),e=this.edition(g.edition),n=BigInt(e.recipe.amount);if(this.grantStatus(g)!=='active'||g.caller!==this.world.s.actor||e.editionHash!==g.editionHash||n>BigInt(g.perCall)||BigInt(g.spent)+n>BigInt(g.total))throw Error('Grant rejects this caller, custody epoch, edition or budget.');const selection=this.world.s.selected;this._delegation={identity:g.identity,epoch:g.epoch};this.world.s.selected=g.identity;try{const result=this.apply(e.recipe);g.used++;g.spent=String(BigInt(g.spent)+n);this.record('EDITION_EXECUTED',g.identity,{grant:g.id,edition:e.id,amount:String(n),asset:e.recipe.input,cause:e.receipt});return result;}finally{this._delegation=null;this.world.s.selected=selection;}});}
 commission({title,worker,asset,amount,days=14,room=1}){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected);if(!['you','guest'].includes(worker)||worker===this.world.s.actor)throw Error('Choose the other participant.');this.world.room(room);opDays(days,90);const n=opQ(amount);opTake(a.balances,asset,n);const c={id:this.op.commissions.length+1,identity:a.id,sponsor:this.world.s.actor,reviewer:this.world.s.actor,worker,asset,amount:String(n),title:opText(title,256),deadline:this.world.s.now+days*DAY,reviewEnds:this.world.s.now+(days+3)*DAY,room:Number(room),status:'offered',edition:0};c.receipt=this.record('COMMISSION_FUNDED',a.id,{commission:c.id,room:c.room,asset,amount:c.amount}).seq;this.op.commissions.push(c);return c;});}
 acceptCommission(id){const c=opGet(this.op.commissions,id);if(this.world.s.actor!==c.worker||c.status!=='offered'||this.world.s.now>=c.deadline)throw Error('Commission cannot be accepted.');c.status='accepted';this.record('COMMISSION_ACCEPTED',c.identity,{commission:c.id,cause:c.receipt});}
 submitCommission(id,edition){const c=opGet(this.op.commissions,id),e=this.edition(edition);if(this.world.s.actor!==c.worker||e.author!==c.worker||c.status!=='accepted'||this.world.s.now>=c.deadline)throw Error('Deliver your own edition before the deadline.');c.edition=e.id;c.status='submitted';this.record('WORK_SUBMITTED',c.identity,{commission:c.id,edition:e.id,cause:c.receipt});}
 decideCommission(id,approve){return this.atomic(()=>{const c=opGet(this.op.commissions,id);if(c.status!=='submitted'||this.world.s.actor!==c.reviewer||this.world.s.now>=c.reviewEnds)throw Error('Only the named reviewer can decide within the review window.');if(approve){opAdd(this.extra.personalBalances[c.worker],c.asset,c.amount);c.status='paid';}else{opAdd(this.world.identity(c.identity).balances,c.asset,c.amount);c.status='refunded';}this.record(approve?'WORK_PAID':'WORK_REJECTED',c.identity,{commission:c.id,edition:c.edition,cause:c.receipt});});}
 refundCommission(id){return this.atomic(()=>{const c=opGet(this.op.commissions,id);const timeout=this.world.s.now>=(c.status==='submitted'?c.reviewEnds:c.deadline);if(!['offered','accepted','submitted'].includes(c.status)||!timeout)throw Error('The fixed refund deadline has not arrived.');c.status='refunded';opAdd(this.world.identity(c.identity).balances,c.asset,c.amount);this.record('COMMISSION_REFUNDED',c.identity,{commission:c.id,cause:c.receipt});});}
 mintCollectible(edition){const a=this.world._owner(this.world.s.selected),e=this.edition(edition);const t={id:this.op.collectibles.length+1,edition:e.id,holder:a.id,venue:0};this.op.collectibles.push(t);this.record('EDITION_COLLECTED',a.id,{collectible:t.id,edition:e.id,cause:e.receipt});return t;}
 openShelf(collectible,price,days=7){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected),t=opGet(this.op.collectibles,collectible);if(t.holder!==a.id||t.venue)throw Error('Collectible is not free inventory.');opDays(days,365);const v={id:this.op.venues.length+1,identity:a.id,collectible:t.id,price:String(opQ(price)),bondUntil:this.world.s.now+days*DAY,reserve:'0',status:'open'};t.venue=v.id;this.op.venues.push(v);this.record('VENUE_OPENED',a.id,{venue:v.id,collectible:t.id,bondUntil:v.bondUntil});return v;});}
 buyShelf(id){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected),v=opGet(this.op.venues,id),t=opGet(this.op.collectibles,v.collectible);if(v.status!=='open'||a.id===v.identity)throw Error('Shelf unavailable or self-trade.');opTake(a.balances,'ETH',v.price);v.reserve=v.price;v.status='sold';t.holder=a.id;t.venue=0;this.record('SHELF_PURCHASED',a.id,{venue:v.id,collectible:t.id,amount:v.price,asset:'ETH'});});}
 closeShelf(id){return this.atomic(()=>{const v=opGet(this.op.venues,id),a=this.world._owner(v.identity);if(v.status==='closed'||this.world.s.now<v.bondUntil)throw Error('Venue bond has not ended.');const t=opGet(this.op.collectibles,v.collectible);if(v.status==='open'){t.venue=0;t.holder=a.id;}opAdd(a.balances,'ETH',v.reserve);v.reserve='0';v.status='closed';this.record('VENUE_CLOSED',a.id,{venue:v.id});});}
 cell(id=this.world.s.selected,create=false){let c=this.op.cells.find(x=>x.identity===Number(id));if(!c&&create){c={id:this.op.cells.length+1,identity:Number(id),enabled:[],enabledEpoch:this.world.identity(id).epoch,balances:{},strategy:{asset:'AUR',assets:'0',shares:'0'},basket:{supply:'0',ETH:'0',AUR:'0'},strip:null};this.op.cells.push(c);}if(!c)throw Error('Allocate a separate laboratory balance first.');return c;}
 allocate(asset,amount){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected),n=opQ(amount),c=this.cell(a.id,true);opTake(a.balances,asset,n);opAdd(c.balances,asset,n);this.record('LAB_ALLOCATED',a.id,{cell:c.id,asset,amount:String(n)});return c;});}
 enableLab(module){const a=this.world._owner(this.world.s.selected),c=this.cell(a.id);if(!LAB_MODULES.includes(module))throw Error('This module has no runnable adapter.');if(c.enabledEpoch!==a.epoch){c.enabled=[];c.enabledEpoch=a.epoch;}if(!c.enabled.includes(module))c.enabled.push(module);this.record('LAB_ENABLED',a.id,{cell:c.id,module});}
 labOwner(module,id=this.world.s.selected,newRisk=true){const a=this.world._owner(id),c=this.cell(a.id);if(newRisk&&(c.enabledEpoch!==a.epoch||!c.enabled.includes(module)))throw Error('This experiment is locked in the engine. Explicitly enable it for this cell and custody epoch.');return c;}
 withdrawLab(asset,n){return this.atomic(()=>{const a=this.world._owner(this.world.s.selected),c=this.cell(a.id);n=opQ(n);opTake(c.balances,asset,n);opAdd(a.balances,asset,n);this.record('LAB_RETURNED',a.id,{asset,amount:String(n)});});}
 sow(n,minShares=1n){return this.atomic(()=>{const c=this.labOwner('granary'),s=c.strategy;n=opQ(n);const shares=BigInt(s.shares)===0n?n:n*BigInt(s.shares)/BigInt(s.assets);if(shares<opQ(minShares)||shares===0n)throw Error('Minimum shares not met; zero-asset strategies cannot accept a deposit.');opTake(c.balances,s.asset,n);opAdd(s,'assets',n);opAdd(s,'shares',shares);this.record('STRATEGY_DEPOSIT',c.identity,{asset:s.asset,amount:String(n),shares:String(shares),cell:c.id});return shares;});}
 reap(shares,minAssets=1n){return this.atomic(()=>{const c=this.labOwner('granary',this.world.s.selected,false),s=c.strategy;shares=opQ(shares);if(shares>BigInt(s.shares))throw Error('Insufficient strategy shares.');const n=BigInt(s.assets)*shares/BigInt(s.shares);if(n<opQ(minAssets))throw Error('Minimum assets not met.');opAdd(s,'shares',-shares);opAdd(s,'assets',-n);opAdd(c.balances,s.asset,n);this.record('STRATEGY_WITHDRAW',c.identity,{asset:s.asset,amount:String(n),shares:String(shares)});return n;});}
 mintBasket(shares){return this.atomic(()=>{const c=this.labOwner('issue'),b=c.basket;shares=opQ(shares);const eth=ceilRatio(shares,wei('0.0001'),E18),aur=ceilRatio(shares,wei('10'),E18);opTake(c.balances,'ETH',eth);opTake(c.balances,'AUR',aur);opAdd(b,'ETH',eth);opAdd(b,'AUR',aur);opAdd(b,'supply',shares);this.record('BASKET_MINTED',c.identity,{shares:String(shares),ETH:String(eth),AUR:String(aur)});return {eth,aur};});}
 redeemBasket(shares){return this.atomic(()=>{const c=this.labOwner('issue',this.world.s.selected,false),b=c.basket;shares=opQ(shares);if(shares>BigInt(b.supply))throw Error('Insufficient basket shares.');const eth=shares*wei('0.0001')/E18,aur=shares*wei('10')/E18;opAdd(b,'supply',-shares);opAdd(b,'ETH',-eth);opAdd(b,'AUR',-aur);opAdd(c.balances,'ETH',eth);opAdd(c.balances,'AUR',aur);if(b.supply==='0'){opAdd(c.balances,'ETH',b.ETH);opAdd(c.balances,'AUR',b.AUR);b.ETH=b.AUR='0';}this.record('BASKET_REDEEMED',c.identity,{shares:String(shares)});return {eth,aur};});}
 strip(n,days=30){return this.atomic(()=>{const c=this.labOwner('strips');if(c.strip&&BigInt(c.strip.pairs)>0n)throw Error('Close this matched series before starting another.');n=opQ(n);opDays(days);opTake(c.balances,'AUR',n);c.strip={asset:'AUR',assets:String(n),pairs:String(n),initial:String(n),maturity:this.world.s.now+days*DAY};this.record('PAIRS_CREATED',c.identity,{amount:String(n),asset:'AUR',maturity:c.strip.maturity});});}
 unstrip(n){return this.atomic(()=>{const c=this.labOwner('strips',this.world.s.selected,false),s=c.strip;if(!s)throw Error('No matched series.');n=opQ(n);const out=matchedExit(s.assets,s.pairs,n);opAdd(s,'pairs',-n);opAdd(s,'assets',-out);opAdd(c.balances,s.asset,out);this.record('PAIRS_RECOMBINED',c.identity,{amount:String(n),received:String(out),asset:s.asset});return out;});}
 stress(module,bps){return this.atomic(()=>{const c=this.labOwner(module);if(!['granary','strips'].includes(module)||!Number.isInteger(bps)||bps<1||bps>10000)throw Error('Loss scenario must be 1–10,000 basis points.');const p=module==='granary'?c.strategy:c.strip;if(!p)throw Error('No funded position.');const n=BigInt(p.assets)*BigInt(bps)/10000n;opAdd(p,'assets',-n);opAdd(this.op.lossSink,p.asset,n);this.record('LAB_LOSS_SCENARIO',c.identity,{module,asset:p.asset,amount:String(n),note:'Explicit hypothetical loss; not market data.'});return n;});}
 requestLoan(collateral,principal,repayment,days=14){return this.atomic(()=>{const c=this.labOwner('counter');collateral=opQ(collateral);principal=opQ(principal);repayment=opQ(repayment);if(repayment<principal)throw Error('Repayment below principal.');opDays(days,365);opTake(c.balances,'AUR',collateral);const l={id:this.op.loans.length+1,borrower:c.identity,lender:0,collateral:String(collateral),principal:String(principal),repayment:String(repayment),days,offerUntil:this.world.s.now+7*DAY,due:0,status:'offered'};this.op.loans.push(l);this.record('CREDIT_REQUESTED',c.identity,{loan:l.id,amount:l.principal,asset:'ETH'});return l;});}
 fundLoan(id){return this.atomic(()=>{const c=this.labOwner('counter'),l=opGet(this.op.loans,id);if(l.status!=='offered'||c.identity===l.borrower||this.world.s.now>=l.offerUntil)throw Error('Credit offer unavailable.');opTake(c.balances,'ETH',l.principal);opAdd(this.cell(l.borrower).balances,'ETH',l.principal);l.lender=c.identity;l.due=this.world.s.now+l.days*DAY;l.status='active';this.record('CREDIT_FUNDED',c.identity,{loan:l.id,borrower:l.borrower,due:l.due});});}
 repayLoan(id){return this.atomic(()=>{const l=opGet(this.op.loans,id),c=this.labOwner('counter',l.borrower,false);if(l.status!=='active'||this.world.s.now>=l.due)throw Error('Repayment window has closed.');opTake(c.balances,'ETH',l.repayment);opAdd(this.cell(l.lender).balances,'ETH',l.repayment);opAdd(c.balances,'AUR',l.collateral);l.status='repaid';this.record('CREDIT_REPAID',c.identity,{loan:l.id});});}
 closeLoan(id){return this.atomic(()=>{const l=opGet(this.op.loans,id);if(l.status==='offered'){if(this.world.s.now<l.offerUntil)this.world._owner(l.borrower);opAdd(this.cell(l.borrower).balances,'AUR',l.collateral);l.status='cancelled';}else if(l.status==='active'&&this.world.s.now>=l.due){opAdd(this.cell(l.lender).balances,'AUR',l.collateral);l.status='defaulted';}else throw Error('No collateral release is available.');this.record('CREDIT_CLOSED',l.borrower,{loan:l.id,status:l.status});});}
 writeOption(underlying,strike,premium,days=14){return this.atomic(()=>{const c=this.labOwner('scrivener');opDays(days,365);underlying=opQ(underlying);strike=opQ(strike);premium=opQ(premium);opTake(c.balances,'AUR',underlying);const o={id:this.op.options.length+1,writer:c.identity,buyer:0,underlying:String(underlying),strike:String(strike),premium:String(premium),expiry:this.world.s.now+days*DAY,status:'offered'};this.op.options.push(o);this.record('OPTION_WRITTEN',c.identity,{option:o.id,expiry:o.expiry,asset:'AUR',amount:o.underlying});return o;});}
 takeOption(id){return this.atomic(()=>{const c=this.labOwner('scrivener'),o=opGet(this.op.options,id);if(o.status!=='offered'||c.identity===o.writer||this.world.s.now>=o.expiry)throw Error('Option not available.');opTake(c.balances,'ETH',o.premium);opAdd(this.cell(o.writer).balances,'ETH',o.premium);o.buyer=c.identity;o.status='active';this.record('OPTION_BOUGHT',c.identity,{option:o.id});});}
 exercise(id){return this.atomic(()=>{const o=opGet(this.op.options,id),c=this.labOwner('scrivener',o.buyer,false);if(o.status!=='active'||this.world.s.now>=o.expiry)throw Error('Exercise window closed.');opTake(c.balances,'ETH',o.strike);opAdd(this.cell(o.writer).balances,'ETH',o.strike);opAdd(c.balances,'AUR',o.underlying);o.status='exercised';this.record('OPTION_EXERCISED',c.identity,{option:o.id});});}
 closeOption(id){return this.atomic(()=>{const o=opGet(this.op.options,id);if(!['offered','active'].includes(o.status))throw Error('Option already closed.');if(this.world.s.now<o.expiry){if(o.status!=='offered')throw Error('Accepted cover remains locked until expiry.');this.world._owner(o.writer);}opAdd(this.cell(o.writer).balances,'AUR',o.underlying);o.status='closed';this.record('OPTION_CLOSED',o.writer,{option:o.id});});}
 registerApplication(title,hash,bytes){const a=this.world._owner(this.world.s.selected);if(!/^0x[0-9a-f]{64}$/.test(hash)||!Number.isInteger(bytes)||bytes<1||bytes>4000000)throw Error('Invalid application manifest.');const x={id:this.op.applications.length+1,identity:a.id,title:opText(title,96),hash,bytes,time:this.world.s.now};this.op.applications.push(x);this.record('APPLICATION_COMMITTED',a.id,{application:x.id,hash,bytes});return x;}
 moduleSnapshot(id){id=Number(id);return {version:'1.6',gifts:this.extra.gifts.filter(g=>g.donor===id||g.recipient.kind==='artifact'&&g.recipient.id===id),installations:this.op.installations.filter(x=>x.identity===id),grants:this.op.grants.filter(x=>x.identity===id),commissions:this.op.commissions.filter(x=>x.identity===id),collectibles:this.op.collectibles.filter(x=>x.holder===id),venues:this.op.venues.filter(x=>x.identity===id),cells:this.op.cells.filter(x=>x.identity===id),loans:this.op.loans.filter(x=>x.borrower===id||x.lender===id),options:this.op.options.filter(x=>x.writer===id||x.buyer===id),applications:this.op.applications.filter(x=>x.identity===id)};}
 _bindListing(l){const moduleRoot=fingerprint(this.moduleSnapshot(l.identity));const base=fingerprint({domain:'LOCAL_ESTATE_COVENANT_1_4',id:l.id,identity:l.identity,seller:l.seller,price:l.price,expires:l.expires,status:'listed',inventory:l.inventory});const manifest=fingerprint({domain:'IDFBI_OPERATING_COVENANT_1_6',base,moduleRoot});this.op.covenants[l.id]={moduleRoot,manifest,base};l.manifest=manifest;this.record('MANIFEST_BOUND',l.identity,{listing:l.id,moduleRoot,manifest},l.seller);}
 refreshListing(id){return this.atomic(()=>{const l=opGet(this.world.s.listings,id);if(l.status!=='listed'||l.seller!==this.world.s.actor||this.world.identity(l.identity).owner!=='escrow')throw Error('Only the listing seller may refresh declared contents.');l.inventory=this.world._inventorySnapshot(l.identity);this._bindListing(l);});}
 ledger(id=this.world.s.selected){const a=this.world.identity(id);return {identity:a.id,owner:a.owner,epoch:a.epoch,free:structuredClone(a.balances),projected:this.project(a.id,this.world.s.now),modules:structuredClone(this.moduleSnapshot(a.id)),activeGrants:this.op.grants.filter(g=>g.identity===a.id).map(g=>({id:g.id,status:this.grantStatus(g),remaining:String(BigInt(g.total)-BigInt(g.spent))})),note:'No aggregate valuation. Each asset has its own units. Laboratory collateral and committed funds are not free balances.'};}
 export(){const b={schema:'idfbi/operating/1.6',instruments:super.export(),operating:structuredClone(this.op)};return {...b,checksum:fingerprint(b)};}
 static restore(x){if(x?.schema==='idfbi/instruments/1.5'){const e=InstrumentEngine.restore(x);Object.setPrototypeOf(e,OperatingEngine.prototype);e.op=opFresh();e._attach();return e;}if(!x||x.schema!=='idfbi/operating/1.6')throw Error('Unsupported operating archive.');const {checksum,...b}=x;if(Object.keys(x).sort().join(',')!=='checksum,instruments,operating,schema'||fingerprint(b)!==checksum)throw Error('Operating archive checksum failed.');const e=InstrumentEngine.restore(x.instruments);Object.setPrototypeOf(e,OperatingEngine.prototype);e.op=structuredClone(x.operating);validateOperating(e);e._attach();return e;}
}
function validateOperating(e){const o=e.op,w=e.world,fail=()=>{throw Error('Unsafe or inconsistent operating archive.');};if(!o||o.schema!=='idfbi/operating-state/1.6')fail();const expected=Object.keys(opFresh()).sort().join(',');if(Object.keys(o).sort().join(',')!==expected)fail();
 const arrs=['editions','installations','grants','commissions','collectibles','venues','cells','loans','options','applications'];for(const k of arrs){if(!Array.isArray(o[k])||o[k].length>512)fail();for(let i=0;i<o[k].length;i++)if(o[k][i].id!==i+1)fail();}
 const person=v=>{if(!['you','guest','archivist','weaver'].includes(v))fail();};const identity=v=>{w.identity(v);};const time=v=>{if(!Number.isSafeInteger(v)||v<0)fail();};const asset=v=>{if(!/^[A-Z][A-Z0-9]{1,11}$/.test(v))fail();};
 const quantities=b=>{if(!b||typeof b!=='object'||Array.isArray(b)||Object.keys(b).length>512)fail();for(const[k,v]of Object.entries(b)){asset(k);opN(v);}};
 for(const x of o.editions){identity(x.identity);person(x.author);time(x.time);time(x.epoch);opText(x.title,96);if(x.parent>=x.id||x.parent<0)fail();const recipe=e.normalize(x.recipe);if(fingerprint(recipe)!==fingerprint(x.recipe)||x.contentHash!==fingerprint({schema:'idfbi/typed-edition/1.6',recipe}))fail();const{editionHash,receipt,contentHash,...body}=x;if(editionHash!==fingerprint({...body,contentHash}))fail();const ev=w.s.events.find(z=>z.seq===receipt);if(ev?.kind!=='EDITION_PUBLISHED'||ev.data.edition!==x.id||ev.data.contentHash!==contentHash)fail();}
 for(const x of o.installations){identity(x.identity);if(e.edition(x.edition).contentHash!==x.contentHash)fail();time(x.readyAt);}
 for(const x of o.grants){identity(x.identity);person(x.caller);time(x.epoch);time(x.expires);if(e.edition(x.edition).editionHash!==x.editionHash||typeof x.revoked!=='boolean')fail();opQ(x.perCall);opQ(x.total);opN(x.spent);if(BigInt(x.spent)>BigInt(x.total)||BigInt(x.perCall)>BigInt(x.total)||!Number.isInteger(x.calls)||x.calls<1||x.calls>100||!Number.isInteger(x.used)||x.used<0||x.used>x.calls)fail();if(BigInt(x.spent)!==BigInt(e.edition(x.edition).recipe.amount)*BigInt(x.used))fail();}
 for(const x of o.commissions){identity(x.identity);person(x.sponsor);person(x.worker);person(x.reviewer);asset(x.asset);opQ(x.amount);opText(x.title);time(x.deadline);time(x.reviewEnds);if(x.reviewEnds!==x.deadline+3*DAY||!['offered','accepted','submitted','paid','refunded'].includes(x.status))fail();w.room(x.room);if(['submitted','paid'].includes(x.status)&&e.edition(x.edition).author!==x.worker)fail();}
 for(const c of o.cells){identity(c.identity);time(c.enabledEpoch);quantities(c.balances);if(!Array.isArray(c.enabled)||c.enabled.some(k=>!LAB_MODULES.includes(k))||new Set(c.enabled).size!==c.enabled.length)fail();if(c.strategy.asset!=='AUR')fail();opN(c.strategy.assets);opN(c.strategy.shares);for(const k of ['supply','ETH','AUR'])opN(c.basket[k]);if(BigInt(c.basket.ETH)<ceilRatio(c.basket.supply,wei('0.0001'),E18)||BigInt(c.basket.AUR)<ceilRatio(c.basket.supply,wei('10'),E18))fail();if(c.strip){for(const k of ['assets','pairs','initial'])opN(c.strip[k]);if(c.strip.asset!=='AUR'||BigInt(c.strip.assets)>BigInt(c.strip.initial)||BigInt(c.strip.pairs)>BigInt(c.strip.initial))fail();time(c.strip.maturity);}}
 if(new Set(o.cells.map(c=>c.identity)).size!==o.cells.length)fail();
 for(const x of o.collectibles){identity(x.holder);e.edition(x.edition);if(!Number.isInteger(x.venue)||x.venue<0||x.venue>o.venues.length)fail();}
 for(const x of o.venues){identity(x.identity);opQ(x.price);opN(x.reserve);time(x.bondUntil);opGet(o.collectibles,x.collectible);if(!['open','sold','closed'].includes(x.status))fail();}
 for(const x of o.loans){identity(x.borrower);if(x.lender)identity(x.lender);for(const k of ['collateral','principal','repayment'])opQ(x[k]);if(BigInt(x.repayment)<BigInt(x.principal)||!['offered','active','cancelled','defaulted','repaid'].includes(x.status))fail();opDays(x.days,365);time(x.offerUntil);time(x.due);if(['active','defaulted','repaid'].includes(x.status)&&(!x.lender||x.lender===x.borrower||x.due===0))fail();e.cell(x.borrower);if(x.lender)e.cell(x.lender);}
 for(const x of o.options){identity(x.writer);if(x.buyer)identity(x.buyer);for(const k of ['underlying','strike','premium'])opQ(x[k]);time(x.expiry);if(!['offered','active','exercised','closed'].includes(x.status)||['active','exercised'].includes(x.status)&&(!x.buyer||x.buyer===x.writer))fail();e.cell(x.writer);if(x.buyer)e.cell(x.buyer);}
 for(const x of o.applications){identity(x.identity);opText(x.title,96);if(!/^0x[0-9a-f]{64}$/.test(x.hash)||!Number.isInteger(x.bytes)||x.bytes<1||x.bytes>4000000)fail();time(x.time);}
 for(const [id,c]of Object.entries(o.covenants)){const l=opGet(w.s.listings,id);if(!/^0x[0-9a-f]{64}$/.test(c.moduleRoot)||c.manifest!==fingerprint({domain:'IDFBI_OPERATING_COVENANT_1_6',base:c.base,moduleRoot:c.moduleRoot})||c.manifest!==l.manifest)fail();}quantities(o.lossSink);
}
