"""Actual release HTML, browser interactions, no wallet or network service.
Managed Chromium disallows file navigation. set_content inspects the exact shipped
HTML without changing browser policies. Web Storage below is a test adapter.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image
import json,hashlib,time,traceback
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'reports/v1.4';OUT.mkdir(exist_ok=True)
HTML=(ROOT/'preview.html').read_text();checks=[];errors=[];requests=[]
def check(name,ok):
 checks.append({'name':name,'passed':bool(ok)})
 print(('PASS ' if ok else 'FAIL ')+name,flush=True)
 if not ok:raise AssertionError(name)
def mount(page,saved=None):
 page.evaluate('''saved=>{window.__store=saved||{};const make=s=>({getItem:k=>Object.hasOwn(s,k)?s[k]:null,setItem:(k,v)=>s[k]=String(v),removeItem:k=>delete s[k],clear:()=>Object.keys(s).forEach(k=>delete s[k])});Object.defineProperty(window,'localStorage',{value:make(__store),configurable:true});Object.defineProperty(window,'sessionStorage',{value:make({}),configurable:true});window.__wallet=[];window.ethereum={on(){},removeListener(){},request:r=>{__wallet.push(r);return Promise.reject(Error('NO TEST WALLET'));}};window.__audio=0;const Audio=window.AudioContext;if(Audio)window.AudioContext=class extends Audio{constructor(...a){super(...a);__audio++}};}''',saved or {})
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url))
 page.set_content(HTML,wait_until='domcontentloaded')
 page.wait_for_function("window.__kingdom && document.querySelector('#kingdom').dataset.ready==='true'",timeout=20000)
 page.wait_for_timeout(180)
 return page
def nav(page,v):page.click(f'#k-tabs [data-view="{v}"]')
def confirm(page):page.click('#k-dialog [data-k="confirm"]');page.wait_for_timeout(50)
def act(page,action,id=None):page.click(f'#kingdom [data-k="{action}"]'+(f'[data-id="{id}"]' if id is not None else ''))
def close(page):page.click('#k-dialog-close')
def s(page,expr='s'):return page.evaluate('__kingdom.model().'+expr)
def fill(page,form,name,value):page.locator(f'#{form} [name="{name}"]').fill(str(value))
def submit(page,form):page.locator('#'+form+' button[type="submit"], #'+form+' button:not([type])').last.click()
report={'release':'1.4.0','previewSha256':hashlib.sha256(HTML.encode()).hexdigest(),'scope':'Actual shipped HTML via set_content. Injected in-memory Web Storage. No live wallet, Solidity, EVM or public-chain validation.'}
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 ctx=browser.new_context(viewport={'width':1440,'height':950},device_scale_factor=1,reduced_motion='reduce',accept_downloads=True)
 ctx.set_default_timeout(10000);page=mount(ctx.new_page())
 try:
  check('standalone new interface boots visibly',page.locator('#kingdom').is_visible())
  check('initial view is Sanctum',page.evaluate('__kingdom.view()')=='sanctum')
  check('reduced motion is respected',not page.evaluate('__kingdom.scene.motion'))
  check('no initial wallet call or autoplay',page.evaluate('__wallet.length===0&&__audio===0'))
  check('scene has computed facets',page.evaluate('__kingdom.scene.faces.length')>500)
  page.screenshot(path=str(OUT/'sanctum-desktop.png'))
  check('rendered screenshot has broad pixel variation',len(Image.open(OUT/'sanctum-desktop.png').getcolors(1000000) or [])>1000)
  head0=s(page,'export().checksum');page.locator('#k-time').fill('180')
  check('timeglass does not change local data or receipt head',s(page,'export().checksum')==head0)
  nav(page,'vault');check('future projection is visibly labeled', '+180 days' in page.locator('#k-locks').inner_text())
  check('future projection does not enable early release',page.locator('#k-locks [data-k="release"]').first.is_disabled())
  page.locator('#k-time').fill('0');nav(page,'launch')
  fill(page,'k-launch-form','name','Phoenix Test Garden');fill(page,'k-launch-form','symbol','PHNX');fill(page,'k-launch-form','hours','1');submit(page,'k-launch-form')
  check('launch requires a separate review',page.locator('#k-dialog').is_visible() and len(s(page)['sales'])==0)
  check('allocation is shown in review',all(x in page.locator('#k-dialog').inner_text() for x in ['500,000','400,000','100,000']))
  confirm(page);check('confirmed local launch creates a sale',len(s(page)['sales'])==1)
  check('launch creates a connected commons',any(r['name']=='PHNX commons' for r in s(page)['rooms']))
  check('no pool appears before settlement',not any(p['asset']=='PHNX' for p in s(page)['pools']))
  act(page,'contribute',1);submit(page,'k-contribute-form');confirm(page)
  check('contribution debits the NFT local treasury',s(page)['sales'][0]['raised']=='1000000000000000000' and s(page)['identities'][0]['balances']['ETH']=='7000000000000000000')
  act(page,'close-sale-time',1);confirm(page);act(page,'settle',1);confirm(page)
  check('settlement creates the market',any(p['asset']=='PHNX' for p in s(page)['pools']))
  check('settlement creates founder and treasury schedules',len(s(page)['locks'])==4)
  act(page,'claim',1);confirm(page)
  check('claim credits the actual pro-rata model allocation',s(page)['identities'][0]['balances']['PHNX']=='500000000000000000000000')
  before=s(page)['identities'][0]['balances']['PHNX'];nav(page,'swap')
  page.select_option('#k-swap-out','PHNX');fill(page,'k-swap-form','amount','0.05');page.check('#k-swap-lock');submit(page,'k-swap-form')
  check('swap review shows minimum and atomic vault destination','Minimum received' in page.locator('#k-dialog').inner_text() and 'Artifact vault / 30 days' in page.locator('#k-dialog').inner_text())
  confirm(page);check('swap-and-lock creates a claim, not a spendable token credit',len(s(page)['locks'])==5 and s(page)['identities'][0]['balances']['PHNX']==before)
  check('model has a structured SWAPPED receipt',s(page)['events'][-1]['kind']=='SWAPPED' and s(page)['events'][-1]['data']['lock']!=0)
  nav(page,'vault');fill(page,'k-vault-form','amount','0.15');submit(page,'k-vault-form');confirm(page)
  check('explicit vault deposit creates a sixth schedule',len(s(page)['locks'])==6)
  nav(page,'market');page.wait_for_timeout(200);page.screenshot(path=str(OUT/'marketplace-desktop.png'))
  check('three complete estate cards render',page.locator('.k-estate').count()==3)
  old_lock=s(page)['locks'][1].copy();act(page,'estate',204)
  check('manifest shows actual declared locked and spendable inventory','50,000 AUR' in page.locator('#k-dialog').inner_text() and '1.25' in page.locator('#k-dialog').inner_text())
  act(page,'buy',1);confirm(page)
  check('whole-estate acquisition changes custody',s(page)['identities'][1]['owner']=='you')
  check('acquisition selects the purchased artifact',s(page)['selected']==204)
  check('purchase transfers control without accelerating locks',s(page)['locks'][1]==old_lock)
  check('rehearsal payment is actually debited',s(page)['wallets']['you']=='18200000000000000000')
  nav(page,'world');fill(page,'k-message-form','body','I am the current custodian, not the next one.');submit(page,'k-message-form')
  authored=s(page)['messages'][-1].copy();check('message captures identity and custodian-at-time',authored['identity']==204 and authored['custodian']=='you')
  nav(page,'market');act(page,'list');page.select_option('#k-list-form [name="identity"]','204');fill(page,'k-list-form','price','2');submit(page,'k-list-form');confirm(page)
  check('listing places the whole NFT in escrow',s(page)['identities'][1]['owner']=='escrow')
  check('escrow advances the custody epoch',s(page)['identities'][1]['epoch']>authored['epoch'])
  page.select_option('#k-persona','guest');act(page,'estate',204);act(page,'buy',3);confirm(page)
  check('other persona can acquire the estate',s(page)['identities'][1]['owner']=='guest')
  check('earlier authorship survives the sale unchanged',s(page)['messages'][-1]==authored)
  page.select_option('#k-persona','you');nav(page,'swap')
  check('old owner cannot operate the sold artifact via its form',page.locator('#k-swap-form>.k-primary').is_disabled())
  page.select_option('#k-id-select','1');nav(page,'world');act(page,'open-room',2);act(page,'room-settings',2);act(page,'invite',2)
  check('invitation does not silently add an accepted member',not s(page)['rooms'][1]['members']['guest']['accepted'])
  close(page);page.select_option('#k-persona','guest');before_count=len(s(page)['messages']);fill(page,'k-message-form','body','This must not post before acceptance.');submit(page,'k-message-form')
  check('unaccepted member cannot post in gated room',len(s(page)['messages'])==before_count)
  act(page,'room-settings',2);act(page,'accept',2);close(page)
  fill(page,'k-message-form','body','Invitation accepted. My voice is still mine.');submit(page,'k-message-form')
  check('accepted guest can post as their own voice',len(s(page)['messages'])==before_count+1 and s(page)['messages'][-1]['identity']==0)
  page.select_option('#k-persona','you');act(page,'room-settings',2);act(page,'remove-member',2);close(page)
  check('room removal keeps message history intact',len(s(page)['messages'])==before_count+1)
  page.select_option('#k-persona','guest');fill(page,'k-message-form','body','This must not post after removal.');submit(page,'k-message-form')
  check('removed member cannot create another room post',len(s(page)['messages'])==before_count+1)
  page.select_option('#k-persona','you');act(page,'open-room',1)
  n=len(s(page)['events']);fill(page,'k-message-form','body','<img src=x onerror=alert(1)> I LAUNCHED a coin');submit(page,'k-message-form')
  check('chat renders markup as literal text',page.locator('#kingdom img').count()==0 and '<img src=x' in page.locator('.k-message-body').last.inner_text())
  check('typed launch claim produces SPOKE, not LAUNCHED',s(page)['events'][-1]['kind']=='SPOKE' and len(s(page)['events'])==n+1)
  last_id=s(page)['messages'][-1]['id'];page.locator(f'[data-k="reaction"][data-id="{last_id}"][data-emoji="♡"]').click()
  check('reaction is stored by participant',s(page)['messages'][-1]['reactions']['♡']==['you'])
  page.locator(f'[data-k="reaction"][data-id="{last_id}"][data-emoji="♡"]').click();check('reaction toggles without duplicating participants',s(page)['messages'][-1]['reactions']['♡']==[])
  act(page,'filters');page.locator('#k-dialog [data-k="profile"][data-user="weaver"]').click();act(page,'block');close(page)
  check('personal removal hides only that participant in this view',page.locator('#k-messages [data-k="profile"][data-user="weaver"]').count()==0)
  check('personal removal does not destroy public example messages',any(m['actor']=='weaver' for m in s(page)['messages']))
  act(page,'create-room');fill(page,'k-create-room-form','name','The Glass Observatory');page.check('#k-create-room-form [name="gated"]');submit(page,'k-create-room-form')
  rid=s(page)['rooms'][-1]['id'];check('custom room is created and opened','The Glass Observatory' in page.locator('.k-channel-head').inner_text())
  act(page,'room-settings',rid);fill(page,'k-room-form','topic','A custom room whose rules are explicit.');fill(page,'k-room-form','slow','0');page.uncheck('#k-room-form [name="gated"]');submit(page,'k-room-form')
  check('room topic, slow mode and access are customizable',s(page)['rooms'][-1]['slow']==0 and not s(page)['rooms'][-1]['gated'])
  close(page);act(page,'open-room',1);page.screenshot(path=str(OUT/'world-desktop.png'))
  act(page,'receipts') if page.locator('[data-k="receipts"]').count() else page.evaluate('__kingdom.boundary()')
  # Export through visible UI; archive bytes validate in a separate page below.
  if page.locator('#k-dialog [data-k="export"]').count()==0:page.evaluate('__kingdom.boundary()')
  with page.expect_download() as pending:page.locator('#k-dialog [data-k="export"]').click()
  pending.value.save_as(str(OUT/'browser-rehearsal-export.json'))
  exported=json.loads((OUT/'browser-rehearsal-export.json').read_text());check('downloaded rehearsal is valid JSON with exact head',exported['state']['head']==s(page)['head'])
  close(page);saved=page.evaluate('__store');other=mount(ctx.new_page(),saved)
  check('saved state restores through a Web Storage adapter',s(other)['head']==s(page)['head'] and s(other)['identities'][1]['owner']=='guest');other.close()
  bad=mount(ctx.new_page(),{'idfbi.kingdom.rehearsal.1.4':'{broken'})
  check('corrupt save is not overwritten',bad.evaluate('__store["idfbi.kingdom.rehearsal.1.4"]')=='{broken')
  check('corrupt-save warning is visible',bad.locator('#k-storage-warning').is_visible());bad.close()
  nav(page,'sanctum');page.click('#k-motion');page.wait_for_timeout(300);tm=page.evaluate('__kingdom.scene.time');page.wait_for_timeout(250)
  check('opt-in motion advances the procedural scene',page.evaluate('__kingdom.scene.time')>tm)
  page.click('#k-motion');tm=page.evaluate('__kingdom.scene.time');page.wait_for_timeout(150)
  check('motion pause freezes autonomous scene time',page.evaluate('__kingdom.scene.time')==tm)
  original_head=page.evaluate('window.__idfbi?.state().root');act(page,'original')
  check('original organism remains accessible',not page.locator('#kingdom').is_visible() and page.locator('#k-entry').is_visible())
  page.click('#k-entry');check('returning preserves original organism state',page.evaluate('window.__idfbi?.state().root')==original_head)
  check('no wallet RPC method was requested in any new flow',page.evaluate('__wallet.length')==0)
  check('sound remains off unless explicitly requested',page.evaluate('__audio')==0)
  mobile_ctx=browser.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True,reduced_motion='reduce');mobile=mount(mobile_ctx.new_page())
  check('mobile scene respects reduced motion',not mobile.evaluate('__kingdom.scene.motion'))
  check('mobile layout fits viewport width',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  mobile.screenshot(path=str(OUT/'sanctum-mobile.png'))
  nav(mobile,'market');check('mobile marketplace cards remain reachable',mobile.locator('.k-estate').first.is_visible());act(mobile,'estate',1)
  check('mobile estate manifest fits viewport',mobile.locator('#k-dialog').bounding_box()['width']<=390);close(mobile)
  nav(mobile,'world');check('mobile World composer remains visible',mobile.locator('#k-message-form textarea').is_visible())
  mobile.screenshot(path=str(OUT/'world-mobile.png'))
  act(mobile,'persona');act(mobile,'set-persona');check('mobile persona switch has a visible route',s(mobile)['actor']=='you')
  check('no HTTP or socket requests from the artifact',not any(u.startswith(('http:','https:','ws:','wss:')) for u in requests))
  check('no unhandled browser exceptions',not errors)
  report.update({'browser':browser.version,'passed':len(checks),'failed':0,'checks':checks,'pageErrors':errors,'requestsObserved':requests,'storage':'test adapter','fileNavigation':'not tested: managed browser policy blocks file:// navigation','screenshots':'actual browser capture; not concept art','solidity':'not executed'})
 except Exception as e:
  report.update({'browser':browser.version,'passed':sum(c['passed'] for c in checks),'failed':1,'checks':checks,'pageErrors':errors,'exception':traceback.format_exc()})
  page.screenshot(path=str(OUT/'browser-failure.png'))
  raise
 finally:
  (OUT/'browser-results.json').write_text(json.dumps(report,indent=2));browser.close()
print('TOTAL',len(checks),'passed',flush=True)
