import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ganache from 'ganache';
import {BrowserProvider,ContractFactory,Contract,getCreateAddress,zeroPadValue,parseEther,AbiCoder,keccak256,ZeroAddress} from 'ethers';
import {inspectLane,bridgePlan,deliveryRecord,bridgeOptions,verifyCrosschainReceipt,bridgeDeploymentPlan,recipientDeliveries,prepareLaneDeployment} from '../../web/crosschain/client.mjs';
import {compileBridge} from '../../packages/crosschain/compile.mjs';
const artifacts=compileBridge({fixtures:true}).contracts;
const deploy=async(name,signer,args=[])=>{const a=artifacts[name],c=await new ContractFactory(a.abi,'0x'+a.evm.bytecode.object,signer).deploy(...args,{gasLimit:15000000});await c.waitForDeployment();return c;};
const sent=async tx=>await (await tx).wait();
const b32=a=>zeroPadValue(a,32);

test('official OFT and EndpointV2 on two independent chains: debit, authenticated delivery, lock, retry, refunds and replay exclusion',async t=>{
 const rawA=ganache.provider({logging:{quiet:true},chain:{chainId:31001,hardfork:'shanghai'},miner:{blockGasLimit:30000000},wallet:{deterministic:true}}),rawB=ganache.provider({logging:{quiet:true},chain:{chainId:31002,hardfork:'shanghai'},miner:{blockGasLimit:30000000},wallet:{deterministic:true}});
 const a=new BrowserProvider(rawA,undefined,{cacheTimeout:-1}),b=new BrowserProvider(rawB,undefined,{cacheTimeout:-1});
 a.pollingInterval=b.pollingInterval=10;
 t.after(async()=>{await a.destroy();await b.destroy();await rawA.disconnect();await rawB.disconnect();});
 const alice=await a.getSigner(0),bob=await b.getSigner(1),operatorB=await b.getSigner(0),aliceAddress=await alice.getAddress(),bobAddress=await bob.getAddress();
 const endpointA=await deploy('EndpointV2',alice,[30101,aliceAddress]),endpointB=await deploy('EndpointV2',operatorB,[30184,await operatorB.getAddress()]);
 const libA=await deploy('SimpleMessageLib',alice,[await endpointA.getAddress(),ZeroAddress]),libB=await deploy('SimpleMessageLib',operatorB,[await endpointB.getAddress(),ZeroAddress]);
 for(const [endpoint,lib,remote,owner] of [[endpointA,libA,30184,aliceAddress],[endpointB,libB,30101,await operatorB.getAddress()]]){
  await sent(endpoint.registerLibrary(await lib.getAddress()));await sent(endpoint.setDefaultSendLibrary(remote,await lib.getAddress()));await sent(endpoint.setDefaultReceiveLibrary(remote,await lib.getAddress(),0));await sent(lib.setWhitelistCaller(owner));
 }
 const oftA=await deploy('FixtureOFT',alice,[await endpointA.getAddress()]),oftB=await deploy('FixtureOFT',operatorB,[await endpointB.getAddress()]);
 await sent(oftA.setPeer(30184,b32(await oftB.getAddress())));await sent(oftB.setPeer(30101,b32(await oftA.getAddress())));
 const guiSetup=await prepareLaneDeployment(a,b,{sourceChainId:31001,destinationChainId:31002,sourceDeployer:aliceAddress,destinationDeployer:await operatorB.getAddress(),sourceOFT:await oftA.getAddress(),destinationOFT:await oftB.getAddress()});
 assert.equal(guiSetup.source.meta.deployer,aliceAddress);assert.equal(guiSetup.source.meta.expectedImmutables.composer,guiSetup.composerAddress);assert.equal(guiSetup.destination.meta.expectedImmutables.sourceRouter,b32(guiSetup.sourceAddress));
 assert.equal(guiSetup.destination.meta.expectedImmutables.timeVault,ZeroAddress);assert.equal(guiSetup.source.request.nonce,await a.getTransactionCount(aliceAddress,'pending'));
 const ledger=await deploy('BridgeLedgerFixture',operatorB),vault=await deploy('TimeVault',operatorB,[await ledger.getAddress()]);
 const predictedComposer=getCreateAddress({from:await operatorB.getAddress(),nonce:await b.getTransactionCount(await operatorB.getAddress())});
 const source=await deploy('AnimaOFTSource',alice,[await oftA.getAddress(),30184,predictedComposer,b32(await oftB.getAddress())]);
 const composer=await deploy('AnimaOFTComposer',operatorB,[await endpointB.getAddress(),await oftB.getAddress(),30101,b32(await source.getAddress()),b32(await oftA.getAddress()),await vault.getAddress()]);
 assert.equal(await composer.getAddress(),predictedComposer);
 const deploymentPlan=await bridgeDeploymentPlan('AnimaOFTSource',[await oftA.getAddress(),30184,predictedComposer,b32(await oftB.getAddress())],{chainId:31001,sender:aliceAddress,nonce:source.deploymentTransaction().nonce});
 const setupRecord={...deploymentPlan,final:true,chainId:31001};await verifyCrosschainReceipt(a,setupRecord,await a.getTransactionReceipt(source.deploymentTransaction().hash));assert.equal(setupRecord.contractAddress,await source.getAddress());
 await assert.rejects(verifyCrosschainReceipt(a,{...setupRecord,meta:{...setupRecord.meta,expectedImmutables:{...setupRecord.meta.expectedImmutables,destinationEid:'30110'}}},await a.getTransactionReceipt(source.deploymentTransaction().hash)),/immutable differs/);
 const decoder=await deploy('PacketDecoder',operatorB);
 const lane=await inspectLane(a,{sourceAddress:await source.getAddress(),destinationProvider:b,destinationChainId:31002});
 assert.equal(lane.destinationChain,'31002');
 const browserPlan=await bridgePlan(lane,{amount:'10',minimum:'10',recipient:bobAddress});
 assert.equal(browserPlan.spend[0].amount,parseEther('10'));assert.equal(browserPlan.chainId,31001);assert.match(bridgeOptions(),/^0x0003/);
 await sent(oftA.mint(aliceAddress,parseEther('100')));await sent(oftA.approve(await source.getAddress(),parseEther('100')));
 const deliveries=[];
 async function sendBridge(action,amount=parseEther('10')){
  const receipt=await sent(source.bridge(amount,amount,action,'0x0003',100,{value:100,gasLimit:4000000}));
  const packetEvent=receipt.logs.map(l=>{try{return endpointA.interface.parseLog(l)}catch{return null}}).find(l=>l?.name==='PacketSent');
  const bridgeEvent=receipt.logs.map(l=>{try{return source.interface.parseLog(l)}catch{return null}}).find(l=>l?.name==='BridgeSent');
  const packet=packetEvent.args.encodedPayload ?? packetEvent.args[0];
  const [origin,receiver,guid,message]=await decoder.decode(packet);
  assert.equal(guid,bridgeEvent.args.guid);assert.equal(receiver,await oftB.getAddress());
  await sent(libB.validatePacket(packet));
  const delivered=await sent(endpointB.lzReceive([origin.srcEid,origin.sender,origin.nonce],receiver,guid,message,'0x',{gasLimit:4000000}));
  const composeEvent=delivered.logs.map(l=>{try{return endpointB.interface.parseLog(l)}catch{return null}}).find(l=>l?.name==='ComposeSent');
  const composeMsg=composeEvent.args.message ?? composeEvent.args[4];
  await sent(endpointB.lzCompose(await oftB.getAddress(),await composer.getAddress(),guid,0,composeMsg,'0x',{gasLimit:4000000}));
  deliveries.push({source:receipt.hash,destination:delivered.hash,guid});
  return {guid,origin,receiver,message,composeMsg};
 }
 const now=Number((await b.getBlock('latest')).timestamp);
 const direct={recipient:bobAddress,minimumReceived:parseEther('10'),lockAmount:0,deadline:now+86400,start:0,cliff:0,end:0,linear:false};
 const first=await sendBridge(direct);
 const record=await deliveryRecord(lane,deliveries[0].source,{confirmations:1});assert.equal(record.destinationStatus,2);assert.equal(record.sourceConfirmationTargetMet,true);
 const bridgeRecord={final:true,kind:'crosschain-bridge',chainId:31001,payer:aliceAddress,request:{to:await source.getAddress()},meta:{bridgeSource:await source.getAddress(),composer:await composer.getAddress(),recipient:bobAddress,destinationEid:'30184',amount:String(parseEther('10')),minimum:String(parseEther('10')),destinationChainId:'31002',actionHash:keccak256(AbiCoder.defaultAbiCoder().encode(['tuple(address recipient,uint256 minimumReceived,uint112 lockAmount,uint64 deadline,uint64 start,uint64 cliff,uint64 end,bool linear)'],[direct]))}};
 await verifyCrosschainReceipt(a,bridgeRecord,await a.getTransactionReceipt(deliveries[0].source));assert.equal(bridgeRecord.crosschain.destinationVerified,false);
 await assert.rejects(verifyCrosschainReceipt(a,{...bridgeRecord,meta:{...bridgeRecord.meta,recipient:aliceAddress}},await a.getTransactionReceipt(deliveries[0].source)),/differs/);
 assert.equal((await composer.deliveryAction(first.guid)).recipient,bobAddress);
 assert.equal(await oftA.balanceOf(aliceAddress),parseEther('90'));assert.equal(await oftB.balanceOf(bobAddress),parseEther('10'));assert.equal((await composer.deliveries(first.guid)).status,2n);
 await assert.rejects(composer.lzCompose(await oftB.getAddress(),first.guid,first.composeMsg,ZeroAddress,'0x'));
 await assert.rejects(endpointB.lzCompose(await oftB.getAddress(),await composer.getAddress(),first.guid,0,first.composeMsg,'0x'));
 await assert.rejects(composer.connect(bob).refund(first.guid));
 const locked=await sendBridge({...direct,lockAmount:parseEther('6'),cliff:now+3600,end:now+3600});
 const lock=await vault.lockInfo(1);assert.equal(lock[1],bobAddress);assert.equal(lock[3],parseEther('6'));assert.equal(await oftB.balanceOf(bobAddress),parseEther('14'));assert.equal(await oftB.allowance(await composer.getAddress(),await vault.getAddress()),0n);
 await sent(ledger.setSealed(false));
 const deferredTerms={...direct,lockAmount:parseEther('4'),cliff:now+7200,end:now+7200};
 const deferred=await sendBridge(deferredTerms);assert.equal((await composer.deliveries(deferred.guid)).status,1n);assert.equal(await composer.liability(),parseEther('10'));
 const recovered=await recipientDeliveries(b,{composerAddress:await composer.getAddress(),chainId:31002,recipient:bobAddress,limit:1});assert.equal(recovered.count,'3');assert.equal(recovered.records[0].guid,deferred.guid);assert.equal(recovered.records[0].status,1);assert.equal(recovered.records[0].action.lockAmount,String(parseEther('4')));assert.equal(recovered.nextCursor,'2');
 const earlier=await recipientDeliveries(b,{composerAddress:await composer.getAddress(),chainId:31002,recipient:bobAddress,before:recovered.nextCursor,limit:2});assert.deepEqual(earlier.records.map(r=>r.guid),[locked.guid,first.guid]);assert.equal(earlier.nextCursor,null);
 await assert.rejects(recipientDeliveries(b,{composerAddress:await composer.getAddress(),chainId:31001,recipient:bobAddress}),/another chain/);
 await assert.rejects(composer.retry(deferred.guid,{...deferredTerms,recipient:aliceAddress}));
 await sent(ledger.setSealed(true));await sent(composer.retry(deferred.guid,deferredTerms,{gasLimit:2000000}));assert.equal((await composer.deliveries(deferred.guid)).status,2n);assert.equal(await composer.liability(),0n);
 const insufficient=await sendBridge({...direct,minimumReceived:parseEther('11')});assert.equal((await composer.deliveries(insufficient.guid)).status,1n);
 await assert.rejects(composer.refund(insufficient.guid));const before=await oftB.balanceOf(bobAddress);await sent(composer.connect(bob).refund(insufficient.guid));assert.equal(await oftB.balanceOf(bobAddress),before+parseEther('10'));await assert.rejects(composer.connect(bob).refund(insufficient.guid));
 assert.equal(await composer.liability(),0n);assert.equal(await composer.deliveryCount(bobAddress),4n);
 assert.equal(await oftA.totalSupply()+await oftB.totalSupply(),parseEther('100'),'Two-chain token supply is conserved');
 fs.mkdirSync('reports/crosschain',{recursive:true});fs.writeFileSync('reports/crosschain/local-two-chain.json',JSON.stringify({schema:'anima.crosschain-local/1',sourceChain:31001,destinationChain:31002,protocol:'Official EndpointV2 + OFT',transport:'Official SimpleMessageLib with one whitelisted test relayer. No public DVN validation.',deliveries},null,2)+'\n');
});
