import { formatEther } from '../vendor/ethers.min.js';
import { serviceOrigin } from './service-origin.mjs';
import { normalizeInstrumentRequest, instrumentTerms, validateGeneratedInstrument, approveInstrument, launchGeneratedInstrument, exactProposalGrant } from '../worlds/instruments.mjs';
import { fundGeneratedInstrument, decideGeneratedInstrument, acquireGeneratedInstrument, refundGeneratedInstrument } from '../worlds/commissions.mjs';

export function mountWorldsDesk(container, { wallet, addresses = {}, notify = () => {}, review = () => {}, read = () => null, save = () => {} } = {}) {
  const abort = new AbortController(); let artifact, request, approval, stopPreview;
  container.innerHTML = `<div class="cf-card"><h2>Shared world · separate game</h2><p>Enter a persistent world with other players: explore, gather, forge a blade, defeat wisps, found towns and trade. NFT owner sessions follow the selected collection. Durable command receipts, regional updates and automatic reconnection preserve your progress. One server operator maintains this world; its game coins have no onchain withdrawal.</p><label>World service URL<input id="wx-url" placeholder="http://127.0.0.1:8789"></label><button id="wx-enter">Open shared world</button><p>Operator: <code>node agent/worlds/server.mjs --demo</code> starts an explicit local guest world. A hosted NFT world requires the chain and service settings in the Worlds guide.</p></div>
  <div class="cf-card"><h2>Commission a new instrument</h2><p>Write the program you want. The provider delivers complete HTML and JavaScript; you review the exact source before approving payment, publishing it as a frozen cartridge or running it. A byte fingerprint does not prove code safe.</p><label>Instrument name<input id="wx-name" value="My new instrument"></label><label>What should it do?<textarea id="wx-description" rows="4" placeholder="Describe the tool and the intended behavior."></textarea></label><label><input id="wx-read" type="checkbox"> Permit the provider to request an explicitly selected read-only snapshot</label><label><input id="wx-propose" type="checkbox"> Permit requesting an exact transaction proposal (a separate grant and wallet review are still required)</label><label>Optional public snapshot JSON<textarea id="wx-snapshot" rows="3">null</textarea></label><button id="wx-request">Create and export request</button><p id="wx-terms"></p><label>Verified commissioned-cartridge publisher<input id="wx-publisher" placeholder="0x…"></label><label>Provider wallet<input id="wx-worker" placeholder="0x…"></label><label>Budget in native token<input id="wx-budget" value="0.001"></label><label>Submission days<input id="wx-days" type="number" min="1" max="90" value="7"></label><button id="wx-fund">Review funding transaction</button></div>
  <div class="cf-card"><h2>Review the provider’s exact result</h2><label>Request file (for an existing commission)<input id="wx-request-file" type="file" accept="application/json,.json"></label><label>Generated deliverable JSON<input id="wx-result" type="file" accept="application/json,.json"></label><p id="wx-fingerprint"></p><label>Complete executable source<textarea id="wx-source" rows="12" readonly></textarea></label><details><summary>Exact manifest</summary><pre id="wx-manifest" style="white-space:pre-wrap;overflow-wrap:anywhere"></pre></details><label><input id="wx-reviewed" type="checkbox"> I reviewed this source and its requested capabilities. I understand it is untrusted code.</label><button id="wx-approve">Approve these exact bytes locally</button><label>Commission ID<input id="wx-work" inputmode="numeric" placeholder="1"></label><div class="cf-actions"><button id="wx-pay">Review acceptance and provider payment</button><button id="wx-reject">Review rejection and refund</button><button id="wx-expire">Review expired-work refund</button><button id="wx-acquire">Review frozen cartridge acquisition</button></div><p>Rejected or expired work credits the funding NFT’s escrow balance. Withdrawing that credit remains a separate transaction in the Work desk.</p></div>
  <div class="cf-card"><h2>Run the approved instrument</h2><p>Default execution has no wallet or parent-data bridge. An opaque-origin frame and content policy block ordinary network and resource requests. Browsers can still permit self-navigation or resource exhaustion; do not treat arbitrary HTML as certified safe or give it secrets.</p><details><summary>Optional exact proposal grant</summary><p>This grant allows one exact proposal for five minutes. It does not send it. Ownership or account epoch changes invalidate it.</p><label>Target<input id="wx-target" placeholder="0x…"></label><label>Native value in wei<input id="wx-value" value="0"></label><label>Exact calldata<textarea id="wx-data">0x</textarea></label><label><input id="wx-grant" type="checkbox"> Grant exactly this proposal for this approved source</label></details><button id="wx-preview">Run approved bytes in isolation</button><button id="wx-stop">Stop instrument and revoke local grant</button><div id="wx-frame"></div></div><p id="wx-status" role="status"></p>`;
  const $ = id => container.querySelector('#' + id), message = text => { $('wx-status').textContent = text; notify(text); };
  $('wx-url').value = read('world-service') || 'http://127.0.0.1:8789';
  $('wx-publisher').value = read('generated-publisher') || addresses.CommissionedCartridges || addresses.commissionedCartridges || '';
  const on = (id, action, event = 'click') => $(id).addEventListener(event, async () => { try { await action(); } catch (error) { message(error.message); } }, { signal: abort.signal });
  const download = (name, value) => { const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' })), a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const publisher = () => { const value = $('wx-publisher').value.trim(); save('generated-publisher', value); return value; };
  const reviewed = async plan => { await review(plan); message('Prepared for the existing wallet transaction review.'); };
  const useRequest = value => { request = normalizeInstrumentRequest(value); $('wx-terms').textContent = 'Commission terms: ' + instrumentTerms(request); };
  on('wx-enter', () => { const origin = serviceOrigin($('wx-url').value, 'world'); save('world-service', origin); window.open(origin, '_blank', 'noopener,noreferrer'); });
  on('wx-request', async () => { await wallet.assertOwner(); useRequest({ schema: 'anima.generated-request/1', chainId: String(wallet.chainId), collection: wallet.collection, account: wallet.account, tokenId: String(wallet.tokenId), name: $('wx-name').value, description: $('wx-description').value, snapshot: JSON.parse($('wx-snapshot').value), capabilities: [$('wx-read').checked && 'read-snapshot', $('wx-propose').checked && 'propose-transaction'].filter(Boolean) }); download('instrument-request.json', request); message('Exported the exact public request. Share only this chosen file with your provider.'); });
  on('wx-request-file', async () => { const file = $('wx-request-file').files[0]; if (!file || file.size > 20000) throw Error('Choose a request file under 20 KiB.'); useRequest(JSON.parse(await file.text())); }, 'change');
  on('wx-fund', async () => { if (!request) throw Error('Create or import a request first.'); await reviewed(await fundGeneratedInstrument(wallet, publisher(), request, { worker: $('wx-worker').value, amount: $('wx-budget').value, days: Number($('wx-days').value) })); });
  on('wx-result', async () => { stopPreview?.(); approval = null; $('wx-reviewed').checked = false; const file = $('wx-result').files[0]; if (!file || file.size > 100000) throw Error('Choose a deliverable JSON under 100 KiB.'); const candidate = validateGeneratedInstrument(JSON.parse(await file.text())); if (request && instrumentTerms(request) !== candidate.terms) throw Error('This provider result belongs to a different request.'); artifact = candidate; useRequest(artifact.request); $('wx-source').value = artifact.html; $('wx-manifest').textContent = artifact.manifestJSON; $('wx-fingerprint').textContent = `${artifact.bytes} exact bytes · ${artifact.contentHash} · capability requests: ${artifact.capabilities.join(', ') || 'none'}`; message('Exact commitments validated. Review the source before approving.'); }, 'change');
  on('wx-approve', () => { approval = approveInstrument(artifact, { contentHash: artifact?.contentHash, manifestHash: artifact?.manifestHash, reviewedSource: $('wx-reviewed').checked }); message('These exact bytes are approved locally. Payment, publication and any transaction proposal remain separate actions.'); });
  on('wx-pay', async () => reviewed(await decideGeneratedInstrument(wallet, publisher(), $('wx-work').value, request, artifact, approval, true)));
  on('wx-reject', async () => reviewed(await decideGeneratedInstrument(wallet, publisher(), $('wx-work').value, request, null, null, false)));
  on('wx-expire', async () => reviewed(await refundGeneratedInstrument(wallet, publisher(), $('wx-work').value, request)));
  on('wx-acquire', async () => reviewed(await acquireGeneratedInstrument(wallet, publisher(), $('wx-work').value, artifact, approval)));
  on('wx-preview', async () => {
    stopPreview?.(); let grant;
    if ($('wx-grant').checked) { await wallet.assertOwner(); grant = exactProposalGrant({ contentHash: artifact.contentHash, chainId: String(wallet.chainId), account: wallet.account, epoch: String(await wallet.contract.sessionEpoch()), target: $('wx-target').value, value: $('wx-value').value, data: $('wx-data').value.trim(), expires: Date.now() + 300000 }); }
    stopPreview = launchGeneratedInstrument($('wx-frame'), artifact, approval, { grant, readContext: async () => { await wallet.assertOwner(); return { chainId: String(wallet.chainId), account: wallet.account, epoch: String(await wallet.contract.sessionEpoch()) }; }, onProposal: async exact => { await reviewed(await wallet.prepare({ ...exact, value: formatEther(exact.value) })); return { prepared: true, sent: false }; } }); message('Approved source is running in the isolated frame. It stops after five minutes or when this desk closes.');
  });
  on('wx-stop', () => { stopPreview?.(); message('Instrument stopped. Its local grant is revoked.'); });
  return () => { abort.abort(); stopPreview?.(); container.replaceChildren(); };
}
