import fs from 'node:fs';
import path from 'node:path';
import {keccak256} from '../../node_modules/ethers/lib.esm/index.js';
import {compileBridge} from './compile.mjs';
const {contracts}=compileBridge(),artifacts={};
for(const name of ['AnimaOFTSource','AnimaOFTComposer']){
 const a=contracts[name], immutableGroups=Object.values(a.evm.deployedBytecode.immutableReferences),runtime=a.evm.deployedBytecode.object;
 let normalized=runtime;for(const m of immutableGroups.flat())normalized=normalized.slice(0,m.start*2)+'0'.repeat(m.length*2)+normalized.slice((m.start+m.length)*2);
 artifacts[name]={abi:a.abi,bytecode:'0x'+a.evm.bytecode.object,creationHash:keccak256('0x'+a.evm.bytecode.object),normalizedHash:keccak256('0x'+normalized),immutableGroups,bytes:runtime.length/2};
}
fs.writeFileSync(path.resolve(import.meta.dirname,'../../web/crosschain/artifacts.mjs'),'// Generated by packages/crosschain/build.mjs; Solidity 0.8.30, Shanghai, viaIR, 1000 runs.\nexport const CROSSCHAIN_ARTIFACTS = '+JSON.stringify(artifacts)+';\n');
console.log('Built exact immutable source/composer verification artifacts.');
