import test from 'node:test';import assert from 'node:assert/strict';
import {SpiritField} from '../../web/spirit/field.js';
import {identityVector} from '../../web/confluence/identity.mjs';
import {particleVertex,particleFragment} from '../../web/spirit/shaders.mjs';
const identity=n=>identityVector({seed:'0x'+n.repeat(32)});
function declarations(source){const result=new Map(),precision=source.match(/precision\s+(\w+)\s+float/)[1];for(const m of source.matchAll(/(uniform|varying)\s+(?:(highp|mediump|lowp)\s+)?(float|vec[234])\s+([^;]+);/g))for(const name of m[4].split(','))result.set(m[1]+':'+name.trim(),{precision:m[2]||precision,type:m[3],explicit:!!m[2]});return result;}
function fixture(options={}){
 const config={failLink:false,badFramebuffer:false,noGL:false,...options},draws=[],fills=[],deleted=[];
 const gl={VERTEX_SHADER:1,FRAGMENT_SHADER:2,COMPILE_STATUS:3,LINK_STATUS:4,ARRAY_BUFFER:5,STATIC_DRAW:6,FLOAT:8,BLEND:9,SRC_ALPHA:10,ONE:11,POINTS:13,TRIANGLES:14,FRAMEBUFFER_COMPLETE:99,
 createShader:type=>({type}),shaderSource:(s,source)=>s.source=source,compileShader(){},getShaderParameter:()=>true,
 createProgram:()=>({shaders:[]}),attachShader:(p,s)=>p.shaders.push(s),linkProgram(p){const a=declarations(p.shaders[0].source),b=declarations(p.shaders[1].source);p.linked=!config.failLink&&[...a].every(([k,v])=>!b.has(k)||(b.get(k).precision===v.precision&&b.get(k).type===v.type));},getProgramParameter:p=>p.linked,getProgramInfoLog:()=>'link failed',
 createBuffer:()=>({}),createTexture:()=>({}),createFramebuffer:()=>({}),checkFramebufferStatus:()=>config.badFramebuffer?0:99,
 getUniformLocation:(_p,k)=>k,getAttribLocation:(_p,k)=>['position','destination','salt'].indexOf(k),drawArrays:(mode,_first,count)=>draws.push({mode,count})};
 for(const key of ['bindBuffer','bufferData','bindTexture','texParameteri','texImage2D','bindFramebuffer','framebufferTexture2D','useProgram','uniform1f','uniform2f','uniform3f','uniform4f','uniform1i','enableVertexAttribArray','disableVertexAttribArray','vertexAttribPointer','disable','enable','blendFunc','viewport','activeTexture'])gl[key]=()=>{};
 for(const kind of ['Shader','Buffer','Program','Texture','Framebuffer'])gl['delete'+kind]=x=>deleted.push([kind,x]);
 const context={setTransform(){},fillRect:(...args)=>fills.push(args),createRadialGradient:()=>({addColorStop(){}})};
 class Canvas{constructor(){this.id='cf-field';this.width=300;this.height=150;this.style={};this.listeners=new Map();this.contextType=null;}getContext(type){if(this.contextType&&type!==this.contextType)return null;if(type==='webgl'&&config.noGL)return null;this.contextType=type;return type==='2d'?context:gl;}cloneNode(){const c=new Canvas();c.width=this.width;c.height=this.height;c.style={...this.style};return c;}replaceWith(next){this.replacement=next;}addEventListener(type,fn){this.listeners.set(type,fn);}setPointerCapture(){}dispatch(type,e={}){this.listeners.get(type)?.(e);}}
 return {config,gl,draws,fills,deleted,canvas:new Canvas()};
}
function environment(run){const css=new Map(),values={innerWidth:390,innerHeight:844,devicePixelRatio:1,document:{hidden:false,documentElement:{style:{setProperty:(k,v)=>css.set(k,v)}},body:{classList:{toggle(){}}}},matchMedia:()=>({matches:false}),requestAnimationFrame:()=>1,addEventListener(){},visualViewport:undefined};const previous=Object.fromEntries(Object.keys(values).map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));try{Object.assign(globalThis,values);run(css);}finally{for(const[k,v]of Object.entries(previous))if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];}}
test('all shared particle uniforms and varyings have matching explicit precision',()=>{const a=declarations(particleVertex),b=declarations(particleFragment);for(const[k,v]of a)if(b.has(k)){assert.deepEqual(v,b.get(k),k);assert.equal(v.explicit,true,k);}});
test('volume, composite and two particle passes execute with the expected particle count',()=>environment(()=>{const f=fixture(),field=new SpiritField(f.canvas,identity('13'));field.tick(16);assert.equal(field.gl,f.gl);assert.deepEqual(f.draws.map(x=>x.count),[3,3,16000,16000]);assert.ok(field.bodyWidth*field.bodyHeight<=361000);}));
for(const config of [{badFramebuffer:true},{failLink:true},{noGL:true}])test('renderer initialization recovers on a fresh interactive Canvas: '+JSON.stringify(config),()=>environment(()=>{const f=fixture(config),field=new SpiritField(f.canvas,identity('13'));assert.equal(field.gl,null);assert.notEqual(field.canvas,f.canvas);assert.equal(field.canvas.contextType,'2d');assert.equal(field.canvas.width,390);field.tick(16);assert.ok(f.fills.length>4000);field.canvas.dispatch('wheel',{deltaY:-100,preventDefault(){}});assert.ok(field.zoom>1);assert.ok(field.canvas.listeners.has('pointerdown'));}));
test('framebuffer failure after context restoration resumes the fallback with one listener set',()=>environment(()=>{const f=fixture(),field=new SpiritField(f.canvas,identity('13'));field.canvas.dispatch('webglcontextlost',{preventDefault(){}});field.tick(16);assert.equal(field.frames,0);f.config.badFramebuffer=true;field.canvas.dispatch('webglcontextrestored');assert.equal(field.lost,false);assert.equal(field.gl,null);field.tick(32);assert.equal(field.frames,1);assert.ok(f.fills.length>4000);assert.ok(field.canvas.listeners.has('pointermove'));}));
test('quality resize failure also recovers',()=>environment(()=>{const f=fixture(),field=new SpiritField(f.canvas,identity('13'));f.config.badFramebuffer=true;field.resizeOptics();assert.equal(field.gl,null);field.tick(16);assert.equal(field.frames,1);}));
test('identity and keyboard changes keep input coordinates synchronized with particle coordinates',()=>environment(css=>{globalThis.innerWidth=1440;globalThis.innerHeight=900;const f=fixture(),field=new SpiritField(f.canvas,identity('13'));const old=css.get('--sa-width');field.setIdentity(identity('ee'));assert.notEqual(css.get('--sa-width'),old);assert.equal(css.get('--sa-left'),field.layout.panel.x+'px');globalThis.innerWidth=390;globalThis.innerHeight=844;globalThis.visualViewport={width:390,height:390,scale:1,offsetTop:10};field.resize();assert.equal(field.canvas.height,390);assert.equal(css.get('--sa-top'),field.layout.panel.y+10+'px');assert.equal(css.get('--sa-viewport-bottom'),'444px');assert.ok(field.layout.panel.y+field.layout.panel.height<390);}));
