import { test } from 'node:test';import assert from 'node:assert/strict';
import { restoreState,byteLength,validateBody,escapeHTML,safeHttp,parseTokenId,visiblePosts,catchUp,sampleData,workBrief } from '../src/commons/model.js';
import {makeGeometry,project,STATIONS} from '../src/commons/scene.js';
import {validateConfig,HISTORICAL,CommonsBridge} from '../src/commons/bridge.js';
test('corrupt and mismatched browser storage cannot break launch',()=>{for(const input of ['{',null,'null','[]','{"version":99}'])assert.equal(restoreState(input).version,1)});
test('stored fields are filtered and never interpreted as HTML',()=>{const s=restoreState(JSON.stringify({version:1,joined:[1,'1','1'],flat:'yes',drafts:{'1':'<svg onload=bad()>','__proto__':'ignored'},posts:[{bad:true}]}));assert.deepEqual(s.joined,['1']);assert.equal(s.flat,false);assert.equal(s.posts.length,0);assert.match(escapeHTML(s.drafts['1']),/^&lt;/)});
test('post limits use UTF-8 bytes',()=>{assert.equal(byteLength('🪴'),4);assert.equal(validateBody('🪴'.repeat(256)).length,512);assert.throws(()=>validateBody('🪴'.repeat(257)));assert.throws(()=>validateBody('   '))});
test('HTML is escaped including attribute delimiters',()=>assert.equal(escapeHTML(`<a x="'&">`),'&lt;a x=&quot;&#39;&amp;&quot;&gt;'));
test('external links reject executable or credential-bearing schemes',()=>{assert.equal(safeHttp('javascript:alert(1)'),null);assert.equal(safeHttp('https://a:b@example.com/'),null);assert.equal(safeHttp('https://example.com/'),'https://example.com/')});
test('token IDs never pass through floating point',()=>{const s='123456789012345678901234567890';assert.equal(String(parseTokenId(s)),s);assert.equal(parseTokenId(String(2n**256n-1n)),2n**256n-1n);for(const x of ['-1','0','1.1','1e6',String(2n**256n)])assert.throws(()=>parseTokenId(x))});
test('muted authors do not appear in posts or finite catchup',()=>{const {posts}=sampleData();assert.equal(visiblePosts(posts,{blocked:['sample-imani']}).length,2);assert.ok(catchUp(posts,['1','2','3'],{},['sample-imani']).every(p=>p.author!=='sample-imani'));});
test('catchup is bounded, joined-only, and respects read markers',()=>{const {posts}=sampleData();const many=Array.from({length:30},(_,i)=>({...posts[0],id:String(i),createdAt:i+1}));assert.equal(catchUp(many,['1'],{}).length,5);assert.equal(catchUp(many,['2'],{}).length,0);assert.equal(catchUp(many,['1'],{'1':30}).length,0)});
test('filters separate root conversations and replies',()=>{const {posts}=sampleData();posts.push({...posts[0],id:'reply',parentId:'sample-1'});assert.equal(visiblePosts(posts).length,4);assert.equal(visiblePosts(posts,{rootsOnly:false,query:'sources'}).length,3)});
test('work brief preserves decimal strings and requires honest deadlines',()=>{const b={body:'Sources and disagreements',agentId:'1',amount:'1.25',coverage:'0',deadline:new Date(Date.now()+86400000).toISOString(),reviewHours:'72'};assert.equal(workBrief(b).reviewWindow,259200);assert.equal(workBrief(b).amount,'1.25');for(const patch of [{amount:'1e6'},{coverage:'-1'},{amount:'0'},{reviewHours:'0'},{deadline:'2000-01-01'}])assert.throws(()=>workBrief({...b,...patch}));});
test('actual 3D geometry contains finite triangles, normals and six destinations',()=>{const g=makeGeometry();assert.ok(g.length>10000);assert.equal(g.length%27,0);assert.ok([...g].every(Number.isFinite));for(let i=0;i<g.length;i+=9)assert.ok(Math.abs(Math.hypot(g[i+3],g[i+4],g[i+5])-1)<.00001);assert.equal(new Set(STATIONS.map(s=>s.id)).size,6);});
test('projection maps homogeneous center to screen center',()=>{assert.deepEqual(project([0,0,0],new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]),100,100),[50,50,0])});
test('network configuration disallows mainnet, plain remote HTTP and credentials',()=>{assert.equal(validateConfig(HISTORICAL).chainId,84532);for(const patch of [{chainId:1},{rpc:'http://evil.example'},{rpc:'https://a:b@example.org'},{anima:'not-an-address'}])assert.throws(()=>validateConfig({...HISTORICAL,...patch}));assert.equal(validateConfig({...HISTORICAL,chainId:31337,rpc:'http://127.0.0.1:8545'}).chainId,31337)});
test('bridge has no implicit wallet connection or permission',()=>{const b=new CommonsBridge();assert.equal(b.address,null);assert.equal(b.config,null);assert.throws(()=>b.requireWrite());b.disconnect();assert.equal(b.epoch,1)});
test('fixtures never pretend to be funded live agents',()=>{const d=sampleData();assert.ok(d.posts.every(p=>p.sample));assert.ok(d.posts.every(p=>!('balance'in p)&&!('trust'in p)&&!('paid'in p)))});

test('live pagination starts at the newest twenty entries and goes backward',async()=>{const b=new CommonsBridge();b.config={commons:'0x1'};b.public={getBlockNumber:async()=>123n};const calls=[];b.read=async(_a,_abi,fn,args)=>{calls.push([fn,args]);if(fn==='postCount')return 45n;if(fn==='postsPage')return [[],args[1]+args[2]];throw Error(fn)};assert.equal((await b.posts('1')).next,'25');assert.deepEqual(calls.find(x=>x[0]==='postsPage')[1],[1n,25n,20n]);calls.length=0;assert.equal((await b.posts('1',25n)).next,'5');assert.deepEqual(calls.find(x=>x[0]==='postsPage')[1],[1n,5n,20n]);assert.equal((await b.posts('1',5n)).next,null);await assert.rejects(b.posts('1',99n));});
test('hidden and withdrawn text is excluded from search and catchup',()=>{const {posts}=sampleData();posts[0].hidden=true;posts[1].withdrawn=true;assert.equal(visiblePosts(posts,{circleId:'1'}).length,0);assert.equal(catchUp(posts,['1'],{}).length,0);});

test('stale reviewed transactions fail before any wallet send',async()=>{const b=new CommonsBridge();b.verified=true;b.config={commons:'0x1111111111111111111111111111111111111111',chainId:31337};b.address='0x2222222222222222222222222222222222222222';b.connectedChain=31337;const calls=[];b.provider={request:async({method})=>{calls.push(method);return method==='eth_accounts'?[b.address]:'0x1'}};const plan={epoch:1,address:b.address,contract:b.config.commons,chainId:31337};await assert.rejects(b.commit(plan),/changed/);assert.equal(calls.length,0);plan.epoch=0;await assert.rejects(b.commit(plan),/changed/);assert.ok(!calls.includes('eth_sendTransaction'));});
test('wallet changes during re-simulation cannot send a reviewed plan',async()=>{const b=new CommonsBridge();b.verified=true;b.config={commons:'0x1111111111111111111111111111111111111111',chainId:31337};b.address='0x2222222222222222222222222222222222222222';b.connectedChain=31337;const calls=[];b.provider={request:async({method})=>{calls.push(method);return method==='eth_accounts'?[b.address]:'0x7a69'}};b.public={simulateContract:async()=>{b.epoch++;return {request:{}}}};await assert.rejects(b.commit({epoch:0,address:b.address,contract:b.config.commons,chainId:31337,functionName:'join',args:[1n]}),/during simulation/);assert.ok(!calls.includes('eth_sendTransaction'));});
