import { describe,it } from 'node:test';
import assert from 'node:assert/strict';
import { getAddress,keccak256,toHex,zeroAddress,encodeAbiParameters,parseAbiParameters } from 'viem';
import { deployProtocol,mintAgent,expectRevert,ZERO32 } from './helpers.js';
const RULES='Be specific. Show evidence. Never post secrets.';
const hash=(s:string)=>keccak256(toHex(s));
async function setup(inviteOnly=false,slowMode=0){
 const p=await deployProtocol();const commons=await p.viem.deployContract('AnimaCommons',[p.anima.address,p.escrow.address]);
 await commons.write.createCircle(['The Foundry','Make useful things',RULES,inviteOnly,slowMode],{account:p.alice.account});
 return {...p,commons};
}
async function join(p:Awaited<ReturnType<typeof setup>>,who=p.bob){await p.commons.write.join([1n],{account:who.account});}
async function publish(p:Awaited<ReturnType<typeof setup>>,body='A public question',kind=1,who=p.alice,parent=0n){await p.commons.write.publish([1n,parent,0n,ZERO32,kind,body],{account:who.account});return await p.commons.read.nextPostId()-1n;}

describe('AnimaCommons — people, purpose, and evidence',()=>{
 it('creates a public circle with exact recoverable rules and a non-custodial binding',async()=>{const p=await setup();const c=await p.commons.read.circleOf([1n]);assert.equal(c.rules,RULES);assert.equal(c.rulesHash,hash(RULES));assert.equal(c.members,1);assert.equal(getAddress(c.steward),getAddress(p.alice.account.address));assert.equal(await p.commons.read.isMember([1n,p.alice.account.address]),true);assert.equal(getAddress(await p.commons.read.ANIMA()),getAddress(p.anima.address));});
 it('rejects a mismatched WorkEscrow token binding',async()=>{const p=await setup();await expectRevert(p.viem.deployContract('AnimaCommons',[p.usdc.address,p.escrow.address]),'BadInput');});
 it('rejects zero and non-contract constructor dependencies',async()=>{const p=await setup();await expectRevert(p.viem.deployContract('AnimaCommons',[zeroAddress,p.escrow.address]),'BadInput');});
 it('enforces UTF-8 creation bounds and nonempty rules',async()=>{const p=await setup();for(const args of [['x'.repeat(65),'p',RULES,false,0],['a','p','',false,0],['a','p','x'.repeat(2049),false,0],['a','p',RULES,false,86401]] as const)await expectRevert(p.commons.write.createCircle(args),'BadInput');});
 it('allows open membership once and forbids nonmember writing',async()=>{const p=await setup();await expectRevert(publish(p,'Not a member',0,p.bob),'NotMember');await join(p);await publish(p,'I joined',0,p.bob);await expectRevert(join(p),'BadInput');assert.equal((await p.commons.read.circleOf([1n])).members,2);});
 it('invitation gates writing, never public reading',async()=>{const p=await setup(true);await expectRevert(join(p),'InvitationRequired');await publish(p,'Public even before you join');assert.equal((await p.commons.read.postOf([1n])).body,'Public even before you join');await p.commons.write.invite([1n,p.bob.account.address,true],{account:p.alice.account});await join(p);assert.equal(await p.commons.read.isInvited([1n,p.bob.account.address]),false);});
 it('does not let arbitrary wallets invite or configure',async()=>{const p=await setup();await expectRevert(p.commons.write.invite([1n,p.carol.account.address,true],{account:p.bob.account}),'Unauthorized');await expectRevert(p.commons.write.configureCircle([1n,false,0,false,RULES],{account:p.bob.account}),'Unauthorized');});
 it('ban clears membership and invitations; unban does not rejoin',async()=>{const p=await setup();await join(p);await p.commons.write.ban([1n,p.bob.account.address,true],{account:p.alice.account});assert.equal(await p.commons.read.isMember([1n,p.bob.account.address]),false);await expectRevert(join(p),'CircleUnavailable');await p.commons.write.ban([1n,p.bob.account.address,false],{account:p.alice.account});assert.equal(await p.commons.read.isMember([1n,p.bob.account.address]),false);await join(p);});
 it('a moderator cannot ban the steward or another moderator',async()=>{const p=await setup();await join(p);await join(p,p.carol);for(const w of [p.bob,p.carol])await p.commons.write.setModerator([1n,w.account.address,true],{account:p.alice.account});await expectRevert(p.commons.write.ban([1n,p.alice.account.address,true],{account:p.bob.account}),'Unauthorized');await expectRevert(p.commons.write.ban([1n,p.carol.account.address,true],{account:p.bob.account}),'Unauthorized');});
 it('leaving permanently removes a dormant moderation role',async()=>{const p=await setup();await join(p);await p.commons.write.setModerator([1n,p.bob.account.address,true],{account:p.alice.account});await p.commons.write.leave([1n],{account:p.bob.account});await join(p);assert.equal(await p.commons.read.isModerator([1n,p.bob.account.address]),false);await expectRevert(p.commons.write.invite([1n,p.carol.account.address,true],{account:p.bob.account}),'Unauthorized');});
 it('stewardship is a two-step voluntary transfer',async()=>{const p=await setup();await join(p);await p.commons.write.proposeSteward([1n,p.bob.account.address],{account:p.alice.account});await expectRevert(p.commons.write.acceptSteward([1n],{account:p.carol.account}),'Unauthorized');await p.commons.write.acceptSteward([1n],{account:p.bob.account});assert.equal(getAddress((await p.commons.read.circleOf([1n])).steward),getAddress(p.bob.account.address));await expectRevert(p.commons.write.setModerator([1n,p.alice.account.address,true],{account:p.alice.account}),'Unauthorized');});
 it('leaving or being banned cancels a stewardship nomination',async()=>{const p=await setup();await join(p);await p.commons.write.proposeSteward([1n,p.bob.account.address],{account:p.alice.account});await p.commons.write.leave([1n],{account:p.bob.account});await join(p);await expectRevert(p.commons.write.acceptSteward([1n],{account:p.bob.account}),'Unauthorized');await p.commons.write.proposeSteward([1n,p.bob.account.address],{account:p.alice.account});await p.commons.write.ban([1n,p.bob.account.address,true],{account:p.alice.account});assert.equal((await p.commons.read.circleOf([1n])).pendingSteward,zeroAddress);});
 it('archival stops new joins, posts, and reactions but permits leaving',async()=>{const p=await setup();await join(p);await publish(p);await p.commons.write.configureCircle([1n,false,0,true,RULES],{account:p.alice.account});await expectRevert(publish(p),'CircleUnavailable');await expectRevert(p.commons.write.react([1n,1],{account:p.bob.account}),'CircleUnavailable');await p.commons.write.leave([1n],{account:p.bob.account});});
 it('checks bytes rather than characters and records exact public text',async()=>{const p=await setup();await publish(p,'🪴'.repeat(256));assert.equal((await p.commons.read.postOf([1n])).body,'🪴'.repeat(256));await expectRevert(publish(p,'🪴'.repeat(257)),'BadInput');await expectRevert(publish(p,''),'BadInput');});
 it('requires a reply to reference a visible post in the same circle',async()=>{const p=await setup();await publish(p);await p.commons.write.createCircle(['Other','p',RULES,false,0],{account:p.alice.account});await expectRevert(p.commons.write.publish([2n,1n,0n,ZERO32,0,'cross-circle'],{account:p.alice.account}),'InvalidThread');await p.commons.write.withdraw([1n],{account:p.alice.account});await expectRevert(publish(p,'reply',0,p.alice,1n),'InvalidThread');});
 it('enforces slow mode on both new posts and revisions',async()=>{const p=await setup(false,120);await publish(p);await expectRevert(publish(p),'SlowMode');await expectRevert(p.commons.write.revise([1n,'edited'],{account:p.alice.account}),'SlowMode');await p.networkHelpers.time.increase(121);await p.commons.write.revise([1n,'edited'],{account:p.alice.account});await expectRevert(publish(p),'SlowMode');});
 it('bounded storage pagination returns stable IDs without an indexer',async()=>{const p=await setup();for(let i=0;i<4;i++)await publish(p,`post ${i}`);assert.deepEqual(await p.commons.read.postsPage([1n,0n,2n]),[[1n,2n],2n]);assert.deepEqual(await p.commons.read.postsPage([1n,2n,50n]),[[3n,4n],4n]);assert.deepEqual(await p.commons.read.postsPage([1n,4n,1n]),[[],4n]);await expectRevert(p.commons.read.postsPage([1n,5n,1n]),'BadInput');await expectRevert(p.commons.read.postsPage([1n,0n,51n]),'BadInput');});
 it('personal posts cannot masquerade as fingerprint-authenticated agents',async()=>{const p=await setup();await expectRevert(p.commons.write.publish([1n,0n,0n,hash('fake'),0,'fake'],{account:p.alice.account}),'BadInput');});
 it('agent authorship checks actual controller and pins current state',async()=>{const p=await setup();const id=await mintAgent(p,p.alice.account.address);const fp=await p.anima.read.getStateFingerprint([id]);await p.commons.write.publish([1n,0n,id,fp,0,'Agent-backed post'],{account:p.alice.account});const post=await p.commons.read.postOf([1n]);assert.equal(post.agentState,fp);assert.equal(getAddress(post.agentOwnerAtPublication),getAddress(p.alice.account.address));await join(p);await expectRevert(p.commons.write.publish([1n,0n,id,fp,0,'spoof'],{account:p.bob.account}),'Unauthorized');});
 it('NFT transfer does not transfer human posts, circle roles, or moderation',async()=>{const p=await setup();await join(p);const id=await mintAgent(p,p.alice.account.address);await publish(p,'A human post');await p.anima.write.transferFrom([p.alice.account.address,p.bob.account.address,id],{account:p.alice.account});await expectRevert(p.commons.write.revise([1n,'buyer takeover'],{account:p.bob.account}),'Unauthorized');assert.equal(getAddress((await p.commons.read.circleOf([1n])).steward),getAddress(p.alice.account.address));});
 it('A to B to A does not revive a stale agent-authored draft',async()=>{const p=await setup();const id=await mintAgent(p,p.alice.account.address);const old=await p.anima.read.getStateFingerprint([id]);await p.anima.write.transferFrom([p.alice.account.address,p.bob.account.address,id],{account:p.alice.account});await p.anima.write.transferFrom([p.bob.account.address,p.alice.account.address,id],{account:p.bob.account});await expectRevert(p.commons.write.publish([1n,0n,id,old,0,'stale'],{account:p.alice.account}),'StateChanged');});
 it('a former controller cannot revise a badge after its agent changes state',async()=>{const p=await setup();const id=await mintAgent(p,p.alice.account.address);const fp=await p.anima.read.getStateFingerprint([id]);await p.commons.write.publish([1n,0n,id,fp,0,'before transfer'],{account:p.alice.account});await p.anima.write.transferFrom([p.alice.account.address,p.bob.account.address,id],{account:p.alice.account});await expectRevert(p.commons.write.revise([1n,'after transfer'],{account:p.alice.account}),'StateChanged');});
 it('reactions replace rather than inflate the same wallet count',async()=>{const p=await setup();await publish(p);await p.commons.write.react([1n,1],{account:p.alice.account});await expectRevert(p.commons.write.react([1n,1],{account:p.alice.account}),'BadInput');await p.commons.write.react([1n,2],{account:p.alice.account});assert.equal(await p.commons.read.reactionCount([1n,1]),0n);assert.equal(await p.commons.read.reactionCount([1n,2]),1n);await p.commons.write.react([1n,0],{account:p.alice.account});assert.equal(await p.commons.read.reactionCount([1n,2]),0n);});
 it('only the question author selects a visible direct reply',async()=>{const p=await setup();await join(p);await publish(p);await publish(p,'answer',0,p.bob,1n);await expectRevert(p.commons.write.acceptReply([1n,2n],{account:p.bob.account}),'Unauthorized');await p.commons.write.acceptReply([1n,2n],{account:p.alice.account});assert.equal(await p.commons.read.acceptedReply([1n]),2n);});
 it('hiding content is a tombstone, not a false deletion claim',async()=>{const p=await setup();await publish(p,'durable bytes');await p.commons.write.moderate([1n,true,hash('rule')],{account:p.alice.account});const post=await p.commons.read.postOf([1n]);assert.equal(post.body,'durable bytes');assert.equal(post.hidden,true);await p.commons.write.withdraw([1n],{account:p.alice.account});await p.commons.write.moderate([1n,false,hash('appeal')],{account:p.alice.account});assert.equal((await p.commons.read.postOf([1n])).withdrawn,true);});
 it('author withdrawal still works after ban or archival',async()=>{const p=await setup();await join(p);await publish(p,'my words',0,p.bob);await p.commons.write.ban([1n,p.bob.account.address,true],{account:p.alice.account});await p.commons.write.configureCircle([1n,false,0,true,RULES],{account:p.alice.account});await p.commons.write.withdraw([1n],{account:p.bob.account});assert.equal((await p.commons.read.postOf([1n])).withdrawn,true);});
 it('hash-chain publication commits to chain, module, circle, author and bytes',async()=>{const p=await setup();const body='replayable';await publish(p,body);const leaf=keccak256(encodeAbiParameters(parseAbiParameters('uint8,uint256,uint256,address,uint256,address,bytes32,uint8,bytes32'),[0,1n,0n,p.alice.account.address,0n,zeroAddress,ZERO32,1,hash(body)]));const root=keccak256(encodeAbiParameters(parseAbiParameters('bytes32,uint256,address,uint256,bytes32,bytes32'),[hash('anima.commons.history.v1'),BigInt(await p.publicClient.getChainId()),p.commons.address,1n,ZERO32,leaf]));assert.equal(await p.commons.read.historyRoot([1n]),root);});
 it('job link requires an actual client-matching, exact-body WorkEscrow record',async()=>{const p=await setup();const id=await mintAgent(p,p.bob.account.address);const body='Compare three sources with citations';await publish(p,body,2);await p.usdc.write.mint([p.alice.account.address,10000000n]);await p.usdc.write.approve([p.escrow.address,10000000n],{account:p.alice.account});const now=await p.networkHelpers.time.latest();await p.escrow.write.offerJob([id,1000000n,0n,BigInt(now+86400),3600n,zeroAddress,hash(body),''],{account:p.alice.account});await p.commons.write.attachJob([1n,1n],{account:p.alice.account});assert.equal(await p.commons.read.linkedJob([1n]),1n);assert.equal((await p.escrow.read.jobOf([1n])).state,1);await expectRevert(p.commons.write.revise([1n,'change the promised result'],{account:p.alice.account}),'Unauthorized');});
 it('rejects nonexistent or mismatched work evidence without a paid badge',async()=>{const p=await setup();await publish(p,'a brief',2);await expectRevert(p.commons.write.attachJob([1n,99n],{account:p.alice.account}),'InvalidJob');await p.usdc.write.mint([p.alice.account.address,1000000n]);await p.usdc.write.approve([p.escrow.address,1000000n],{account:p.alice.account});const now=await p.networkHelpers.time.latest();await p.escrow.write.offerJob([1n,1000000n,0n,BigInt(now+86400),3600n,zeroAddress,hash('wrong brief'),''],{account:p.alice.account});await expectRevert(p.commons.write.attachJob([1n,1n],{account:p.alice.account}),'InvalidJob');});
});
