import test from 'node:test';
import assert from 'node:assert/strict';
import {ProtocolsDesk} from '../../../web/launchpad/protocols.mjs';
const A='0x1111111111111111111111111111111111111111',B='0x2222222222222222222222222222222222222222',H='0x'+'ab'.repeat(32);
function desk(){const saved=new Map(),d=new ProtocolsDesk({chain:{chainId:1},storage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)}});return {d,saved};}
test('setup reorg invalidates only matching configured deployment on the affected chain',()=>{const {d,saved}=desk();d.config={'1':{ccaFactory:A},'10':{ccaFactory:B}};assert.equal(d.rollback({kind:'official-setup',final:true,chainId:1,hash:H,meta:{contractName:'ContinuousClearingAuctionFactory',predictedAddress:A}}),true);assert.equal(d.config['1'].ccaFactory,undefined);assert.equal(d.config['10'].ccaFactory,B);assert.ok([...saved.values()].some(x=>JSON.parse(x)['10'].ccaFactory===B));d.config['1'].ccaFactory=B;assert.equal(d.rollback({kind:'official-setup',final:true,chainId:1,hash:H,meta:{contractName:'ContinuousClearingAuctionFactory',predictedAddress:A}}),false);assert.equal(d.config['1'].ccaFactory,B);});
test('launch reorg clears matching snapshot, participant link, migration and success',()=>{const {d}=desk();d.snapshot={chainId:1,auction:A};d.lastLaunch={chainId:1,transactionHash:H,descriptor:{target:A,token:B}};d.lastMigration={kind:'pool',target:B};d.lastMigrationRecord={chainId:1,transactionHash:H,auction:A};d.status='A pool was created';assert.equal(d.rollback({kind:'official-cca-create',final:true,chainId:1,hash:H,meta:{auction:A,token:B}}),true);assert.equal(d.snapshot,null);assert.equal(d.lastLaunch,null);assert.equal(d.lastMigration,null);assert.match(d.status,/no longer canonical/);});
test('same addresses on a different chain and an approval do not erase confirmed work',()=>{const {d}=desk();d.snapshot={chainId:10,auction:A};d.lastLaunch={chainId:10,transactionHash:H,descriptor:{target:A,token:B}};assert.equal(d.rollback({kind:'official-cca-create',final:true,chainId:1,hash:H,meta:{auction:A,token:B}}),false);assert.equal(d.rollback({kind:'official-cca-create',final:false,chainId:10,hash:H,meta:{auction:A,token:B}}),false);assert.ok(d.snapshot);assert.ok(d.lastLaunch);});
test('review actions preserve typed outside-form values across their busy render',async()=>{const {d}=desk();const fields=[{name:'originalHash',value:H},{name:'replacementHash',value:'0x'+'cd'.repeat(32)},{name:'registry',value:A}];d.root={querySelectorAll:()=>fields,querySelector:()=>({value:''})};d.change=()=>{for(const f of fields)f.value='';};await d.act(async()=>{assert.equal(d.input('originalHash'),H);assert.equal(d.input('registry'),A);assert.equal(d.input('replacementHash'),'0x'+'cd'.repeat(32));});assert.equal(d.actionValues,null);});
