import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),base=path.join(root,'integrations/official-launch');
const require=createRequire(path.join(root,'package.json')),{ethers}=require('ethers');
const {OfficialProtocolClient,verifyProtocolReceipt,verifyProtocol,mineProtocolSalt,protocolLogs,linearCCAsteps,ccaPrice,dopplerCloneAddress}=await import(path.join(root,'web/launchpad/protocols-client.mjs'));
const A=n=>JSON.parse(fs.readFileSync(path.join(base,'artifacts',n+'.json'),'utf8'));

test('official CCA and Doppler execute actual creation, trading, settlement, refunds and migration',{timeout:360000},async()=>{
  const port=24773,rpc=`http://127.0.0.1:${port}`,anvil=spawn(process.execPath,[path.join(root,'integrations/console/protocol/v4-hook/node_modules/@foundry-rs/anvil/bin.mjs'),'--host','127.0.0.1','--port',String(port),'--chain-id','31337','--hardfork','cancun','--silent'],{stdio:['ignore','ignore','pipe']});
  let errors='',provider;anvil.stderr.on('data',d=>errors+=d);const evidence=[];
  try{
    for(let i=0;i<100;i++){if(anvil.exitCode!==null)throw Error(errors);try{const r=await fetch(rpc,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_chainId',params:[]})});if((await r.json()).result==='0x7a69')break;}catch{}await new Promise(r=>setTimeout(r,100));}
    provider=new ethers.JsonRpcProvider(rpc,31337,{staticNetwork:true,cacheTimeout:-1});provider.pollingInterval=20;
    const signer=await provider.getSigner(0),other=await provider.getSigner(1),owner=await signer.getAddress(),recipient=await other.getAddress();
    const deploy=async(n,args=[])=>{const a=A(n),c=await new ethers.ContractFactory(a.abi,a.bytecode,signer).deploy(...args);await c.waitForDeployment();return c;};
    const send=async tx=>(await tx).wait();
    const chain={provider,address:owner,payer:owner,chainId:31337,generation:0,async assertContext(g){assert.equal(g,this.generation);},async prepareExternal(p){this.plan=p;return p;}};
    const client=new OfficialProtocolClient(chain);
    const run=async p=>{for(const s of p.spend||[]){const token=new ethers.Contract(s.tokenAddress,['function approve(address,uint256) returns(bool)'],signer);await send(token.approve(p.request.to,s.amount));}const receipt=await send(signer.sendTransaction(p.request));const verification=await verifyProtocolReceipt(provider,{...p,account:owner,payer:owner,final:true},receipt);assert.equal(verification.verified,true);return receipt;};
    const mineTo=async n=>{let current=await provider.getBlockNumber();if(n>current)await provider.send('anvil_mine',[ethers.toQuantity(n-current)]);};
    const timeTo=async n=>{await provider.send('evm_setNextBlockTimestamp',[n]);await provider.send('evm_mine',[]);};
    const manager=await deploy('PoolManager',[owner]),controller=await deploy('ProtocolFeeController',[owner]),factory=await deploy('ContinuousClearingAuctionFactory',[controller.target]),launcher=await deploy('OfficialCCALauncher',[factory.target]),token=await deploy('OfficialLaunchToken',['CCA Token','CCA',ethers.parseEther('1000000'),owner]);
    await verifyProtocol(provider,factory.target,'ContinuousClearingAuctionFactory');
    const current=await provider.getBlockNumber(),input={factory:factory.target,launcher:launcher.target,token:token.target,currency:ethers.ZeroAddress,amount:'1000',floorPrice:'0.00001',priceStep:'0.000001',startBlock:current+12,endBlock:current+52,claimBlock:current+53,recipient:owner};
    const p=await client.ccaCreate(input);await run(p);const auction=new ethers.Contract(p.meta.auction,A('ContinuousClearingAuction').abi,signer);assert.equal(await token.balanceOf(auction.target),ethers.parseEther('1000'));
    await assert.rejects(client.ccaBid({auction:auction.target,amount:'1',maxPrice:'0.001'}));
    await mineTo(input.startBlock);const bid=await client.ccaBid({auction:auction.target,amount:'1',maxPrice:'0.001',recipient});await run(bid);
    assert.equal((await auction.bids(0)).owner,recipient);
    await send(token.transfer(recipient,1n)); // unrelated ERC20 event must not enter auction history
    const history=await client.readCCA({auction:auction.target,owner:recipient,bidLimit:1});assert.deepEqual(history.bids.map(b=>b.id),['0']);assert.equal(history.history.totalBids,1);
    assert.equal((await client.readCCA({auction:auction.target,owner:recipient,bidOffset:1,bidLimit:1})).bids.length,0);
    assert.equal((await client.readCCA({auction:auction.target,owner})).bids.length,0);
    const cpLogs=await protocolLogs(provider,{address:auction.target,event:auction.filters.CheckpointUpdated()},{fromBlock:0});assert.ok(cpLogs.every(l=>l.address.toLowerCase()===auction.target.toLowerCase()&&auction.interface.parseLog(l).name==='CheckpointUpdated'));
    await assert.rejects(protocolLogs(provider,auction.filters.BidSubmitted(),{fromBlock:0}));
    await assert.rejects(client.readCCA({auction:auction.target,owner:recipient,bidLimit:101}));
await mineTo(input.claimBlock+1);await run(await client.ccaAction({auction:auction.target,action:'checkpoint'}));await run(await client.ccaAction({auction:auction.target,action:'exit',bidId:0}));assert.ok((await auction.bids(0)).tokensFilled>0n);const before=await token.balanceOf(recipient);await run(await client.ccaAction({auction:auction.target,action:'claim',bidId:0}));assert.ok(await token.balanceOf(recipient)>before);await run(await client.ccaAction({auction:auction.target,action:'sweepCurrency'}));await run(await client.ccaAction({auction:auction.target,action:'sweepTokens'}));await assert.rejects(client.ccaAction({auction:auction.target,action:'claim',bidId:0}));const claimedBalance=await token.balanceOf(recipient);await send(auction.claimTokens(0));assert.equal(await token.balanceOf(recipient),claimedBalance);
    evidence.push('Official CCA v2.1.0: atomic create/funding, pre-start rejection, actual bid, checkpoint, bid exit/refund, claim to independent owner, proceeds and unsold-token sweeps.');
    // Miss the minimum: the actual protocol returns the full bid currency, not fabricated local accounting.
    const nowBlock=await provider.getBlockNumber(),failed=await client.ccaCreate({...input,startBlock:nowBlock+10,endBlock:nowBlock+30,claimBlock:nowBlock+31,minimumRaise:'10'});await run(failed);await mineTo(nowBlock+10);await run(await client.ccaBid({auction:failed.meta.auction,amount:'1',maxPrice:'0.001',recipient}));await mineTo(nowBlock+32);await run(await client.ccaAction({auction:failed.meta.auction,action:'checkpoint'}));const ethBefore=await provider.getBalance(recipient);await run(await client.ccaAction({auction:failed.meta.auction,action:'exit',bidId:0}));assert.equal(await provider.getBalance(recipient)-ethBefore,ethers.parseEther('1'));evidence.push('Official CCA failed minimum: full native bid refund to its owner, triggered by a different caller.');
    const permit=await deploy('Permit2'),weth=await deploy('WETH'),pm=await deploy('PositionManager',[manager.target,permit.target,100000,ethers.ZeroAddress,weth.target]),create2=await deploy('OfficialCreate2');
    const la=A('LBPStrategy'),largs=[pm.target,manager.target,factory.target],linit=(await new ethers.ContractFactory(la.abi,la.bytecode).getDeployTransaction(...largs)).data,mined=await mineProtocolSalt({deployer:create2.target,caller:owner,initCodeHash:ethers.keccak256(linit),flags:0x2000});await send(create2.deploy(mined.salt,linit));const strategy=new ethers.Contract(mined.address,la.abi,signer);
    const b0=await provider.getBlockNumber(),mp=await client.ccaCreate({...input,strategy:strategy.target,amount:'2000',reserve:'1000',startBlock:b0+10,endBlock:b0+50,claimBlock:b0+51,positionRecipient:recipient});await run(mp);await mineTo(b0+10);await run(await client.ccaBid({auction:mp.meta.auction,amount:'1',maxPrice:'0.001'}));await mineTo(b0+52);await run(await client.ccaAction({auction:mp.meta.auction,action:'checkpoint'}));const pmBefore=await pm.balanceOf(recipient),mr=await run(await client.ccaAction({auction:mp.meta.auction,strategy:strategy.target,action:'migrate'}));const me=mr.logs.map(l=>{try{return strategy.interface.parseLog(l);}catch{return null;}});assert.ok(me.some(x=>x?.name==='Migrated'),me.map(x=>x?.name).join(','));assert.ok(await pm.balanceOf(recipient)>pmBefore);await assert.rejects(strategy.migrate.staticCall(mp.meta.auction));evidence.push('Official Liquidity Launcher: deployed a correctly mined strategy hook; funded CCA migrated into the real PoolManager and issued the recipient a real Uniswap position NFT; repeat migration rejected.');
    // A genuine migration failure returns reserve tokens and declares failure instead of reporting a pool.
    await send(controller.setProtocolFeeRecipient(owner));await send(controller.setGlobalProtocolFeePips(1000000));
    const rb=await provider.getBlockNumber(),recovery=await client.ccaCreate({...input,strategy:strategy.target,amount:'2000',reserve:'1000',startBlock:rb+10,endBlock:rb+30,claimBlock:rb+31,positionRecipient:recipient,fee:500,tickSpacing:10});await run(recovery);await mineTo(rb+10);await run(await client.ccaBid({auction:recovery.meta.auction,amount:'1',maxPrice:'0.001'}));await mineTo(rb+32);await run(await client.ccaAction({auction:recovery.meta.auction,action:'checkpoint'}));const reserveBefore=await token.balanceOf(owner),recoveryReceipt=await run(await client.ccaAction({auction:recovery.meta.auction,strategy:strategy.target,action:'migrate'}));const recoveryEvents=recoveryReceipt.logs.map(l=>{try{return strategy.interface.parseLog(l);}catch{return null;}});assert.ok(recoveryEvents.some(e=>e?.name==='MigrationFailed'));assert.ok(recoveryEvents.some(e=>e?.name==='FundsRecovered'));assert.equal(await token.balanceOf(owner)-reserveBefore,ethers.parseEther('1000'));await send(controller.setGlobalProtocolFeePips(0));evidence.push('Official CCA migration failure: a real fee-controller change exhausted LP currency; official MigrationFailed/FundsRecovered events verified, and reserve tokens recovered without falsely recording pool success.');
    // Archived partial bids recover from exact stored links, without rescanning years of logs.
    const archiveStart=await provider.getBlockNumber(),archived=await client.ccaCreate({...input,startBlock:archiveStart+10,endBlock:archiveStart+50,claimBlock:archiveStart+51});await run(archived);await mineTo(archiveStart+10);await run(await client.ccaBid({auction:archived.meta.auction,amount:'0.001',maxPrice:'0.00002',recipient}));await mineTo(archiveStart+16);await run(await client.ccaBid({auction:archived.meta.auction,amount:'1',maxPrice:'0.001'}));await mineTo(archiveStart+52);await run(await client.ccaAction({auction:archived.meta.auction,action:'checkpoint'}));const archiveAuction=new ethers.Contract(archived.meta.auction,A('ContinuousClearingAuction').abi,signer);assert.ok((await archiveAuction.bids(0)).maxPrice<await archiveAuction.clearingPrice());const previousGetLogs=provider.getLogs.bind(provider);provider.getLogs=async()=>{throw Error('Historical event queries are unavailable on this RPC');};const partialPlan=await client.ccaAction({auction:archived.meta.auction,action:'exit',bidId:0});assert.equal(archiveAuction.interface.parseTransaction(partialPlan.request).name,'exitPartiallyFilledBid');await assert.rejects(client.ccaAction({auction:archived.meta.auction,action:'exit',bidId:0,lastFullyFilledCheckpointBlock:0,outbidBlock:0}));await run(partialPlan);assert.ok((await archiveAuction.bids(0)).exitedBlock>0n);provider.getLogs=previousGetLogs;evidence.push('CCA partial bid with historical event RPC unavailable: exact linked checkpoint state selects a valid funded exit and rejects invalid manual hints.');
    // Actual Airlock + official dynamic Doppler + official v2 migrator. No mock pool or settlement.
    const airlock=await deploy('Airlock',[owner]),tokenFactory=await deploy('DopplerERC20V1Factory',[airlock.target]),governance=await deploy('LaunchpadGovernanceFactory'),deployer=await deploy('DopplerDeployer',[manager.target]),initializer=await deploy('UniswapV4Initializer',[airlock.target,manager.target,deployer.target]),topUp=await deploy('TopUpDistributor',[airlock.target]);
    const v2code=fs.readFileSync(path.join(base,'vendor/doppler/script/utils/uniswapV2Factory.bytecode'),'utf8').trim(),v2=new ethers.ContractFactory(['constructor(address)','function getPair(address,address) view returns(address)'],'0x'+v2code.replace(/^0x/,''),signer);const v2factory=await v2.deploy(owner);await v2factory.waitForDeployment();
    const migrator=await deploy('UniswapV2MigratorSplit',[airlock.target,v2factory.target,topUp.target,weth.target]),router=await deploy('OfficialV4SwapRouter',[manager.target]),quoteLens=await deploy('OfficialV4QuoteLens',[manager.target]);await run(await client.approveModules({airlock:airlock.target,modules:[{address:tokenFactory.target,state:1},{address:governance.target,state:2},{address:initializer.target,state:3},{address:migrator.target,state:4}]}));
    const config={airlock:airlock.target,tokenFactory:tokenFactory.target,governanceFactory:governance.target,poolInitializer:initializer.target,liquidityMigrator:migrator.target};
    async function createDoppler(minimumRaise,maximumRaise,searchStart=0){const t=(await provider.getBlock('latest')).timestamp;const p=await client.dopplerCreate({...config,name:'Doppler Real',symbol:'DREAL',supply:'100000',amount:'100000',numeraire:ethers.ZeroAddress,minimumRaise,maximumRaise,starts:t+40,ends:t+440,epochLength:40,gamma:800,startingTick:6000,endingTick:60000,tickSpacing:2,slugs:10,fee:200,recipient,searchStart});await run(p);return {p,t,hook:new ethers.Contract(p.meta.hook,A('Doppler').abi,signer),asset:new ethers.Contract(p.meta.token,A('DopplerERC20V1').abi,signer)};}
    const dp=await createDoppler('0.01','10');assert.equal(dp.asset.target,dopplerCloneAddress(tokenFactory.target,await tokenFactory.IMPLEMENTATION(),airlock.interface.decodeFunctionData('create',dp.p.request.data)[0].salt));await assert.rejects(airlock.migrate.staticCall(dp.asset.target));await timeTo(dp.t+40);
    const trade={airlock:airlock.target,asset:dp.asset.target,router:router.target,quoter:quoteLens.target,side:'buy',amount:'1',minimumOut:'0.000001',recipient:owner};const stateBefore=Array.from(await dp.hook.state()),quoted=await client.dopplerQuote(trade);assert.equal(await dp.asset.balanceOf(owner),0n);assert.deepEqual(Array.from(await dp.hook.state()),stateBefore);const tradeReceipt=await run(await client.dopplerSwap(trade));const owned=await dp.asset.balanceOf(owner);assert.ok(owned>0n);const swapEvent=tradeReceipt.logs.map(l=>{try{return router.interface.parseLog(l);}catch{return null;}}).find(e=>e?.name==='Swapped');assert.equal(swapEvent.args.received,BigInt(quoted.received));await assert.rejects(router.unlockCallback.staticCall('0x'));await assert.rejects(run(await client.dopplerSwap({...trade,minimumOut:'1000000000'})));evidence.push('Exact Doppler quote: the actual PoolManager/hook execution rolled back without balance/state changes; the resulting fee-inclusive quote matched the funded swap output.');
    await timeTo(dp.t+450);const dr=await run(await client.dopplerAction({...config,asset:dp.asset.target,action:'migrate'}));assert.ok(dr.logs.some(l=>{try{return airlock.interface.parseLog(l)?.name==='Migrate';}catch{return false;}}));assert.equal(await dp.asset.isPoolLocked(),false);assert.equal(await dp.asset.owner(),recipient);const ds=await client.readDoppler({airlock:airlock.target,asset:dp.asset.target});assert.equal(ds.phase,'migrated');const pair=new ethers.Contract(ds.migrationPool,['function balanceOf(address) view returns(uint256)','function getReserves() view returns(uint112,uint112,uint32)'],provider);assert.ok(await pair.balanceOf(recipient)>0n);assert.ok((await pair.getReserves())[0]>0n);await assert.rejects(airlock.migrate.staticCall(dp.asset.target));await timeTo(ds.lpLock.minUnlockDate+1);await run(await client.dopplerAction({airlock:airlock.target,asset:dp.asset.target,action:'exitLockedLP'}));evidence.push('Official Doppler: actual Airlock creation, CREATE2 hook mining, dynamic v4 swap, bounded slippage rejection, permissionless migration into a real v2 pair, recipient LP custody, one-year protocol LP unlock, and repeat migration rejection.');
    const fp=await createDoppler('10','100',1000000);await timeTo(fp.t+40);await run(await client.dopplerSwap({...trade,asset:fp.asset.target}));const bought=await fp.asset.balanceOf(owner);assert.ok(bought>0n);await timeTo(fp.t+450);const beforeRefund=await provider.getBalance(recipient);await run(await client.dopplerSwap({...trade,asset:fp.asset.target,side:'sell',amount:ethers.formatEther(bought),minimumOut:'0.000001',recipient}));assert.ok(await provider.getBalance(recipient)>beforeRefund);assert.equal(await fp.hook.insufficientProceeds(),true);await assert.rejects(airlock.migrate.staticCall(fp.asset.target));await assert.rejects(client.dopplerSwap({...trade,asset:fp.asset.target}));evidence.push('Official Doppler failed minimum: actual onchain refund-curve sell returns currency, then blocks buys and migration. It does not pretend to refund the historical purchase price exactly.');
    assert.equal(await provider.getBalance(router.target),0n);assert.equal(await fp.asset.balanceOf(router.target),0n);
    await assert.rejects(verifyProtocol(provider,router.target,'Airlock'));
    fs.writeFileSync(path.join(base,'artifacts/lifecycle-evidence.json'),json({chainId:31337,source:'actual vendored contracts compiled with pinned solc, funded local Anvil transactions',evidence}));
    console.log(evidence.join('\n'));
  } finally{provider?.destroy();anvil.kill('SIGTERM');}
});
function json(x){return JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v,null,2)+'\n';}
