/* Private bodies and memory passphrases exist only in this controller's volatile cache. */
let memOpen=0,memParent=0,memDraft=null,memQuery='',memMode='all',memFormThrough=null,memFormOriginal=false,memWorking=false;
let memSessionPass='',memSessionActor='',memSessionAt=0,memSessionEpoch=0;
const memUnlocked=new Map();
function memLock(){memSessionEpoch++;memSessionPass='';memSessionActor='';memSessionAt=0;memUnlocked.clear();memDraft=null;memParent=0;memQuery='';if(ixReview?.memoryPrivate)ixReview=null;}
function memCheckSession(){if(memSessionActor&& (memSessionActor!==W().s.actor||Date.now()-memSessionAt>600000)){memLock();return true;}return false;}
function memSession(pass){memSessionPass=pass;memSessionActor=W().s.actor;memSessionAt=Date.now();}
function memText(label,id,value='',rows=3){return `<div class="ix-field"><label for="mem-${id}">${label}</label><textarea id="mem-${id}" rows="${rows}" maxlength="3000">${esc(value)}</textarea></div>`;}
function memVal(id){return ix$('#mem-'+id)?.value||'';}
function memGetBody(){return memoryBody(Object.fromEntries(['title','thesis','setup','invalidation','exitPlan','horizon','risk','tags','feeling','lesson'].map(k=>[k,memVal(k)])));}
function memEditor(trade=false){const d=memDraft||{};return `<div class="mem-editor">${trade?'<label for="mem-thesis">Why this trade?</label>':''}${trade?`<textarea id="mem-thesis" rows="3" maxlength="3000" placeholder="The thesis, not just the ticker. Leaving this blank keeps the swap journal optional.">${esc(d.thesis||'')}</textarea>`:field('Memory title','mem-title',d.title||'').replaceAll('ix-mem-title','mem-title')+memText(memParent?'What changed? What did you learn?':'Something worth remembering','thesis',d.thesis||'',5)}
 <details ${trade?'':'open'}><summary>${trade?'Decision details · optional':'Context · optional'}</summary><div class="ix-row">${memText('Setup / evidence','setup',d.setup||'',2)}${memText('What would invalidate this?','invalidation',d.invalidation||'',2)}</div><div class="ix-row">${memText('Exit / review plan','exitPlan',d.exitPlan||'',2)}${memText('Time horizon','horizon',d.horizon||'',2)}</div><div class="ix-row">${memText('Planned risk · state amount and units','risk',d.risk||'',2)}${memText('Tags · comma separated','tags',d.tags||'',2)}</div>${memText('How I felt · your description, not an AI diagnosis','feeling',d.feeling||'',2)}<p class="ix-small">These are notes, not executable stop-loss orders, forecasts, or risk limits. The swap's separate minimum output still controls execution.</p></details>
 <div class="ix-row"><div class="ix-field"><label for="mem-privacy">Who can read the body?</label><select id="mem-privacy"><option value="encrypted">Private · encrypted with my memory passphrase</option><option value="public">Public · readable in the archive</option></select></div><div class="ix-field"><label for="mem-pass">Memory passphrase ${memSessionPass?'· unlocked for this session':''}</label><input id="mem-pass" type="password" autocomplete="new-password" placeholder="${memSessionPass?'Leave blank to use this session':'At least 12 characters. Not a wallet seed.'}"></div></div>
 <label class="ix-check"><input id="mem-imprint" type="checkbox" checked> Let this entry's opaque commitment influence the form</label><p class="ix-small">The body is not analyzed for shape. Private bodies stay ciphertext in exports; timestamps, authorship, links and approximate length remain visible. Save a unique passphrase separately—losing it loses access. Neither selling the NFT nor switching the demo persona reveals the key.</p></div>`;}
function memTradeEditor(){return `<details class="mem-trade"><summary>Remember why · optional trading journal</summary>${memEditor(true)}</details>`;}
function memBinding(n){return ixEngine.mem.bindings.find(b=>b.entry===n.header.id);}
function memBodyFor(n){return n.payload.mode==='public'?n.payload.body:memUnlocked.get(n.digest);}
function memNoteCard(n){const h=n.header,b=memBodyFor(n),binding=memBinding(n),refs=ixEngine.mem.entries.filter(x=>x.header.parent===h.id);return `<article class="ix-card mem-note"><div class="ix-inline"><h4>${esc(b?.title|| (h.phase==='before'?'Decision before a swap':h.phase==='reflection'?'A later reflection':'A memory'))}</h4><span class="ix-tag">${n.payload.mode==='public'?'PUBLIC':b?'DECRYPTED HERE':'ENCRYPTED'}</span></div><p class="ix-small">${esc(personLabel(h.author))} · artifact #${h.identity} · custody ${h.epoch} · ${when(h.time)} · ${h.phase}</p><p class="mem-excerpt">${b?esc((b.thesis||b.lesson).slice(0,200)):'Only the body is locked. Its context and commitment are inspectable.'}</p>${binding?`<p class="ix-small">Linked successful local swap #${binding.receipt} · ${money(binding.result.received,binding.result.asset)}</p>`:''}<div class="ix-actions">${B('mem-open','Read & compare →',h.id)}${refs.length?`<span class="ix-small">${refs.length} later reflection${refs.length>1?'s':''}</span>`:''}</div></article>`;}
function memPage(){memCheckSession();if(memOpen)return memReadPage();const w=W(),own=ixEngine.mem.entries.filter(n=>n.header.author===w.s.actor),trades=w.s.events.filter(e=>e.kind==='SWAPPED'&&e.actor===w.s.actor),before=own.filter(n=>n.header.phase==='before'),reviewed=before.filter(n=>own.some(r=>r.header.parent===n.header.id));const notes=own.filter(n=>{const b=memBodyFor(n);return(memMode==='all'||memMode==='review'?memMode!=='review'||n.header.phase==='before'&&!own.some(r=>r.header.parent===n.header.id):n.header.phase===memMode)&&(!memQuery||b&&stable(b).toLowerCase().includes(memQuery.toLowerCase()));});
 const invalidations=before.map(memBodyFor).filter(Boolean).filter(b=>b.invalidation).length,readable=before.filter(n=>memBodyFor(n)).length;
 return `<div class="mem-heading"><span class="ix-kicker">MEMORY / DECISIONS, NOT JUST TRANSACTIONS</span><h3>Remember what you knew then.</h3><p>Keep the reason before an action and the reflection after it. Neither overwrites the other.</p></div><div class="mem-stats">${fact('Recorded swaps',trades.length)}${fact('With a before-note',before.length)}${fact('Reviewed decisions',reviewed.length+' / '+before.length)}${fact('Invalidation recorded',invalidations+' / '+readable+' readable notes')}</div>
 <div class="ix-actions">${B('mem-new','Write any memory →')}${B('mem-form','Explore lived form →')}${B('mem-lock','Lock private bodies')}${B('mem-export-fills','Export execution CSV')}</div><p class="ix-small">Process statistics, not a profitability score. No current prices, tax basis, gas valuation, portfolio P&L, or guaranteed improvement are inferred.</p>
 <div class="ix-row"><div class="ix-field"><label for="mem-search">Search readable bodies</label><input id="mem-search" value="${esc(memQuery)}" placeholder="Thesis, tags, lesson…"></div><div class="ix-field"><label for="mem-filter">View</label><select id="mem-filter">${[['all','All my memories'],['before','Before a swap'],['memory','General memories'],['reflection','Reflections'],['review','Awaiting reflection']].map(([v,n])=>`<option value="${v}" ${memMode===v?'selected':''}>${n}</option>`).join('')}</select></div></div>
 <p class="ix-small">Private search works only on bodies explicitly decrypted in this session. You are viewing ${esc(personLabel(w.s.actor))}'s journal; changing the demo persona is not authentication.</p><div class="ix-stack">${notes.length?notes.slice().reverse().map(memNoteCard).join(''):'<div class="ix-card"><h4>A record begins with one honest sentence.</h4><p>Use “Remember why” inside Trade, or write a memory here without moving any money.</p></div>'}</div>`;}
function memReadPage(){const n=ixEngine.entry(memOpen),h=n.header,b=memBodyFor(n),bind=memBinding(n),r=bind?W().s.events.find(e=>e.seq===bind.receipt):null;return `${B('mem-back','← My journal')}<h3>${esc(b?.title||'A preserved moment.')}</h3>${fact('Authored by',esc(personLabel(h.author)))}${fact('Artifact / custody at inscription','#'+h.identity+' / '+h.epoch)}${fact('Recorded local time',when(h.time))}${fact('Phase',h.phase)}<span class="ix-code">${esc(n.digest)}</span>
 ${!b?`<form id="mem-unlock-form"><label for="mem-unlock-pass">Memory passphrase</label><input id="mem-unlock-pass" type="password" autocomplete="current-password"><button class="ix-button primary" type="submit">Decrypt on this device →</button></form><p class="ix-small">No server receives this passphrase. A compromised browser can still read an unlocked memory. Lost passphrases cannot be reset.</p>`:`<div class="mem-body">${Object.entries(b).filter(([,v])=>v).map(([k,v])=>`<section><h4>${esc({thesis:'What I thought',exitPlan:'Exit / review plan',invalidation:'What would invalidate this',risk:'Planned risk',feeling:'Self-described feeling',lesson:'Lesson'}[k]||k)}</h4><p>${esc(v)}</p></section>`).join('')}</div>`}
 ${r?`<hr class="ix-divider"><h4>What actually happened in the rehearsal</h4>${fact('Provided',money(r.data.amount,r.data.input))}${fact('Received',money(r.data.received,r.data.output))}${fact('Linked receipt','#'+r.seq)}${fact('Output commitment',bind?.result.exitPlanId?'Vesting exit #'+bind.result.exitPlanId:r.data.lock?'Lock #'+r.data.lock:'None')}${bind?.result.exitPlanId?B('tab','Follow scheduled sales & receipts','exits'):''}<span class="ix-code">${esc(r.digest)}</span><p class="ix-small">The note was appended before execution within one atomic local operation. It is not an earlier blockchain timestamp or evidence that a decision was good.</p>`:''}
 <div class="ix-actions">${h.author===W().s.actor?B('mem-reflect','Add a reflection →',h.id):''}${B('trace','Inspect inscription receipt',n.event)}${B('mem-form-at','View this activity layer',n.event)}</div><p class="ix-small">Reflections append. They cannot silently edit this moment. Personal plaintext and decryption keys are never automatically transferred with the artifact.</p><div class="ix-stack">${ixEngine.mem.entries.filter(x=>x.header.parent===h.id).map(memNoteCard).join('')}</div>`;}
function memWritePage(){return `${B('mem-back','← My journal')}<h3>${memParent?'A reflection, not a rewrite.':'Keep a moment.'}</h3><p>${memParent?'The original entry stays untouched. This note is authored now, under your original authorship.':'An idea, a lesson, a milestone, or a personal memory. No trade is necessary.'}</p><form id="mem-write-form">${memEditor()}<button class="ix-button primary" type="submit">Review the inscription →</button></form>`;}
function memFormPage(){const live=ixEngine.form(),at=memFormThrough===null?live:ixEngine.form(undefined,memFormThrough);return `<span class="ix-kicker">LIVED FORM / DETERMINISTIC LOCAL HISTORY</span><h3>The same organism. A life of its own.</h3><p>Its density domain, axis proportions, angular folds and twist now develop from typed activity. This is geometry and light structure—not a new mascot or just a hue change.</p><div class="ix-actions">${B('mem-toggle-form',memFormOriginal?'Return to lived form':'Compare original form')}${B('mem-present','Return to present')}${B('mem-watch','Close panel & watch')}</div>${fact('View',memFormOriginal?'Original optical field':memFormThrough===null?'Current lived form':'Historical activity layer · current base genome')}${fact('Contributing records',at.count)}<div class="mem-stats">${FORM_CHANNELS.map((k,i)=>fact(k,at.counts[i])).join('')}</div><span class="ix-code">History root ${esc(at.root)}</span><p class="ix-small">Amount and profit are not growth scores. Each category has diminishing influence; all deformation is bounded. Private text is never read to shape the body. A visual projection is not guaranteed unique and has no rarity or return promise.</p>
 <div class="mem-timeline">${B('mem-form-at','Before this chapter',ixEngine.mem.start)}${live.marks.slice(-100).reverse().map(m=>B('mem-form-at','#'+m.seq+' · '+esc(m.kind)+' · '+when(m.time),m.seq)).join('')}</div><p class="ix-small">This chapter begins when v1.7 opens or an older archive is explicitly imported. It does not secretly reinterpret earlier activity. This timeline replays the activity layer on the current base genome; manual Evolve snapshots remain in the original History. The original audit remains separate. Viewing an older form does not roll back any asset or permission.</p>`;}
async function memSealDraft(phase,plan=null){const sessionEpoch=memSessionEpoch;const body=memGetBody(),mode=memVal('privacy'),pass=memVal('pass')||memSessionPass;if(!['encrypted','public'].includes(mode))throw Error('Select a visibility mode.');memDraft=structuredClone(body);const header=ixEngine.memoryHeader({phase,parent:phase==='reflection'?memParent:0,plan:plan?.digest||MEM_ZERO,form:!!ix$('#mem-imprint')?.checked});const payload=mode==='public'?{mode:'public',body}:await encryptMemory(header,body,pass);if(memSessionEpoch!==sessionEpoch||document.hidden||W().s.actor!==header.author||W().s.selected!==header.identity||W().s.now!==header.time)throw Error('The journal context changed while preparing encryption. Review again.');if(mode==='encrypted')memSession(pass);return memorySeal(header,payload);}
async function memPrepareTrade(plan){if(!memVal('thesis').trim())return planReview(plan);if(memWorking)return;memWorking=true;try{const n=await memSealDraft('before',plan);planReview(plan);ixReview.note=n;ixReview.memoryPrivate=n.payload.mode==='encrypted';ixReview.html+=`<hr class="ix-divider"><h4>Reason preserved with this trade</h4>${fact('Visibility',n.payload.mode==='encrypted'?'Encrypted body · key stays with you':'Public body · readable by everyone with the archive')}${fact('Form contribution',n.header.form?'Opaque commitment only':'None')}<p>${esc(memDraft.thesis)}</p><span class="ix-code">${esc(n.digest)}</span>`;draw();}finally{memWorking=false;}}
async function memSubmit(form){if(memWorking)return;memWorking=true;try{
 if(form==='mem-unlock-form'){const n=ixEngine.entry(memOpen),pass=memVal('unlock-pass'),sessionEpoch=memSessionEpoch,actor=W().s.actor;const body=await decryptMemory(n.header,n.payload,pass);if(memSessionEpoch!==sessionEpoch||document.hidden||W().s.actor!==actor||memOpen!==n.header.id)throw Error('The private session changed while decrypting. No body was opened.');memUnlocked.set(n.digest,body);memSession(pass);draw();notice('Decrypted locally. Lock private bodies to clear this session.');return;}
 if(form==='mem-write-form'){sourceCheck();const n=await memSealDraft(memParent?'reflection':'memory');simpleReview('Inscribe this moment.',n.payload.mode==='encrypted'?'Only encrypted body bytes enter the archive. The passphrase is not saved.':'This body is public in the local archive. Future public-chain storage would be permanently readable.',`<p>${esc(memDraft.thesis)}</p>${fact('Authored by',personLabel(n.header.author))}${fact('Phase',n.header.phase)}<span class="ix-code">${n.digest}</span>`,()=>{ixEngine.appendMemory(n);memOpen=n.header.id;memDraft=null;memParent=0;ixView='journal';});ixReview.memoryPrivate=n.payload.mode==='encrypted';return;}
 }finally{memWorking=false;}}
function memExportFills(){const rows=[['provenance','sequence','local_unix_seconds','artifact','author','input','input_raw','output','output_raw','receipt_digest','before_entry']];for(const e of W().s.events.filter(x=>x.kind==='SWAPPED'&&x.actor===W().s.actor)){const n=ixEngine.mem.bindings.find(x=>x.receipt===e.seq);rows.push(['UNSIGNED LOCAL REHEARSAL',e.seq,e.time,e.identity,e.actor,e.data.input,e.data.amount,e.data.output,e.data.received,e.digest,n?.entry||'']);}const csv=rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='idfbi-local-executions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function memAction(act,id){if(act==='mem-new'){memParent=0;memDraft=null;memOpen=0;return nav('memory-write');}if(act==='mem-back'){memOpen=0;memParent=0;memDraft=null;return nav('journal');}if(act==='mem-open'){memOpen=Number(id);return nav('journal');}if(act==='mem-reflect'){const n=ixEngine.entry(id);if(n.header.author!==W().s.actor)throw Error('Only the original author can reflect.');W().select(n.header.identity);memParent=n.header.id;memDraft=null;return nav('memory-write');}if(act==='mem-lock'){memLock();draw();return notice('Private bodies and the session passphrase were cleared. Encrypted exports are unchanged.');}if(act==='mem-export-fills')return memExportFills();if(act==='mem-form')return nav('form');if(act==='mem-form-at'){memFormThrough=Number(id);memFormOriginal=false;nav('form');return;}if(act==='mem-present'){memFormThrough=null;memFormOriginal=false;return draw();}if(act==='mem-toggle-form'){memFormOriginal=!memFormOriginal;return draw();}if(act==='mem-watch'){ix$('#instrument-dialog').close();return;}throw Error('Unknown memory action.');}
function memAfterDraw(){memCheckSession();const q=ix$('#mem-search');if(q)q.addEventListener('change',()=>{memQuery=q.value;draw();});const f=ix$('#mem-filter');if(f)f.addEventListener('change',()=>{memMode=f.value;draw();});if(ixView==='trade'&&!ixReview){ix$('#ix-trade-form .primary').insertAdjacentHTML('beforebegin',memTradeEditor());}memorySyncField();}
