/* Native controls are captured by the same blue-object creation coordinator. */
function exEditor(required=false){return `<section class="ex-compose"><label class="ix-check"><input id="ix-exit-enabled" type="checkbox" ${required?'checked disabled':''}> Sell as the lock matures</label><p class="ix-small">A separate funded schedule. Each installment keeps its own minimum received amount and sale window.</p><label for="ix-exit-asset">Receive from future sales</label><select id="ix-exit-asset">${assets('ETH')}</select><div class="ix-row">${field('Installments · 1–64','exit-count',4,'number')}${field('Days between installments','exit-interval',7,'number')}</div>${field('Minimum total received · chosen asset units','exit-total','0.01')}${B('ex-generate','Generate equal installments')}${B('ex-maturity','Sell everything at maturity')}<label for="ix-exit-rows">Custom schedule · days after lock, percentage, minimum received</label><textarea id="ix-exit-rows" rows="5" spellcheck="false">0, 25, 0.0025\n7, 25, 0.0025\n14, 25, 0.0025\n21, 25, 0.0025</textarea>${field('Each sale may execute for this many days','exit-grace',7,'number')}<p class="ix-small">Edit every row. Percentages must total 100%. These are fixed minimums, not price predictions. The last installment receives indivisible allocation dust. Failed sales keep their tokens.</p></section>`;}
function exRead(){const rows=String(input('exit-rows')).trim().split('\n').map(line=>{const [day,percent,min,...rest]=line.split(',').map(v=>v.trim());if(rest.length||!/^\d+(?:\.\d{1,2})?$/.test(percent||''))throw Error('Use one row per installment: days, percentage, minimum received.');const bps=Math.round(Number(percent)*100);return {offsetDays:Number(day),bps,minOut:String(wei(min)),graceDays:Number(input('exit-grace'))};});return {asset:input('exit-asset'),rows};}
function exReview(p){if(!p.intent.exit)return '';const spec=p.intent.exit,rows=exitSlices(p.preview.received,spec,W().s.now+p.intent.days*DAY);return `<h4>Your vesting exit</h4>${fact('Sales receive',esc(spec.asset))}${fact('Proceeds recipient','This artifact account · follows ownership')}<div class="ex-slices">${rows.map(s=>`<article><span>${when(s.due)}</span><strong>${money(s.amount,p.preview.asset)} → at least ${money(s.minOut,spec.asset)}</strong><small>Sale window ends ${when(s.expires)}</small></article>`).join('')}</div><p class="ix-small">Sales require execution. Cancelling stops future sales and preserves each vesting date. Custody changes suspend this authorization. No principal is assigned to fee recipients.</p>`;}
function exPage(){const w=W(),plans=ixEngine.exits.filter(p=>p.identity===w.s.selected);return `<div class="ex-intro"><span class="ix-tag">LOCAL REHEARSAL</span><h3>Let time unfold your decision.</h3><p>Remember the reason. Vest the position. Sell in chosen installments. Return to what actually happened.</p><div class="ix-actions">${B('tab','Buy, remember & schedule','trade')}${B('clock','Rehearsal clock')}${B('ex-new','Schedule an existing balance')}${B('ex-live','Open onchain exit desk')}${B('ex-export','Export exit ledger')}</div><p class="ix-small">No live keeper is configured here. Dates make sales eligible; run an eligible installment to rehearse its execution. Live execution uses the separate VestedExitVault contract and a funded executor.</p></div>${plans.length?plans.slice().reverse().map(p=>{const a=w.identity(p.identity),notes=ixEngine.mem.bindings.filter(b=>b.receipt===p.originReceipt);return `<article class="ix-card ex-plan"><span class="ix-tag">SCHEDULE ${p.id} · ${p.cancelled?'CANCELLED':a.epoch!==p.epoch?'CUSTODY CHANGED':p.paused?'PAUSED':'AUTHORIZED'}</span><h4>${money(p.total,p.input)} becomes ${esc(p.output)}</h4><p>Proceeds stay with artifact #${p.identity}. Locked tokens are excluded from its free balance.</p><div class="ix-actions">${B('trace','Original commitment',p.receipt)}${notes.map(n=>B('mem-open','Read original decision',n.entry)).join('')}${B('ex-pause',p.paused?'Resume sales':'Pause sales',p.id,'',p.cancelled)}${B('ex-cancel','Cancel future sales',p.id,'',p.cancelled)}${a.epoch!==p.epoch?B('ex-reauthorize','Review new owner authority',p.id,'',p.cancelled):''}</div><div class="ex-slices">${p.slices.map(s=>{const status=ixEngine.exitStatus(p,s);return `<article><span>${s.index+1} / ${esc(status.toUpperCase())} · ${when(s.due)}</span><strong>${money(s.amount,p.input)} → ${s.status==='sold'?money(s.received,p.output):'minimum '+money(s.minOut,p.output)}</strong><small>Window closes ${when(s.expires)}</small><div class="ix-actions">${status==='eligible'?B('ex-sell','Review & execute installment',p.id+':'+s.index):''}${['recoverable','expired'].includes(status)?B('ex-recover','Recover matured tokens',p.id+':'+s.index):''}${s.receipt?B('trace','Inspect actual receipt',s.receipt):''}</div></article>`;}).join('')}</div></article>`;}).join(''):'<div class="ix-card"><h4>No future sale is authorized.</h4><p>Start with a swap and enable “Sell as the lock matures,” or schedule an existing balance.</p></div>'}`;}
async function exAction(act,id){if(act==='ex-live')return window.__confluence.open('exit-live');
 if(act==='ex-new')return modalForm('Give an existing balance a schedule.',`${amountBox('AUR','100')}${field('Initial lock in days','days',30,'number')}${exEditor(true)}`,'ex-fund-form');
 if(act==='ex-export')return saveFile({schema:'anima.exit-ledger/1',scope:'local rehearsal',origin:ixSeed,plans:ixEngine.exits,receipts:W().s.events.filter(e=>e.kind.startsWith('EXIT_'))},'anima-genesis-exits.json');
 if(['ex-generate','ex-maturity'].includes(act)){const count=act==='ex-maturity'?1:Number(input('exit-count')),interval=Number(input('exit-interval'));if(!Number.isSafeInteger(count)||count<1||count>64||!Number.isSafeInteger(interval)||interval<1)throw Error('Choose 1–64 installments and a positive interval.');const total=wei(input('exit-total'));if(total<=0n)throw Error('Enter a positive total minimum.');let used=0,minimum=0n;ix$('#ix-exit-rows').value=Array.from({length:count},(_,i)=>{const bps=i===count-1?10000-used:Math.floor(10000/count);used+=bps;const n=i===count-1?total-minimum:total*BigInt(bps)/10000n;minimum+=n;return `${i*interval}, ${bps/100}, ${exDecimal(n)}`;}).join('\n');ix$('#ix-exit-enabled').checked=true;return;}
 const [pid,idx]=String(id).split(':').map(Number),p=ixEngine.exitPlan(pid);
 if(act==='ex-sell'){const s=p.slices[idx];if(ixEngine.exitStatus(p,s)!=='eligible')throw Error('This installment is not eligible.');const q=W().quote(p.input,p.output,BigInt(s.amount));return simpleReview('Execute this matured installment.', 'Only its segregated tokens may be sold. A rejected minimum leaves them pending.',fact('Sell',money(s.amount,p.input))+fact('Current model quote',money(q.out,p.output))+fact('Minimum',money(s.minOut,p.output))+fact('Recipient','Artifact #'+p.identity),()=>ixEngine.executeExit(pid,idx));}
 if(act==='ex-recover')return simpleReview('Recover matured tokens.', 'Return only this installment to its fixed artifact account; no swap occurs.',fact('Amount',money(p.slices[idx].amount,p.input)),()=>ixEngine.recoverExit(pid,idx));
 const action=act==='ex-pause'?(p.paused?'resume':'pause'):act==='ex-cancel'?'cancel':act==='ex-reauthorize'?'reauthorize':null;if(!action)throw Error('Unknown exit action.');return simpleReview(action==='cancel'?'Stop future sales.':action==='reauthorize'?'Bind this schedule to the current owner.':'Change this schedule’s execution state.',action==='cancel'?'Cancelling is final. Tokens remain vested until their original dates.':action==='reauthorize'?'All amounts, minimums and dates stay fixed. Reauthorization leaves sales paused; resume separately.':'This does not move tokens or change their vesting dates.',fact('Schedule',p.id)+fact('Action',action),()=>ixEngine.changeExit(pid,action));
}
function exDecimal(n){const s=String(n).padStart(19,'0');const tail=s.slice(-18).replace(/0+$/,'');return s.slice(0,-18)+(tail?'.'+tail:'');}
function exSubmit(){const a=input('input'),n=wei(input('amount')),raw={kind:'LOCK',input:a,output:a,amount:String(n),minOut:String(n),days:Number(input('days')),recipient:null,exit:exRead()};planReview(ixEngine.prepare(raw,anchor()));}
